"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowRight,CheckCircle2,Clock3,Database,GitBranch,History,RefreshCw,ShieldCheck,TimerReset,Workflow,Zap} from "lucide-react";
import type {OrchestrationStatus} from "@/lib/autonomous-production-orchestrator";
import styles from "./ScheduledProductionsWorkspace.module.css";

type Props={status:OrchestrationStatus|null;error:string|null};
const stageNames=["research","scripting","storyboard","visual-generation","audio-generation","assembly","quality-assurance","publishing","completed"];
const pretty=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());
const formatTime=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-NG",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short"}).format(new Date(value)):"Not recorded";
const tone=(value:string)=>/failed|blocked|degraded|offline/i.test(value)?"danger":/running|active/i.test(value)?"active":"good";

export function ScheduledProductionsWorkspace({status,error}:Props){
  const interval=Math.max(30,status?.intervalSeconds??30);
  const [now,setNow]=useState(()=>Date.now());
  useEffect(()=>{const handle=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(handle)},[]);
  const seconds=status?.nextRunAt?Math.max(0,Math.ceil((new Date(status.nextRunAt).getTime()-now)/1000)):interval;
  const productions=status?.productions??[];
  const scheduled=productions.filter((item)=>!/(completed|published|archived|failed)/i.test(item.status));
  const ready=productions.filter((item)=>item.readiness>=78&& !/(completed|published|archived|failed)/i.test(item.status));
  const held=(status?.decisions??[]).filter((item)=>/hold|defer|blocked/i.test(item.action));
  const stageCounts=useMemo(()=>stageNames.map((stage)=>({stage,count:scheduled.filter((item)=>item.stage===stage).length})),[scheduled]);
  const state=status?.state??(error?"failed":"waiting");
  const stateLabel=error?"Offline":state==="running"?"Cycle running":state==="waiting"?"Awaiting first cycle":"Engine healthy";
  return <main className={styles.page}>
    <header className={styles.hero}><div><span className={styles.eyebrow}>AUTOMATION HUB / LIVE OPERATIONS</span><h1>Autonomous Scheduled Productions</h1><p>Production start times, capacity windows, dependency gates, and recovery actions are continuously orchestrated without human input.</p></div><div className={styles.heroState}><span className={`${styles.pill} ${styles[tone(stateLabel)]}`}><span className={styles.dot}/>{stateLabel}</span><span className={styles.algorithm}>{status?.algorithmVersion??"adaptive production orchestrator"}</span></div></header>
    {error?<div className={`${styles.banner} ${styles.bannerDanger}`} role="alert"><AlertTriangle size={18}/><span><strong>Scheduler telemetry unavailable.</strong> {error} The engine remains governed by its last persisted state.</span><span className={styles.bannerAction}><RefreshCw size={15}/>Auto-retry in {seconds}s</span></div>:state==="failed"?<div className={`${styles.banner} ${styles.bannerDanger}`} role="alert"><AlertTriangle size={18}/><span><strong>Last cycle failed.</strong> {status?.lastRun?.error??"Recoverable work is queued for the next autonomous retry."}</span><span className={styles.bannerAction}>Recovery is automatic</span></div>:<div className={styles.banner}><CheckCircle2 size={18}/><span><strong>Live database telemetry.</strong> Scheduler decisions, queue state, and execution history are read from the production orchestration store.</span><span className={styles.bannerAction}>No operator action required</span></div>}
    <section className={styles.kpis} aria-label="Scheduler KPIs">
      <Kpi icon={<Database/>} label="Scheduled queue" value={String(scheduled.length)} detail="Persisted productions" tone="blue"/>
      <Kpi icon={<Zap/>} label="Ready signals" value={String(ready.length)} detail={ready.length>scheduled.length?`${ready.length-scheduled.length} awaiting a schedule decision`:"Eligibility evaluated live"} tone="violet"/>
      <Kpi icon={<ShieldCheck/>} label="Average confidence" value={status?.lastRun?`${Math.round(status.lastRun.averageConfidence)}%`:"—"} detail="Quality-gated decisions" tone="green"/>
      <Kpi icon={<Clock3/>} label="Next cycle" value={`${seconds}s`} detail={`Last run ${formatTime(status?.lastRun?.completedAt)}`} tone="amber"/>
    </section>
    <section className={styles.telemetry}><div><span>Last run</span><strong>{formatTime(status?.lastRun?.completedAt)}</strong><small>{status?.lastRun?`${status.lastRun.trigger} · ${status.lastRun.scanned} candidates scanned`:"No completed cycle recorded"}</small></div><div><span>Next run</span><strong>{status?.nextRunAt?formatTime(status.nextRunAt):"Pending"}</strong><small>Autonomous cadence · every {interval}s</small></div><div><span>Decision throughput</span><strong>{status?.lastRun?`${status.lastRun.advanced} advanced`:"—"}</strong><small>{status?.lastRun?`${status.lastRun.held} held · ${status.lastRun.duplicates} duplicates suppressed`:"Awaiting telemetry"}</small></div><div><span>Agents allocated</span><strong>{status?.lastRun?.agents??"—"}</strong><small>Stage-aware specialist routing</small></div></section>
    <section className={styles.mainGrid}><article className={styles.panel}><div className={styles.panelHead}><div><h2>Scheduled-production queue</h2><p>Eligible work persisted by the autonomous orchestration engine.</p></div><span className={styles.count}>{scheduled.length} items</span></div>{scheduled.length===0?<Empty title="No productions are scheduled" detail={ready.length?`${ready.length} ready signal${ready.length===1?"":"s"} remain under evaluation; the next cycle will schedule only work that passes capacity, dependency, and quality gates.`:"No eligible productions are currently persisted."}/>:<div className={styles.tableWrap}><table><caption className={styles.srOnly}>Scheduled production queue</caption><thead><tr><th>Production</th><th>Stage</th><th>Priority</th><th>Readiness</th><th>Progress</th><th>Planned start</th></tr></thead><tbody>{scheduled.map((item)=><tr key={item.id}><td><strong>{item.title}</strong><small>{item.code} · {item.type}</small></td><td><span className={styles.stageTag}><Workflow size={13}/>{pretty(item.stage)}</span></td><td><span className={`${styles.priority} ${styles[item.priority.toLowerCase()]}`}>{item.priority}</span></td><td><strong>{Math.round(item.readiness)}%</strong><small>{Math.round(item.confidence)}% confidence</small></td><td><div className={styles.progress}><span style={{width:`${Math.min(100,Math.max(0,item.progress))}%`}}/></div><small>{Math.round(item.progress)}%</small></td><td>{formatTime(item.plannedStartAt??item.updatedAt)}</td></tr>)}</tbody></table></div>}</article><aside className={styles.sideStack}><article className={styles.panel}><div className={styles.panelHead}><div><h2>Capacity timeline</h2><p>Current work across the 9-stage pipeline.</p></div><GitBranch size={18}/></div><div className={styles.timeline}>{stageCounts.map((item)=><div className={styles.timelineRow} key={item.stage}><span>{pretty(item.stage)}</span><div><i style={{width:`${scheduled.length?Math.max(4,item.count/scheduled.length*100):0}%`}}/></div><strong>{item.count}</strong></div>)}</div></article><article className={styles.panel}><div className={styles.panelHead}><div><h2>Autonomous decisions</h2><p>Persisted actions and rationale.</p></div><History size={18}/></div><div className={styles.log}>{(status?.decisions??[]).slice(0,5).map((item)=><div className={styles.logRow} key={item.id}><span className={`${styles.logIcon} ${styles[tone(item.action)]}`}><ArrowRight size={14}/></span><div><strong>{item.title??"Candidate signal"}</strong><small>{pretty(item.action)} · {Math.round(item.confidence)}% confidence</small></div><time>{formatTime(item.createdAt)}</time></div>)}{!status?.decisions?.length&&<Empty title="No decisions recorded" detail="Decision history will appear after the first cycle."/>}</div></article></aside></section>
    <section className={styles.bottomGrid}><article className={styles.panel}><div className={styles.panelHead}><div><h2>Ready but unscheduled</h2><p>Signals that meet readiness but still require an autonomous scheduling decision.</p></div><span className={styles.count}>{ready.length+held.length}</span></div>{ready.length===0&&held.length===0?<Empty title="No unscheduled ready work" detail="All eligible signals are either scheduled, held by policy, or awaiting more evidence."/>:<div className={styles.readyList}>{[...ready.map((item)=>({title:item.title,reason:item.blockers[0]??"Capacity and dependency evaluation in progress",stage:item.stage,priority:item.priority})),...held.map((item)=>({title:item.title??"Candidate signal",reason:String(item.rationale?.reason??"Held by readiness or risk gate"),stage:"decision gate",priority:"policy hold"}))].slice(0,8).map((item,index)=><div className={styles.readyRow} key={`${item.title}-${index}`}><span className={styles.readyIcon}><TimerReset size={16}/></span><div><strong>{item.title}</strong><small>{pretty(item.stage)} · {item.reason}</small></div><span className={styles.defer}>{item.priority}</span></div>)}</div>}</article><article className={styles.panel}><div className={styles.panelHead}><div><h2>Execution history</h2><p>Measured outcomes from the latest completed cycle.</p></div><History size={18}/></div><div className={styles.historyGrid}>{[["Candidates scanned",status?.lastRun?.scanned??0],["Generated",status?.lastRun?.generated??0],["Advanced",status?.lastRun?.advanced??0],["Recovered / held",status?.lastRun?`${status.lastRun.held} / ${status.lastRun.duplicates}`:"—"]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><div className={styles.governance}><ShieldCheck size={17}/><span><strong>Governance enforced</strong><small>Dependencies, quality gates, retries, and audit writes are engine-owned. Human input required: 0.</small></span></div></article></section>
  </main>
}
function Kpi({icon,label,value,detail,tone}:{icon:React.ReactNode;label:string;value:string;detail:string;tone:string}){return <article className={styles.kpi}><span className={`${styles.kpiIcon} ${styles[tone]}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({title,detail}:{title:string;detail:string}){return <div className={styles.empty}><Database size={22}/><strong>{title}</strong><p>{detail}</p></div>}
