"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronDown, Download, Filter, MoreVertical, Network, Pause, RefreshCw, Search, ShieldCheck, Sparkles, Star, Target, TrendingUp, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { loadDiscovery, promoteSignal } from "@/lib/opportunity-intelligence-api";
import type { DiscoveryData, DiscoverySettings, OpportunitySignal } from "@/types/opportunity-intelligence";
import { PageTop } from "./OpportunityDashboard";
import styles from "./OpportunityIntelligence.module.css";

export function DiscoveryEngine(){
 const [data,setData]=useState<DiscoveryData|null>(null),[settings,setSettings]=useState<DiscoverySettings|null>(null),[query,setQuery]=useState(""),[tab,setTab]=useState("All Signals"),[selected,setSelected]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const refresh=useCallback(async(signal?:AbortSignal)=>{setBusy("refresh");try{const next=await loadDiscovery(signal);setData(next);setSettings(next.settings);setSelected(id=>id||next.signals[0]?.id||"");setMessage("");}catch(e){if((e as Error).name!=="AbortError")setMessage((e as Error).message);}finally{setBusy("");}},[]);
 useEffect(()=>{const c=new AbortController();void refresh(c.signal);const interval=window.setInterval(()=>void refresh(),30000);return()=>{c.abort();window.clearInterval(interval);};},[refresh]);
 const signals=useMemo(()=>data?.signals.filter(item=>item.subject.toLowerCase().includes(query.toLowerCase())&&(tab==="All Signals"||(tab==="Accelerating"&&item.velocity>80)||(tab==="New"&&item.state==="New")||(tab==="Anomalies"&&item.anomaly)||(tab==="Watchlist"&&item.watchlisted)))||[],[data,query,tab]);
 const active=data?.signals.find(item=>item.id===selected)||signals[0];
 async function promote(){if(!active)return;setBusy("promote");try{await promoteSignal(active.id);await refresh();setMessage("Autonomy layer confirmed the signal is available as a database-backed opportunity.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}}
 return <div className={styles.page}><PageTop current="Discovery Engine" title="Discovery Engine" subtitle="Autonomously scans market, audience, content, competitor, and partner signals to uncover emerging opportunities."/>
  <section className={styles.workspaceBar}><span className={styles.heroIcon}><Target/></span><div><b>Opportunity Discovery Engine</b><small>Last autonomous scan: {formatAgo(data?.settings.lastScanAt)} | <i/> Engine online | 18 sources connected</small></div><div className={styles.barActions}><button onClick={()=>refresh()}><RefreshCw/>Sync status</button><button><ShieldCheck/>Policy locked</button><button className={styles.primary} disabled><CheckCircle2/>Autonomous scan active</button></div></section>
  {message?<div className={styles.notice}>{message}</div>:null}
  <div className={styles.discoveryLayout}><main><div className={`${styles.metrics} ${styles.discoveryMetrics}`}>{([
   [data?.metrics.processed?.toLocaleString()??"-","Signals Processed","Autonomous ingestion",Target,"purple"],[data?.metrics.emerging??"-","Emerging Signals","Auto-classified",TrendingUp,"green"],[data?.metrics.clusters??"-","Opportunity Clusters","Continuously formed",Network,"blue"],[92,"Source Health","18 sources active",ShieldCheck,"teal"],[data?.metrics.alerts??"-","Alerts Triggered","Auto-escalated signals",AlertTriangle,"orange"]
  ] as Array<[string|number,string,string,LucideIcon,string]>).map(([value,label,detail,Icon,tone])=><article key={label} data-tone={tone}><span><Icon/></span><div><strong>{String(value)}</strong><b>{label}</b><small>{detail}</small></div></article>)}</div>
  <section className={styles.panel}><header className={styles.panelHead}><div><h2>Live Signal Stream</h2><p>AI-detected changes ranked by velocity, relevance, novelty, durability, and commercial potential.</p></div><button><Download/>Export</button><button><MoreVertical/></button></header>
   <nav className={styles.tabs}>{[["All Signals",data?.metrics.emerging],["Accelerating",62],["New",41],["Anomalies",18],["Watchlist",27]].map(([name,count])=><button className={tab===name?styles.active:""} onClick={()=>setTab(String(name))} key={String(name)}>{name}<b>{count}</b></button>)}</nav>
   <div className={styles.tools}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search signals, topics, markets, or entities..."/></label><button><Filter/>Filters <b>6</b></button><button>Sort: Signal Strength <ChevronDown/></button><span className={styles.live}><i/> Live <Pause/></span></div>
   <div className={styles.scoreStrip}><span><TrendingUp/> Velocity <b>+34%</b></span><span><Star/> Novelty <b>82%</b></span><span><Network/> Cross-source matches <b>1,248</b></span><span><Filter/> Noise filtered <b>91%</b></span></div>
   <SignalTable rows={signals} selected={active?.id} onSelect={setSelected}/><footer className={styles.pagination}>1-{signals.length} of {data?.metrics.emerging??0}<span>Auto-refresh every 30 seconds</span></footer>
  </section><div className={styles.bottomCards}>{[["5 critical anomalies","Autonomy layer escalates high-score signals","red",Zap],["11 new clusters","Formed without human triage","blue",Network],["27 watchlist signals","Near activation threshold","orange",Star]].map(([title,detail,tone,Icon])=><article key={String(title)} data-tone={tone}><span><Icon/></span><div><b>{String(title)}</b><small>{String(detail)}</small><button disabled>Monitored automatically</button></div></article>)}</div></main>
  <aside className={styles.discoveryRail}>{settings?<Controls value={settings}/>:null}<Sources/><Formation data={data}/><section className={styles.brief}><h3><Sparkles/> AI Discovery Brief <b>Breakout signal</b></h3><p>Demand for applied industrial AI training is accelerating across search, hiring, procurement, and professional communities. Cross-source agreement is unusually high.</p><span><b>+126% velocity</b><b>92% confidence</b><b>6 source types</b></span><div className={styles.splitButtons}><button className={styles.primary} disabled>Signal map monitored</button><button onClick={promote} disabled={!active||!!busy}>{busy==="promote"?"Confirming...":"Auto-promotion ready"}</button></div></section></aside></div>
 </div>;
}

function Controls({value}:{value:DiscoverySettings}){return <section className={styles.smallPanel}><h3>Autonomous Policy</h3><div className={styles.controls}><label>Scan horizon<b>{value.scanHorizonDays} days</b></label><label>Primary market<b>{value.primaryMarket}</b></label><label>Signal sensitivity<span><input type="range" min="1" max="100" value={value.signalSensitivity} readOnly/><b>{value.signalSensitivity}</b></span></label><label>Minimum confidence<b>{value.minimumConfidence}%</b></label>{[["Include weak signals",value.includeWeakSignals],["Detect anomalies",value.detectAnomalies],["Cross-check competitors",value.crossCheckCompetitors]] .map(([label,enabled])=><label className={styles.check} key={String(label)}><CheckCircle2 size={14}/>{label}<b>{enabled?"On":"Off"}</b></label>)}<button className={styles.primary} disabled><ShieldCheck size={14}/>Policy managed by autonomy layer</button></div></section>}
function Sources(){return <section className={styles.smallPanel}><h3>Signal Sources <span className={styles.greenText}>92% source health</span></h3><div className={styles.sources}>{["Google Trends","Jobs & Skills Data","Social Listening","Public Procurement","Industry Publications","Competitor Monitoring","Search Demand"].map((name,index)=><p key={name}><i>{name[0]}</i><span>{name}</span><b data-updating={index===3}>Live</b></p>)}</div></section>}
function Formation({data}:{data:DiscoveryData|null}){const processed=data?.metrics.processed||0,relevant=data?.signals.filter(x=>x.relevance>=70).length||0,priority=data?.signals.filter(x=>x.score>=90).length||0;const stages=[["Raw signals",processed,100],["Relevant signals",relevant,processed?Math.round(relevant/processed*100):0],["Emerging signals",data?.metrics.emerging||0,processed?Math.round((data?.metrics.emerging||0)/processed*100):0],["Opportunity clusters",data?.metrics.clusters||0,processed?Math.round((data?.metrics.clusters||0)/processed*100):0],["High-priority opportunities",priority,processed?Math.round(priority/processed*100):0]];return <section className={styles.smallPanel}><h3>Opportunity Formation</h3>{stages.map(([name,count,width])=><div className={styles.formation} key={String(name)}><span>{name}</span><b>{Number(count).toLocaleString()}</b><i><u style={{width:`${width}%`}}/></i></div>)}</section>}
function SignalTable({rows,selected,onSelect}:{rows:OpportunitySignal[];selected?:string;onSelect:(id:string)=>void}){return <div className={`${styles.table} ${styles.signalTable}`}><header><span>SIGNAL / SUBJECT</span><span>SOURCE MIX</span><span>VELOCITY</span><span>NOVELTY</span><span>DURABILITY</span><span>RELEVANCE</span><span>SIGNAL SCORE</span><span>STATE</span><span/></header>{rows.map(item=><button className={selected===item.id?styles.rowSelected:""} key={item.id} onClick={()=>onSelect(item.id)}><span><b>{item.subject}</b></span><span><small>{item.sourceMix}</small><b className={styles.sourceDots}>G | in | source +2</b></span><strong className={item.velocity<0?styles.redText:styles.greenText}>{item.velocity>0?"+":""}{item.velocity}%</strong><strong>{item.novelty}%</strong><span>{item.durability}</span><strong>{item.relevance}%</strong><span className={styles.score}><b>{item.score}/100</b><i><u style={{width:`${item.score}%`}}/></i></span><i data-status={item.state}>{item.state}</i><MoreVertical/></button>)}</div>}
function formatAgo(value?:string|null){if(!value)return"pending";const minutes=Math.max(1,Math.round((Date.now()-new Date(value).getTime())/60000));return minutes<60?`${minutes} minutes ago`:`${Math.round(minutes/60)} hours ago`;}
