"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Archive, BarChart3, Bell, BookOpen, BrainCircuit, CalendarDays, CheckCircle2,
  ChevronDown, CircleDollarSign, Clock3, Download, FileStack, Filter, Gauge, Grid2X2, History,
  KanbanSquare, Layers3, List, Megaphone, Plus, RefreshCw, Rocket, Save, Search, Settings2,
  ShieldCheck, Sparkles, Target, Trash2, Users, WandSparkles, X
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { OperationalMutation, OperationalPageData, OperationalRecord } from "@/types/opportunity-operations";
import styles from "./OperationalPage.module.css";
import portfolioStyles from "./PortfolioAutonomy.module.css";

type Definition = {title:string;subtitle:string;entity:string;createLabel:string;type:string;statuses:string[];metricLabels:[string,string,string,string];icon:LucideIcon};
const definitions: Record<string,Definition> = {
  "editorial-board": {title:"Autonomous Editorial Board",subtitle:"Continuously curates, verifies, scores, and approves production-ready stories without operator input.",entity:"pitch",createLabel:"Submit Pitch",type:"pitch",statuses:["Auto-curated","Autonomous evidence verification","Auto-approved for production","Auto-held by risk"],metricLabels:["Candidates Curated","Production Approved","Editorial Health","Decision Confidence"],icon:KanbanSquare},
  "opportunity-scheduler": {title:"Autonomous Opportunity Scheduler",subtitle:"Continuously chooses channel-aware publishing windows, balances capacity, and resolves timing conflicts without operator input.",entity:"scheduled opportunity",createLabel:"Schedule Opportunity",type:"schedule",statuses:["Auto-scheduled","Auto-rebalanced","Autonomous timing optimization","Auto-held by risk"],metricLabels:["Scheduled Opportunities","Upcoming This Week","Optimal Timing Score","Schedule Conflicts"],icon:CalendarDays},
  "autonomy-modes": {title:"Autonomy Modes",subtitle:"Control how independently AI agents discover, decide, create, schedule, and execute opportunities.",entity:"policy",createLabel:"Add Policy",type:"policy",statuses:["Active","Restricted","Approval Required","Disabled"],metricLabels:["Configured Policies","Autonomous Decisions","Human Approvals","Safety Interventions"],icon:ShieldCheck},
  "learning-engine": {title:"Learning Engine",subtitle:"Continuously improve opportunity decisions using outcomes, feedback, experiments, and real-world performance.",entity:"experiment",createLabel:"Create Experiment",type:"experiment",statuses:["Draft","Running","Significant","Inconclusive"],metricLabels:["Learning Signals","Active Experiments","Prediction Accuracy","Model Drift"],icon:BrainCircuit},
  "multi-format-planner": {title:"Autonomous Multi-Format Planner",subtitle:"Continuously adapts completed master productions into channel-native formats while preserving narrative and evidence consistency.",entity:"format asset",createLabel:"Add Format",type:"format",statuses:["Auto-optimized","Auto-ready","Autonomous adapting","Auto-held by risk"],metricLabels:["Master Productions","Format Variants","Channel Coverage","Reuse Efficiency"],icon:FileStack},
  "executive-recommendations": {title:"Autonomous Executive Recommendations",subtitle:"Continuously converts evidence-approved opportunities into risk-adjusted decisions, allocations, and execution without operator input.",entity:"recommendation",createLabel:"Add Recommendation",type:"recommendation",statuses:["Auto-executing","Auto-committed","Autonomous monitoring","Auto-deferred by risk"],metricLabels:["Strategic Recommendations","Auto-executing","Decision Confidence","Committed Investment"],icon:Target},
  "opportunity-portfolio": {title:"Autonomous Opportunity Portfolio",subtitle:"Continuously ingests, deduplicates, balances, ranks, and advances high-value opportunities without operator input.",entity:"opportunity",createLabel:"Add Opportunity",type:"opportunity",statuses:["Auto-promoted","Auto-prioritized","Autonomous enrichment","Auto-risk-managed"],metricLabels:["Portfolio Opportunities","Autonomously Ready","Portfolio Score","Projected Value"],icon:Layers3},
  "campaign-builder": {title:"Autonomous Campaign Builder",subtitle:"Continuously converts channel-ready assets into audience-optimized, sequenced, budgeted, and launch-routed campaigns without operator input.",entity:"campaign asset",createLabel:"Add Campaign Asset",type:"campaign",statuses:["Auto-launched","Auto-scheduled","Autonomous optimizing","Auto-held by risk"],metricLabels:["Autonomous Campaigns","Campaign Assets","Projected Reach","Launch Readiness"],icon:Megaphone},
  "evergreen-knowledge-bank": {title:"Autonomous Evergreen Knowledge Bank",subtitle:"Continuously certifies, refreshes, deduplicates, and routes trusted knowledge for reusable production without operator input.",entity:"knowledge asset",createLabel:"Add Knowledge",type:"knowledge",statuses:["Auto-certified Evergreen","Autonomous monitored","Autonomous refresh queued","Auto-held by risk"],metricLabels:["Evergreen Assets","Auto-certified","Knowledge Freshness","Reuse Readiness"],icon:BookOpen}
};

async function api(slug:string, init?:RequestInit) {
  const response=await fetch(`/api/opportunity-intelligence/operations/${slug}`,{cache:"no-store",headers:{"Content-Type":"application/json"},...init});
  const body=await response.json().catch(()=>null); if(!response.ok)throw new Error(body?.message||`Request failed (${response.status})`); return body as OperationalPageData;
}

export function OperationalPage({slug}:{slug:string}) {
  const def=definitions[slug]; const autonomousPage=slug==="opportunity-scheduler"||slug==="opportunity-portfolio"||slug==="editorial-board"||slug==="executive-recommendations"||slug==="multi-format-planner"||slug==="campaign-builder"||slug==="evergreen-knowledge-bank"; const autonomousPortfolio=slug==="opportunity-portfolio"; const autonomousEditorial=slug==="editorial-board"; const autonomousExecutive=slug==="executive-recommendations"; const autonomousPlanner=slug==="multi-format-planner"; const autonomousCampaign=slug==="campaign-builder"; const autonomousEvergreen=slug==="evergreen-knowledge-bank"; const [data,setData]=useState<OperationalPageData|null>(null); const [error,setError]=useState("");
  const [busy,setBusy]=useState(false); const [showForm,setShowForm]=useState(false); const [query,setQuery]=useState("");
  const refresh=useCallback(async()=>{try{setData(await api(slug));setError("");}catch(e){setError((e as Error).message);}},[slug]);
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer);},[refresh]);
  async function mutate(payload:OperationalMutation){setBusy(true);try{setData(await api(slug,{method:"POST",body:JSON.stringify(payload)}));setError("");setShowForm(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const rows=useMemo(()=>data?.records.filter(r=>`${r.title} ${r.description} ${r.category} ${r.owner} ${r.status}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
  if(!def)return null;
  return <main className={styles.page}>
    <Top title={def.title} subtitle={def.subtitle} autonomous={autonomousPage}/>
    <div className={styles.actions}><span className={styles.live}><i/> Live database <small>{data?`Updated ${new Date(data.generatedAt).toLocaleTimeString()}`:"Connecting…"}</small></span>
      {autonomousPage?<><span className={portfolioStyles.autonomousTag}><ShieldCheck/>Zero-input lifecycle</span><span className={portfolioStyles.autonomousTag}><Clock3/>Every {data?.autonomy?.intervalSeconds??30}s</span></>:<><button onClick={()=>void refresh()}><RefreshCw/>Refresh</button><button onClick={()=>exportRows(def.title,rows)} disabled={!rows.length}><Download/>Export</button><button className={styles.primary} onClick={()=>setShowForm(true)}><Plus/>{def.createLabel}</button></>}</div>
    {error?<div className={styles.error}><AlertTriangle/>{error}</div>:null}
    {showForm&&!autonomousPage?<CreateForm def={def} busy={busy} onClose={()=>setShowForm(false)} onSubmit={mutate}/>:null}
    {autonomousPortfolio?<PortfolioAutonomy data={data}/>:null}
    {autonomousEditorial?<EditorialAutonomy data={data}/>:null}
    {autonomousExecutive?<ExecutiveAutonomy data={data}/>:null}
    {autonomousPlanner?<FormatAutonomy data={data}/>:null}
    {autonomousCampaign?<CampaignAutonomy data={data}/>:null}
    {autonomousEvergreen?<EvergreenAutonomy data={data}/>:null}
    <Metrics def={def} data={data}/>
    {slug==="editorial-board"?<Editorial rows={rows} statuses={def.statuses}/>:null}
    {slug==="opportunity-scheduler"?<Scheduler rows={rows} mutate={mutate}/>:null}
    {slug==="autonomy-modes"?<Autonomy rows={rows} data={data} mutate={mutate}/>:null}
    {slug==="learning-engine"?<Learning rows={rows} mutate={mutate}/>:null}
    {slug==="multi-format-planner"?<Planner rows={rows}/>:null}
    {slug==="executive-recommendations"?<Recommendations rows={rows}/>:null}
    {slug==="opportunity-portfolio"?<Portfolio rows={rows}/>:null}
    {slug==="campaign-builder"?<Campaign rows={rows}/>:null}
    {slug==="evergreen-knowledge-bank"?<EvergreenKnowledge rows={rows}/>:null}
    <SearchBar query={query} setQuery={setQuery} count={rows.length}/>
  </main>;
}

function Top({title,subtitle,autonomous=false}:{title:string;subtitle:string;autonomous?:boolean}) {return <><div className={styles.top}><span>Opportunity Intelligence　/　<b>{title}</b></span><label><Search/><input placeholder="Search intelligence, topics, or signals…"/></label><Bell/><span className={styles.avatar}>AS</span></div><header className={styles.title}><div><h1>{title}</h1><p>{subtitle}</p></div>{autonomous?<><span className={portfolioStyles.autonomousTag}><BrainCircuit/>Engine-owned</span><span className={portfolioStyles.autonomousTag}><CheckCircle2/>No human validation</span></>:<><button><Settings2/>Page Settings</button><button><History/>Activity Log</button></>}</header></>}

function Metrics({def,data}:{def:Definition;data:OperationalPageData|null}) {const editorial=def.title==="Autonomous Editorial Board";const executive=def.title==="Autonomous Executive Recommendations";const planner=def.title==="Autonomous Multi-Format Planner";const campaign=def.title==="Autonomous Campaign Builder";const scheduler=def.title==="Autonomous Opportunity Scheduler";const evergreen=def.title==="Autonomous Evergreen Knowledge Bank";const last=data?.autonomy?.lastRun;const values=scheduler?[data?.totals.count??0,last?.upcoming??0,`${last?.timingScore??0}%`,last?.conflicts??0]:editorial?[data?.totals.count??0,last?.approved??0,`${last?.editorialHealth??0}%`,`${last?.averageConfidence??0}%`]:executive?[data?.totals.count??0,last?.executing??0,`${last?.averageConfidence??0}%`,money(last?.investmentCommitted??0)]:planner?[last?.masters??0,data?.totals.count??0,`${last?.channelCoverage??0}%`,`${last?.reuseEfficiency??0}%`]:campaign?[last?.campaigns??0,data?.totals.count??0,compact(last?.projectedReach??0),`${last?.launchReadiness??0}%`]:evergreen?[data?.totals.count??0,last?.certified??0,`${last?.freshness??0}%`,`${last?.reuseReadiness??0}%`]:[data?.totals.count??0,data?.totals.ready??0,data?.totals.averageScore?`${data.totals.averageScore}%`:"0%",data?.totals.totalAmount?money(data.totals.totalAmount):data?.totals.attention??0];const icons=[def.icon,CheckCircle2,Gauge,AlertTriangle];return <section className={styles.metrics}>{def.metricLabels.map((label,i)=>{const Icon=icons[i];return <article key={label} data-tone={i}><span><Icon/></span><div><small>{label}</small><strong>{values[i]}</strong><em>{data?"Live from database":"Loading live data"}</em></div></article>})}</section>}

function CreateForm({def,busy,onClose,onSubmit}:{def:Definition;busy:boolean;onClose:()=>void;onSubmit:(p:OperationalMutation)=>void}) {const [form,setForm]=useState({title:"",description:"",category:"",owner:"",status:def.statuses[0],score:"",amount:"",dueAt:""});return <section className={styles.form}><header><div><b>Create {def.entity}</b><small>This record will be saved directly to the production database.</small></div><button onClick={onClose}><X/></button></header><div><label>Title<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Owner<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{def.statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Score<input type="number" min="0" max="100" value={form.score} onChange={e=>setForm({...form,score:e.target.value})}/></label><label>Due date<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label className={styles.wide}>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button onClick={onClose}>Cancel</button><button className={styles.primary} disabled={busy||!form.title.trim()} onClick={()=>onSubmit({action:"create",type:def.type,title:form.title,description:form.description,category:form.category,owner:form.owner,status:form.status,score:form.score?Number(form.score):null,dueAt:form.dueAt?new Date(form.dueAt).toISOString():null})}><Save/>{busy?"Saving…":"Save to database"}</button></footer></section>}

function Empty({label}:{label:string}) {return <div className={styles.empty}><Archive/><h3>No {label} yet</h3><p>Create the first record to begin live operations. No demonstration data is displayed.</p></div>}
function change(mutate:(p:OperationalMutation)=>void,row:OperationalRecord,status:string){mutate({action:"update",id:row.id,status,progress:status.match(/ready|approved|verified|significant/i)?100:row.progress});}

function Editorial({rows,statuses}:{rows:OperationalRecord[];statuses:string[]}) {return <section className={styles.panel}><Head title="Autonomous Editorial Workflow" subtitle="Machine-curated pitch pipeline and evidence-governed production decisions"/><div className={styles.kanban}>{statuses.map(status=><div className={styles.column} key={status}><header><b>{status}</b><span>{rows.filter(x=>x.status===status).length}</span></header>{rows.filter(x=>x.status===status).map(row=><article className={styles.card} key={row.id}><b>{row.title}</b><small>{row.category||"Uncategorized"}</small><p>{row.description||"Autonomously curated intelligence candidate."}</p><div><span>{row.owner}</span><strong>{row.score??"—"}</strong></div><small>Evidence {Number(row.metadata.evidenceScore??0).toFixed(1)}% · Decision {Number(row.metadata.decisionConfidence??0).toFixed(1)}%</small></article>)}</div>)}</div>{!rows.length?<Empty label="autonomously curated editorial candidates"/>:null}</section>}

function Scheduler({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {const days=Array.from({length:35},(_,i)=>i+1);return <div className={styles.two}><section className={styles.panel}><Head title="Opportunity Calendar" subtitle="Current month · production and publishing plan"/><div className={styles.calendar}>{days.map(day=><div key={day}><b>{day}</b>{rows.filter(x=>x.dueAt&&new Date(x.dueAt).getDate()===day).map(x=><button key={x.id} disabled>{x.title}</button>)}</div>)}</div>{!rows.length?<Empty label="scheduled opportunities"/>:null}</section><aside className={styles.rail}><Head title="Capacity & Cadence" subtitle="Calculated from scheduled work"/><GaugeRows rows={rows}/><Head title="Schedule Conflicts" subtitle="Records requiring attention"/>{rows.filter(x=>/conflict/i.test(x.status)).map(x=><CardRow key={x.id} row={x} mutate={mutate} next="Scheduled"/>)}</aside></div>}

function Autonomy({rows,data,mutate}:{rows:OperationalRecord[];data:OperationalPageData|null;mutate:(p:OperationalMutation)=>void}) {const current=String(data?.settings.currentMode||"Supervised Autonomy");const modes=[["Manual Control",10],["Assisted Intelligence",40],["Supervised Autonomy",75],["Full Autonomy",95]] as const;const safeguards=["Confidence Threshold","High-impact Approval","Budget Guardrail","Emergency Halt Guard"];return <div className={styles.two}><section className={styles.panel}><Head title="Select Autonomy Mode" subtitle="Authority changes are stored as governed configuration"/><div className={styles.modes}>{modes.map(([name,value])=><button className={current===name?styles.modeActive:""} key={name} onClick={()=>mutate({action:"setting",key:"currentMode",value:name})}><span>{current===name?<CheckCircle2/>:<ShieldCheck/>}</span><div><b>{name}</b><small>{name==="Manual Control"?"Humans approve every action.":name==="Full Autonomy"?"End-to-end execution within safeguards.":"AI prepares and executes within approval policy."}</small></div><strong>{value}%<i><u style={{width:`${value}%`}}/></i></strong></button>)}</div><Head title="Authority & Approval Matrix" subtitle="Live capability policies"/>{rows.length?<DataTable rows={rows} mutate={mutate}/>:<Empty label="autonomy policies"/>}</section><aside className={styles.rail}><Head title="Safety & Governance" subtitle="Production safeguards"/>{safeguards.map(x=>{const key=`safeguard:${x}`;const enabled=data?.settings[key]!==false;return <div className={styles.toggle} key={x}><span>{x}</span><button style={{background:enabled?"#0eaa58":"#aeb7c7"}} aria-pressed={enabled} aria-label={x} onClick={()=>mutate({action:"setting",key,value:!enabled})}/></div>})}<div className={styles.insight}><Sparkles/><b>Current production mode</b><h3>{current}</h3><p>Mode changes are persisted and visible to all connected sessions.</p></div></aside></div>}

function Learning({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <div className={styles.two}><section className={styles.panel}><Head title="Learning Performance" subtitle="Measured experiment scores and outcome improvement"/><div className={styles.chart}>{rows.slice(0,12).map((x,i)=><div key={x.id}><i style={{height:`${Math.max(8,x.score||0)}%`}}/><span>{i+1}</span></div>)}{!rows.length?<p>No measured experiment points yet.</p>:null}</div><div className={styles.loop}>{["Observe","Compare","Diagnose","Experiment","Validate","Deploy"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><Head title="Experiments & Learning Actions" subtitle="Live experiment registry"/>{rows.length?<DataTable rows={rows} mutate={mutate}/>:<Empty label="learning experiments"/>}</section><aside className={styles.rail}><Head title="Model Health" subtitle="Based on recorded experiments"/><GaugeRows rows={rows}/><div className={styles.insight}><BrainCircuit/><b>Learning pipeline</b><h3>{rows.filter(x=>x.status==="Running").length} active experiments</h3><p>Results appear only after measured records are written.</p></div></aside></div>}

function Planner({rows}:{rows:OperationalRecord[]}) {return <div className={styles.two}><section className={styles.panel}><Head title="Autonomous Master-to-Format Blueprint" subtitle="Channel selection, narrative preservation, audience fit, and routing are machine-owned"/>{rows.length?<div className={styles.formatMap}><div className={styles.master}><BrainCircuit/><b>Master<br/>Production</b></div>{rows.slice(0,6).map((x,i)=><article key={x.id} style={{gridArea:`a${i+1}`}}><b>{String(x.metadata.selectedFormat??x.title)}</b><small>{String(x.metadata.targetChannel??x.category)}</small><span>{x.status}</span></article>)}</div>:<Empty label="autonomous format plans"/>}<Head title="Autonomous Format Production Plan" subtitle="Continuously optimized, database-backed channel variants"/>{rows.length?<DataTable rows={rows} readOnly/>:null}</section><aside className={styles.rail}><Head title="Autonomous Format Mix" subtitle="Machine-routed variants by lifecycle"/><Donut rows={rows}/><Head title="Adaptation Quality" subtitle="Narrative and channel fitness scores"/><GaugeRows rows={rows}/></aside></div>}

function Recommendations({rows}:{rows:OperationalRecord[]}) {return <div className={styles.two}><section className={styles.panel}><Head title="Autonomous Strategic Decisions" subtitle="Risk-adjusted by expected utility, evidence, value, diversification, and execution readiness"/><div className={styles.recommendations}>{rows.map((x,i)=><article key={x.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{x.title}</h3><p>{x.description||"Autonomously generated from evidence-approved intelligence."}</p><small>Utility: {x.score??0}% · Risk: {Number(x.metadata.riskScore??0).toFixed(1)}% · Confidence: {Number(x.metadata.decisionConfidence??0).toFixed(1)}% · Allocation: {money(x.amount??0)}</small></div><strong>{x.status}</strong></article>)}</div>{!rows.length?<Empty label="autonomously generated executive recommendations"/>:null}</section><aside className={styles.rail}><Head title="Autonomous Decision Distribution" subtitle="Machine-owned execution states"/><Donut rows={rows}/><div className={styles.insight}><Sparkles/><b>Executive autonomy</b><h3>{rows.filter(x=>x.status==="Auto-executing").length} recommendations executing</h3><p>Every recommendation is evidence-backed, risk-adjusted, allocated, and routed without human approval.</p></div></aside></div>}

function Portfolio({rows}:{rows:OperationalRecord[]}) {return <><div className={styles.two}><section className={styles.panel}><Head title="Autonomous Portfolio Balance" subtitle="Machine-balanced opportunity distribution by strategic theme and lifecycle state"/><div className={styles.balance}>{group(rows,"category").map(([name,items])=><div key={name}><span>{name}<small>{items.length} opportunities</small></span><i><u style={{width:`${Math.max(3,Math.round(items.length/Math.max(1,rows.length)*100))}%`}}/></i></div>)}</div>{!rows.length?<Empty label="autonomously discovered portfolio opportunities"/>:null}</section><aside className={styles.rail}><Head title="Autonomous Lifecycle Distribution" subtitle="Machine-owned opportunity states"/><Donut rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Autonomously Governed Opportunities" subtitle="Continuously ranked, balanced, and routed by the portfolio engine"/><DataTable rows={rows} readOnly/></section>:null}</>}

function PortfolioAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>PORTFOLIO AUTONOMY ENGINE</small><h2>Adaptive portfolio orchestration is active</h2><p>Continuous ingestion, semantic deduplication, concentration-aware scoring, risk management, and lifecycle routing require no operator action.</p></div><aside><span><b>{last?.scanned??0}</b>Candidates</span><span><b>{last?.ingested??0}</b>Ingested</span><span><b>{last?.promoted??0}</b>Promoted</span><span><b>{last?.duplicates??0}</b>Duplicates suppressed</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"adaptive-portfolio-orchestrator-v4"}</small></em></section>}

function EditorialAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>EDITORIAL AUTONOMY ENGINE</small><h2>Evidence-governed editorial orchestration is active</h2><p>Opportunity ingestion, semantic deduplication, evidence fusion, risk gating, editorial scoring, and production approval run without operator action.</p></div><aside><span><b>{last?.scanned??0}</b>Scanned</span><span><b>{last?.ingested??0}</b>Curated</span><span><b>{last?.verified??0}</b>Verified</span><span><b>{last?.approved??0}</b>Approved</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"evidence-editorial-orchestrator-v5"}</small></em></section>}

function ExecutiveAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>EXECUTIVE AUTONOMY ENGINE</small><h2>Risk-adjusted executive orchestration is active</h2><p>Evidence intake, semantic deduplication, expected-utility ranking, portfolio diversification, investment allocation, and execution routing require no operator action.</p></div><aside><span><b>{last?.scanned??0}</b>Scanned</span><span><b>{last?.ingested??0}</b>Generated</span><span><b>{last?.committed??0}</b>Committed</span><span><b>{last?.executing??0}</b>Executing</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"risk-adjusted-executive-orchestrator-v5"}</small></em></section>}

function FormatAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>MULTI-FORMAT AUTONOMY ENGINE</small><h2>Narrative-consistent channel adaptation is active</h2><p>Completed productions are detected, decomposed, adapted, quality-scored, risk-gated, optimized, and routed to channel-native formats without human input.</p></div><aside><span><b>{last?.masters??0}</b>Masters</span><span><b>{data?.totals.count??0}</b>Variants</span><span><b>{last?.optimized??0}</b>Optimized</span><span><b>{last?.adaptationQuality??0}%</b>Quality</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"narrative-consistency-adaptation-orchestrator-v5"}</small></em></section>}

function CampaignAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>CAMPAIGN AUTONOMY ENGINE</small><h2>Multi-objective campaign orchestration is active</h2><p>Format intake, campaign grouping, audience inference, channel synergy, wave sequencing, reach forecasting, budget allocation, risk gating, and launch routing require no operator action.</p></div><aside><span><b>{last?.campaigns??0}</b>Campaigns</span><span><b>{last?.scanned??0}</b>Assets</span><span><b>{last?.launched??0}</b>Launched</span><span><b>{last?.launchReadiness??0}%</b>Readiness</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"multi-objective-campaign-orchestrator-v6"}</small></em></section>}

function EvergreenAutonomy({data}:{data:OperationalPageData|null}){const autonomy=data?.autonomy,last=autonomy?.lastRun;return <section className={portfolioStyles.autonomyPanel}><BrainCircuit/><div><small>EVERGREEN KNOWLEDGE AUTONOMY ENGINE</small><h2>Trusted retention and reuse orchestration is active</h2><p>Verified knowledge is continuously scored for freshness, trust, duplication, evergreen value, reuse readiness, refresh need, and production safety without human input.</p></div><aside><span><b>{last?.scanned??0}</b>Scanned</span><span><b>{last?.certified??0}</b>Certified</span><span><b>{last?.refreshQueued??0}</b>Refresh queued</span><span><b>{last?.freshness??0}%</b>Freshness</span><span><b>{last?.reuseReadiness??0}%</b>Reuse readiness</span></aside><em><i/>{autonomy?.state??"connecting"}<small>{autonomy?.algorithmVersion??"evergreen-retention-reuse-orchestrator-v5"}</small></em></section>}

function Campaign({rows}:{rows:OperationalRecord[]}) {const first=rows[0];return <><section className={styles.steps}>{["Strategy","Audience","Content Plan","Channels","Schedule & Budget","Review & Launch"].map(x=><span key={x}><b><CheckCircle2/></b>{x}</span>)}</section><div className={styles.two}><section className={styles.panel}><Head title="Autonomous Campaign Blueprint" subtitle="Machine-selected objective, audience, sequencing, channel mix, budget, and launch route"/>{first?<div className={styles.blueprint}><div><b>Campaign objective</b><p>{String(first.metadata.objective??first.description)}</p></div><div><b>Priority audience</b><p>{String(first.metadata.audience??"Autonomously inferred audience")}</p></div><div className={styles.wide}><b>Autonomous campaign waves</b><div className={styles.waves}>{["Tease","Educate","Deep Dive","Deepen","Sustain"].map(x=><span key={x}>{x}</span>)}</div></div></div>:<Empty label="autonomous campaign assets"/>}</section><aside className={styles.rail}><Head title="Autonomous Channel Mix" subtitle="Machine-optimized campaign distribution"/><Donut rows={rows}/><Head title="Launch Readiness" subtitle="Risk-adjusted asset readiness"/><GaugeRows rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Autonomous Campaign Content Plan" subtitle="Continuously sequenced, budgeted, and launch-routed assets"/><DataTable rows={rows} readOnly/></section>:null}</>}

function EvergreenKnowledge({rows}:{rows:OperationalRecord[]}){const certified=rows.filter(x=>x.status==="Auto-certified Evergreen").length;return <div className={styles.two}><section className={styles.panel}><Head title="Autonomous Knowledge Health & Freshness" subtitle="Machine-certified evergreen coverage, refresh routing, and reuse readiness"/><div className={styles.balance}>{group(rows,"category").map(([name,items])=><div key={name}><span>{name||"Uncategorized"}<small>{items.length} assets</small></span><i className={styles.green}><u style={{width:`${Math.round(items.reduce((n,x)=>n+Number(x.metadata.freshness??x.score??0),0)/Math.max(1,items.length))}%`}}/></i></div>)}</div>{!rows.length?<Empty label="autonomous evergreen assets"/>:null}</section><aside className={styles.rail}><Head title="Evergreen Lifecycle" subtitle="Machine-owned knowledge states"/><Donut rows={rows}/><div className={styles.insight}><BrainCircuit/><b>Reuse pipeline</b><h3>{certified} assets certified for reuse</h3><p>Freshness decay, source trust, quality, duplicate risk, and production relevance are evaluated continuously.</p></div></aside>{rows.length?<section className={styles.panel}><Head title="Autonomous Evergreen Library" subtitle="Trusted knowledge assets continuously governed for production reuse"/><DataTable rows={rows} readOnly/></section>:null}</div>}

function Knowledge({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <><div className={styles.two}><section className={styles.panel}><Head title="Knowledge Health & Freshness" subtitle="Coverage quality and update status across knowledge domains"/><div className={styles.balance}>{group(rows,"category").map(([name,items])=>{const good=items.filter(x=>x.status==="Verified").length/items.length*100;return <div key={name}><span>{name||"Uncategorized"}<small>{items.length} assets</small></span><i className={styles.green}><u style={{width:`${good}%`}}/></i></div>})}</div>{!rows.length?<Empty label="knowledge assets"/>:null}</section><aside className={styles.rail}><Head title="Knowledge Composition" subtitle="Library assets by type"/><Donut rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Knowledge Library" subtitle="Trusted reusable intelligence records"/><DataTable rows={rows} mutate={mutate}/></section>:null}</>}

function Head({title,subtitle}:{title:string;subtitle:string}){return <header className={styles.head}><div><h2>{title}</h2><p>{subtitle}</p></div><button><Filter/></button></header>}
function SearchBar({query,setQuery,count}:{query:string;setQuery:(v:string)=>void;count:number}){return <div className={styles.searchbar}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this live page…"/></label><span>{count} database record{count===1?"":"s"}</span></div>}
function DataTable({rows,mutate,readOnly=false}:{rows:OperationalRecord[];mutate?:(p:OperationalMutation)=>void;readOnly?:boolean}){return <div className={styles.table}><header><span>Title</span><span>Category</span><span>Owner</span><span>Score</span><span>Progress</span><span>Status</span><span>Updated</span><span/></header>{rows.map(x=><div key={x.id}><b>{x.title}<small>{x.description}</small></b><span>{x.category||"—"}</span><span>{x.owner}</span><strong>{x.score??"—"}</strong><span><i><u style={{width:`${x.progress||0}%`}}/></i>{x.progress??0}%</span><em>{x.status}</em><span>{new Date(x.updatedAt).toLocaleDateString()}</span>{readOnly?<CheckCircle2/>:<button onClick={()=>mutate?.({action:"delete",id:x.id})} aria-label="Delete"><Trash2/></button>}</div>)}</div>}
function CardRow({row,mutate,next}:{row:OperationalRecord;mutate:(p:OperationalMutation)=>void;next:string}){return <article className={styles.card}><b>{row.title}</b><p>{row.description}</p><button onClick={()=>change(mutate,row,next)}>Resolve</button></article>}
function GaugeRows({rows}:{rows:OperationalRecord[]}){const values=rows.slice(0,5);return <div className={styles.gauges}>{values.map(x=><div key={x.id}><span>{x.title}</span><i><u style={{width:`${x.progress??x.score??0}%`}}/></i><b>{x.progress??x.score??0}%</b></div>)}{!values.length?<p>No capacity measurements recorded.</p>:null}</div>}
function Donut({rows}:{rows:OperationalRecord[]}){const groups=group(rows,"status");let offset=0;const colors=["#6435ed","#0ca5d9","#f59b0b","#10a15a","#ef3e70","#6b768c"];const gradient=groups.map(([,items],i)=>{const start=offset;offset+=items.length/Math.max(1,rows.length)*100;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(",");return <div className={styles.donutWrap}><div className={styles.donut} style={{background:`conic-gradient(${gradient||"#e9edf5 0 100%"})`}}><i><b>{rows.length}</b><span>Total</span></i></div><div>{groups.map(([name,items],i)=><p key={name}><i style={{background:colors[i%colors.length]}}/><span>{name}</span><b>{items.length}</b></p>)}</div></div>}
function group(rows:OperationalRecord[],key:"category"|"status"){const map=new Map<string,OperationalRecord[]>();rows.forEach(x=>{const value=x[key]||"Uncategorized";map.set(value,[...(map.get(value)||[]),x]);});return [...map.entries()]}
function money(value:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",notation:"compact",maximumFractionDigits:1}).format(value)}
function compact(value:number){return new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(value)}
function exportRows(title:string,rows:OperationalRecord[]){const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const csv=[["Title","Description","Category","Status","Owner","Score","Progress","Amount","Start","Due","Updated"],...rows.map(x=>[x.title,x.description,x.category,x.status,x.owner,x.score,x.progress,x.amount,x.startAt,x.dueAt,x.updatedAt])].map(row=>row.map(cell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${title.toLowerCase().replaceAll(/[^a-z0-9]+/g,"-")}.csv`;link.click();URL.revokeObjectURL(url)}
