"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Archive, BarChart3, Bell, BookOpen, BrainCircuit, CalendarDays, CheckCircle2,
  ChevronDown, CircleDollarSign, Clock3, Download, FileStack, Filter, Gauge, Grid2X2, History,
  KanbanSquare, Layers3, List, Megaphone, Plus, RefreshCw, Rocket, Save, Search, Settings2,
  ShieldCheck, Sparkles, Target, Trash2, Users, WandSparkles, X
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { OperationalMutation, OperationalPageData, OperationalRecord } from "@/types/opportunity-operations";
import styles from "./OperationalPage.module.css";

type Definition = {title:string;subtitle:string;entity:string;createLabel:string;type:string;statuses:string[];metricLabels:[string,string,string,string];icon:LucideIcon};
const definitions: Record<string,Definition> = {
  "editorial-board": {title:"Editorial Board",subtitle:"Review, govern, and advance high-value stories through a transparent editorial decision process.",entity:"pitch",createLabel:"Submit Pitch",type:"pitch",statuses:["New Pitch","Under Review","Fact Check & Validation","Approved for Production"],metricLabels:["Active Pitches","Awaiting Decision","Approved This Month","Editorial Health"],icon:KanbanSquare},
  "opportunity-scheduler": {title:"Opportunity Scheduler",subtitle:"Schedule opportunities at the right moment using intelligence signals, production capacity, and channel cadence.",entity:"scheduled opportunity",createLabel:"Schedule Opportunity",type:"schedule",statuses:["Scheduled","Ready","In Production","Conflict"],metricLabels:["Scheduled Opportunities","Upcoming This Week","Optimal Timing Score","Schedule Conflicts"],icon:CalendarDays},
  "autonomy-modes": {title:"Autonomy Modes",subtitle:"Control how independently AI agents discover, decide, create, schedule, and execute opportunities.",entity:"policy",createLabel:"Add Policy",type:"policy",statuses:["Active","Restricted","Approval Required","Disabled"],metricLabels:["Configured Policies","Autonomous Decisions","Human Approvals","Safety Interventions"],icon:ShieldCheck},
  "learning-engine": {title:"Learning Engine",subtitle:"Continuously improve opportunity decisions using outcomes, feedback, experiments, and real-world performance.",entity:"experiment",createLabel:"Create Experiment",type:"experiment",statuses:["Draft","Running","Significant","Inconclusive"],metricLabels:["Learning Signals","Active Experiments","Prediction Accuracy","Model Drift"],icon:BrainCircuit},
  "multi-format-planner": {title:"Multi-Format Planner",subtitle:"Transform one core story into coordinated, platform-ready formats without losing narrative consistency.",entity:"format asset",createLabel:"Add Format",type:"format",statuses:["Planned","Draft","In Production","Ready"],metricLabels:["Master Stories","Format Variants","Channel Coverage","Reuse Efficiency"],icon:FileStack},
  "executive-recommendations": {title:"Executive Recommendations",subtitle:"Translate opportunity intelligence into prioritized actions, investment choices, and measurable strategic outcomes.",entity:"recommendation",createLabel:"Add Recommendation",type:"recommendation",statuses:["Decision Required","Review","Approved","Deferred"],metricLabels:["Priority Recommendations","Ready for Decision","Executive Confidence","Committed Investment"],icon:Target},
  "opportunity-portfolio": {title:"Opportunity Portfolio",subtitle:"Organize, balance, and advance high-value content opportunities from discovery to production.",entity:"opportunity",createLabel:"Add Opportunity",type:"opportunity",statuses:["Backlog","Validating","Planned","In Production","Ready to Publish"],metricLabels:["Portfolio Opportunities","Production Ready","Portfolio Score","Projected Value"],icon:Layers3},
  "campaign-builder": {title:"Campaign Builder",subtitle:"Turn high-value opportunities into coordinated, audience-ready, multi-channel content campaigns.",entity:"campaign asset",createLabel:"Add Campaign Asset",type:"campaign",statuses:["Draft","Planned","In Production","Ready"],metricLabels:["Campaign Assets","Production Ready","Projected Reach","Launch Readiness"],icon:Megaphone},
  "evergreen-knowledge-bank": {title:"Evergreen Knowledge Bank",subtitle:"Build a trusted, reusable intelligence library that stays accurate, relevant, and production-ready.",entity:"knowledge asset",createLabel:"Add Knowledge",type:"knowledge",statuses:["Unverified","Review","Verified","Update Required"],metricLabels:["Knowledge Assets","Verified Evergreen","Knowledge Freshness","Content Reuse"],icon:BookOpen}
};

async function api(slug:string, init?:RequestInit) {
  const response=await fetch(`/api/opportunity-intelligence/operations/${slug}`,{cache:"no-store",headers:{"Content-Type":"application/json"},...init});
  const body=await response.json().catch(()=>null); if(!response.ok)throw new Error(body?.message||`Request failed (${response.status})`); return body as OperationalPageData;
}

export function OperationalPage({slug}:{slug:string}) {
  const def=definitions[slug]; const [data,setData]=useState<OperationalPageData|null>(null); const [error,setError]=useState("");
  const [busy,setBusy]=useState(false); const [showForm,setShowForm]=useState(false); const [query,setQuery]=useState("");
  const refresh=useCallback(async()=>{try{setData(await api(slug));setError("");}catch(e){setError((e as Error).message);}},[slug]);
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer);},[refresh]);
  async function mutate(payload:OperationalMutation){setBusy(true);try{setData(await api(slug,{method:"POST",body:JSON.stringify(payload)}));setError("");setShowForm(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const rows=useMemo(()=>data?.records.filter(r=>`${r.title} ${r.description} ${r.category} ${r.owner} ${r.status}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
  if(!def)return null;
  return <main className={styles.page}>
    <Top title={def.title} subtitle={def.subtitle}/>
    <div className={styles.actions}><span className={styles.live}><i/> Live database <small>{data?`Updated ${new Date(data.generatedAt).toLocaleTimeString()}`:"Connecting…"}</small></span>
      <button onClick={()=>void refresh()}><RefreshCw/>Refresh</button><button onClick={()=>exportRows(def.title,rows)} disabled={!rows.length}><Download/>Export</button><button className={styles.primary} onClick={()=>setShowForm(true)}><Plus/>{def.createLabel}</button></div>
    {error?<div className={styles.error}><AlertTriangle/>{error}</div>:null}
    {showForm?<CreateForm def={def} busy={busy} onClose={()=>setShowForm(false)} onSubmit={mutate}/>:null}
    <Metrics def={def} data={data}/>
    {slug==="editorial-board"?<Editorial rows={rows} statuses={def.statuses} mutate={mutate}/>:null}
    {slug==="opportunity-scheduler"?<Scheduler rows={rows} mutate={mutate}/>:null}
    {slug==="autonomy-modes"?<Autonomy rows={rows} data={data} mutate={mutate}/>:null}
    {slug==="learning-engine"?<Learning rows={rows} mutate={mutate}/>:null}
    {slug==="multi-format-planner"?<Planner rows={rows} mutate={mutate}/>:null}
    {slug==="executive-recommendations"?<Recommendations rows={rows} mutate={mutate}/>:null}
    {slug==="opportunity-portfolio"?<Portfolio rows={rows} mutate={mutate}/>:null}
    {slug==="campaign-builder"?<Campaign rows={rows} mutate={mutate}/>:null}
    {slug==="evergreen-knowledge-bank"?<Knowledge rows={rows} mutate={mutate}/>:null}
    <SearchBar query={query} setQuery={setQuery} count={rows.length}/>
  </main>;
}

function Top({title,subtitle}:{title:string;subtitle:string}) {return <><div className={styles.top}><span>Opportunity Intelligence　/　<b>{title}</b></span><label><Search/><input placeholder="Search intelligence, topics, or signals…"/></label><Bell/><span className={styles.avatar}>AS</span></div><header className={styles.title}><div><h1>{title}</h1><p>{subtitle}</p></div><button><Settings2/>Page Settings</button><button><History/>Activity Log</button></header></>}

function Metrics({def,data}:{def:Definition;data:OperationalPageData|null}) {const values=[data?.totals.count??0,data?.totals.ready??0,data?.totals.averageScore?`${data.totals.averageScore}%`:"0%",data?.totals.totalAmount?money(data.totals.totalAmount):data?.totals.attention??0];const icons=[def.icon,CheckCircle2,Gauge,AlertTriangle];return <section className={styles.metrics}>{def.metricLabels.map((label,i)=>{const Icon=icons[i];return <article key={label} data-tone={i}><span><Icon/></span><div><small>{label}</small><strong>{values[i]}</strong><em>{data?"Live from database":"Loading live data"}</em></div></article>})}</section>}

function CreateForm({def,busy,onClose,onSubmit}:{def:Definition;busy:boolean;onClose:()=>void;onSubmit:(p:OperationalMutation)=>void}) {const [form,setForm]=useState({title:"",description:"",category:"",owner:"",status:def.statuses[0],score:"",amount:"",dueAt:""});return <section className={styles.form}><header><div><b>Create {def.entity}</b><small>This record will be saved directly to the production database.</small></div><button onClick={onClose}><X/></button></header><div><label>Title<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Owner<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{def.statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Score<input type="number" min="0" max="100" value={form.score} onChange={e=>setForm({...form,score:e.target.value})}/></label><label>Due date<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label className={styles.wide}>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button onClick={onClose}>Cancel</button><button className={styles.primary} disabled={busy||!form.title.trim()} onClick={()=>onSubmit({action:"create",type:def.type,title:form.title,description:form.description,category:form.category,owner:form.owner,status:form.status,score:form.score?Number(form.score):null,dueAt:form.dueAt?new Date(form.dueAt).toISOString():null})}><Save/>{busy?"Saving…":"Save to database"}</button></footer></section>}

function Empty({label}:{label:string}) {return <div className={styles.empty}><Archive/><h3>No {label} yet</h3><p>Create the first record to begin live operations. No demonstration data is displayed.</p></div>}
function change(mutate:(p:OperationalMutation)=>void,row:OperationalRecord,status:string){mutate({action:"update",id:row.id,status,progress:status.match(/ready|approved|verified|significant/i)?100:row.progress});}

function Editorial({rows,statuses,mutate}:{rows:OperationalRecord[];statuses:string[];mutate:(p:OperationalMutation)=>void}) {return <section className={styles.panel}><Head title="Editorial Workflow" subtitle="Live pitch pipeline and decision governance"/><div className={styles.kanban}>{statuses.map(status=><div className={styles.column} key={status}><header><b>{status}</b><span>{rows.filter(x=>x.status===status).length}</span></header>{rows.filter(x=>x.status===status).map(row=><article className={styles.card} key={row.id}><b>{row.title}</b><small>{row.category||"Uncategorized"}</small><p>{row.description||"No description supplied."}</p><div><span>{row.owner}</span><strong>{row.score??"—"}</strong></div><button onClick={()=>change(mutate,row,statuses[Math.min(statuses.indexOf(status)+1,statuses.length-1)])}>Advance decision</button></article>)}</div>)}</div>{!rows.length?<Empty label="editorial pitches"/>:null}</section>}

function Scheduler({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {const days=Array.from({length:35},(_,i)=>i+1);return <div className={styles.two}><section className={styles.panel}><Head title="Opportunity Calendar" subtitle="Current month · production and publishing plan"/><div className={styles.calendar}>{days.map(day=><div key={day}><b>{day}</b>{rows.filter(x=>x.dueAt&&new Date(x.dueAt).getDate()===day).map(x=><button key={x.id} onClick={()=>change(mutate,x,"Ready")}>{x.title}</button>)}</div>)}</div>{!rows.length?<Empty label="scheduled opportunities"/>:null}</section><aside className={styles.rail}><Head title="Capacity & Cadence" subtitle="Calculated from scheduled work"/><GaugeRows rows={rows}/><Head title="Schedule Conflicts" subtitle="Records requiring attention"/>{rows.filter(x=>/conflict/i.test(x.status)).map(x=><CardRow key={x.id} row={x} mutate={mutate} next="Scheduled"/>)}</aside></div>}

function Autonomy({rows,data,mutate}:{rows:OperationalRecord[];data:OperationalPageData|null;mutate:(p:OperationalMutation)=>void}) {const current=String(data?.settings.currentMode||"Supervised Autonomy");const modes=[["Manual Control",10],["Assisted Intelligence",40],["Supervised Autonomy",75],["Full Autonomy",95]] as const;const safeguards=["Confidence Threshold","High-impact Approval","Budget Guardrail","Emergency Stop"];return <div className={styles.two}><section className={styles.panel}><Head title="Select Autonomy Mode" subtitle="Authority changes are stored as governed configuration"/><div className={styles.modes}>{modes.map(([name,value])=><button className={current===name?styles.modeActive:""} key={name} onClick={()=>mutate({action:"setting",key:"currentMode",value:name})}><span>{current===name?<CheckCircle2/>:<ShieldCheck/>}</span><div><b>{name}</b><small>{name==="Manual Control"?"Humans approve every action.":name==="Full Autonomy"?"End-to-end execution within safeguards.":"AI prepares and executes within approval policy."}</small></div><strong>{value}%<i><u style={{width:`${value}%`}}/></i></strong></button>)}</div><Head title="Authority & Approval Matrix" subtitle="Live capability policies"/>{rows.length?<DataTable rows={rows} mutate={mutate}/>:<Empty label="autonomy policies"/>}</section><aside className={styles.rail}><Head title="Safety & Governance" subtitle="Production safeguards"/>{safeguards.map(x=>{const key=`safeguard:${x}`;const enabled=data?.settings[key]!==false;return <div className={styles.toggle} key={x}><span>{x}</span><button style={{background:enabled?"#0eaa58":"#aeb7c7"}} aria-pressed={enabled} aria-label={x} onClick={()=>mutate({action:"setting",key,value:!enabled})}/></div>})}<div className={styles.insight}><Sparkles/><b>Current production mode</b><h3>{current}</h3><p>Mode changes are persisted and visible to all connected sessions.</p></div></aside></div>}

function Learning({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <div className={styles.two}><section className={styles.panel}><Head title="Learning Performance" subtitle="Measured experiment scores and outcome improvement"/><div className={styles.chart}>{rows.slice(0,12).map((x,i)=><div key={x.id}><i style={{height:`${Math.max(8,x.score||0)}%`}}/><span>{i+1}</span></div>)}{!rows.length?<p>No measured experiment points yet.</p>:null}</div><div className={styles.loop}>{["Observe","Compare","Diagnose","Experiment","Validate","Deploy"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><Head title="Experiments & Learning Actions" subtitle="Live experiment registry"/>{rows.length?<DataTable rows={rows} mutate={mutate}/>:<Empty label="learning experiments"/>}</section><aside className={styles.rail}><Head title="Model Health" subtitle="Based on recorded experiments"/><GaugeRows rows={rows}/><div className={styles.insight}><BrainCircuit/><b>Learning pipeline</b><h3>{rows.filter(x=>x.status==="Running").length} active experiments</h3><p>Results appear only after measured records are written.</p></div></aside></div>}

function Planner({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <div className={styles.two}><section className={styles.panel}><Head title="Master Story Blueprint" subtitle="Core narrative and transformation plan"/>{rows.length?<div className={styles.formatMap}><div className={styles.master}><FileStack/><b>Master<br/>Story</b></div>{rows.slice(0,6).map((x,i)=><article key={x.id} style={{gridArea:`a${i+1}`}}><b>{x.title}</b><small>{x.category||x.type}</small><span>{x.status}</span></article>)}</div>:<Empty label="format plans"/>}<Head title="Format Production Plan" subtitle="Database-backed format variants"/>{rows.length?<DataTable rows={rows} mutate={mutate}/>:null}</section><aside className={styles.rail}><Head title="Format Mix" subtitle="Assets by format"/><Donut rows={rows}/><Head title="Adaptation Quality" subtitle="Average live score"/><GaugeRows rows={rows}/></aside></div>}

function Recommendations({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <div className={styles.two}><section className={styles.panel}><Head title="Strategic Recommendations" subtitle="Prioritized by impact, urgency, fit, and execution readiness"/><div className={styles.recommendations}>{rows.map((x,i)=><article key={x.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{x.title}</h3><p>{x.description||"No rationale supplied."}</p><small>Owner: {x.owner} · Score: {x.score??"Not scored"}</small></div><strong>{x.status}</strong><button onClick={()=>change(mutate,x,"Approved")}>Approve</button></article>)}</div>{!rows.length?<Empty label="executive recommendations"/>:null}</section><aside className={styles.rail}><Head title="Decision Readiness" subtitle="Live status distribution"/><Donut rows={rows}/><div className={styles.insight}><Sparkles/><b>Executive insight</b><h3>{rows.filter(x=>x.status==="Decision Required").length} decisions require action</h3><p>Only evidence-backed recommendations stored in the database are shown.</p></div></aside></div>}

function Portfolio({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <><div className={styles.two}><section className={styles.panel}><Head title="Portfolio Balance" subtitle="Opportunity distribution by strategic theme and lifecycle stage"/><div className={styles.balance}>{group(rows,"category").map(([name,items])=><div key={name}><span>{name}<small>{items.length} opportunities</small></span><i><u style={{width:`${Math.max(3,Math.round(items.length/Math.max(1,rows.length)*100))}%`}}/></i></div>)}</div>{!rows.length?<Empty label="portfolio opportunities"/>:null}</section><aside className={styles.rail}><Head title="Lifecycle Distribution" subtitle="Live opportunity stages"/><Donut rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Portfolio Opportunities" subtitle="Existing opportunity intelligence records"/><DataTable rows={rows} mutate={mutate}/></section>:null}</>}

function Campaign({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <><section className={styles.steps}>{["Strategy","Audience","Content Plan","Channels","Schedule & Budget","Review & Launch"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</section><div className={styles.two}><section className={styles.panel}><Head title="Campaign Blueprint" subtitle="Live campaign strategy and content architecture"/>{rows.length?<div className={styles.blueprint}><div><b>Campaign objective</b><p>{rows[0].description||"Objective not provided"}</p></div><div><b>Primary category</b><p>{rows[0].category||"Not assigned"}</p></div><div className={styles.wide}><b>Campaign waves</b><div className={styles.waves}>{["Tease","Educate","Deep Dive","Sustain"].map(x=><span key={x}>{x}</span>)}</div></div></div>:<Empty label="campaign assets"/>}</section><aside className={styles.rail}><Head title="Channel Mix" subtitle="Configured campaign categories"/><Donut rows={rows}/><Head title="Launch Readiness" subtitle="Average asset progress"/><GaugeRows rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Campaign Content Plan" subtitle="Production-ready asset registry"/><DataTable rows={rows} mutate={mutate}/></section>:null}</>}

function Knowledge({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}) {return <><div className={styles.two}><section className={styles.panel}><Head title="Knowledge Health & Freshness" subtitle="Coverage quality and update status across knowledge domains"/><div className={styles.balance}>{group(rows,"category").map(([name,items])=>{const good=items.filter(x=>x.status==="Verified").length/items.length*100;return <div key={name}><span>{name||"Uncategorized"}<small>{items.length} assets</small></span><i className={styles.green}><u style={{width:`${good}%`}}/></i></div>})}</div>{!rows.length?<Empty label="knowledge assets"/>:null}</section><aside className={styles.rail}><Head title="Knowledge Composition" subtitle="Library assets by type"/><Donut rows={rows}/></aside></div>{rows.length?<section className={styles.panel}><Head title="Knowledge Library" subtitle="Trusted reusable intelligence records"/><DataTable rows={rows} mutate={mutate}/></section>:null}</>}

function Head({title,subtitle}:{title:string;subtitle:string}){return <header className={styles.head}><div><h2>{title}</h2><p>{subtitle}</p></div><button><Filter/></button></header>}
function SearchBar({query,setQuery,count}:{query:string;setQuery:(v:string)=>void;count:number}){return <div className={styles.searchbar}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this live page…"/></label><span>{count} database record{count===1?"":"s"}</span></div>}
function DataTable({rows,mutate}:{rows:OperationalRecord[];mutate:(p:OperationalMutation)=>void}){return <div className={styles.table}><header><span>Title</span><span>Category</span><span>Owner</span><span>Score</span><span>Progress</span><span>Status</span><span>Updated</span><span/></header>{rows.map(x=><div key={x.id}><b>{x.title}<small>{x.description}</small></b><span>{x.category||"—"}</span><span>{x.owner}</span><strong>{x.score??"—"}</strong><span><i><u style={{width:`${x.progress||0}%`}}/></i>{x.progress??0}%</span><em>{x.status}</em><span>{new Date(x.updatedAt).toLocaleDateString()}</span><button onClick={()=>mutate({action:"delete",id:x.id})} aria-label="Delete"><Trash2/></button></div>)}</div>}
function CardRow({row,mutate,next}:{row:OperationalRecord;mutate:(p:OperationalMutation)=>void;next:string}){return <article className={styles.card}><b>{row.title}</b><p>{row.description}</p><button onClick={()=>change(mutate,row,next)}>Resolve</button></article>}
function GaugeRows({rows}:{rows:OperationalRecord[]}){const values=rows.slice(0,5);return <div className={styles.gauges}>{values.map(x=><div key={x.id}><span>{x.title}</span><i><u style={{width:`${x.progress??x.score??0}%`}}/></i><b>{x.progress??x.score??0}%</b></div>)}{!values.length?<p>No capacity measurements recorded.</p>:null}</div>}
function Donut({rows}:{rows:OperationalRecord[]}){const groups=group(rows,"status");let offset=0;const colors=["#6435ed","#0ca5d9","#f59b0b","#10a15a","#ef3e70","#6b768c"];const gradient=groups.map(([,items],i)=>{const start=offset;offset+=items.length/Math.max(1,rows.length)*100;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(",");return <div className={styles.donutWrap}><div className={styles.donut} style={{background:`conic-gradient(${gradient||"#e9edf5 0 100%"})`}}><i><b>{rows.length}</b><span>Total</span></i></div><div>{groups.map(([name,items],i)=><p key={name}><i style={{background:colors[i%colors.length]}}/><span>{name}</span><b>{items.length}</b></p>)}</div></div>}
function group(rows:OperationalRecord[],key:"category"|"status"){const map=new Map<string,OperationalRecord[]>();rows.forEach(x=>{const value=x[key]||"Uncategorized";map.set(value,[...(map.get(value)||[]),x]);});return [...map.entries()]}
function money(value:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",notation:"compact",maximumFractionDigits:1}).format(value)}
function exportRows(title:string,rows:OperationalRecord[]){const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const csv=[["Title","Description","Category","Status","Owner","Score","Progress","Amount","Start","Due","Updated"],...rows.map(x=>[x.title,x.description,x.category,x.status,x.owner,x.score,x.progress,x.amount,x.startAt,x.dueAt,x.updatedAt])].map(row=>row.map(cell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${title.toLowerCase().replaceAll(/[^a-z0-9]+/g,"-")}.csv`;link.click();URL.revokeObjectURL(url)}
