"use client";
import {useCallback,useEffect,useState} from "react";
import {Activity,BrainCircuit,Calculator,CheckCircle2,Clock3,DatabaseZap,ShieldCheck,Sparkles,Target,Trophy,Zap} from "lucide-react";
import {PageTop} from "./OpportunityDashboard";
import {loadScoring} from "@/lib/gap-scoring-api";
import type {ScoringData} from "@/types/gap-scoring";
import styles from "./GapScoring.module.css";
const icons=[Calculator,Trophy,Target,BrainCircuit];
export function OpportunityScoringPage(){
  const[data,setData]=useState<ScoringData|null>(null),[message,setMessage]=useState("");
  const refresh=useCallback(async()=>{try{setData(await loadScoring());setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Autonomous scoring telemetry is unavailable.")}},[]);
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),10_000);return()=>window.clearInterval(timer)},[refresh]);
  const best=data?.items[0],autonomy=data?.autonomy,last=autonomy?.lastRun;
  return <main className={styles.shell}><PageTop current="Scoring Engine" title="Autonomous Opportunity Scoring Engine" subtitle="Continuously discovers, evaluates, ranks, and routes opportunities using an adaptive evidence-calibrated ensemble."/>
    <div className={`${styles.actions} ${styles.autoActions}`}><span><Activity/>Engine {autonomy?.state??"connecting"}</span><span><ShieldCheck/>Zero-input scoring</span><span><Clock3/>Every {autonomy?.intervalSeconds??30}s</span></div>
    {message&&<div className={styles.notice}>{message}</div>}
    <section className={styles.autonomyBanner}><BrainCircuit/><div><small>OPPORTUNITY AUTONOMY ENGINE</small><h2>Adaptive scoring and lifecycle decisions are fully machine-owned</h2><p>Reliability-weighted factors, nonlinear calibration, evidence agreement, uncertainty penalties, and autonomous promotion operate continuously without human input.</p></div><aside><b><i/> {autonomy?.state??"connecting"}</b><span>No operator actions</span></aside></section>
    <section className={styles.metrics}>{data?.metrics.map((metric,index)=>{const Icon=icons[index];return <article className={styles.metric} data-tone={metric.tone} key={metric.label}><span><Icon/></span><div><b>{metric.label}</b><strong>{metric.value}</strong><small>{metric.detail}</small></div></article>})}</section>
    <div className={styles.runStrip}><span><DatabaseZap/><small>Candidates scanned</small><b>{last?.scanned??0}</b></span><span><Zap/><small>Auto-promoted</small><b>{last?.promoted??0}</b></span><span><Activity/><small>Autonomous enrichment</small><b>{last?.enriching??0}</b></span><span><Target/><small>Mean confidence</small><b>{last?.averageConfidence??0}%</b></span><span><Clock3/><small>Next cycle</small><b>{relative(autonomy?.nextRunAt)}</b></span></div>
    <div className={styles.scoreGrid}><section className={styles.panel}><h2>Self-Calibrating Scoring Policy</h2><div className={styles.weights}>{data?.weights.map(weight=><div className={styles.weight} data-rating={weight.rating} key={weight.key}><div><b>{weight.label}</b><small>{weight.description}</small></div><b>{weight.weight}%</b><i className={styles.policyBar}><u style={{width:`${weight.weight*2}%`}}/></i><em>Adaptive</em></div>)}<footer className={styles.weightFooter}><BrainCircuit/> Base policy normalized continuously <span className={styles.good}>Policy engine locked</span><b>{autonomy?.algorithmVersion??"adaptive-opportunity-ensemble-v4"}</b></footer></div></section><aside className={styles.right}><section className={styles.panel}><h2>Score Distribution</h2><div className={styles.gaugeWrap}><div className={styles.gauge}><span><b>{data?.averageScore??0}</b>Average Score</span></div><div className={styles.distCounts}><span><b>{data?.distribution.exceptional||0}</b>Exceptional</span><span><b>{data?.distribution.strong||0}</b>Strong</span><span><b>{data?.distribution.moderate||0}</b>Moderate</span><span><b>{data?.distribution.low||0}</b>Low</span></div></div></section><section className={`${styles.panel} ${styles.insight}`}><h3><Sparkles/> Autonomous Scoring Decision</h3><strong>{best?.title||"Autonomous discovery initializing"}</strong><p>{best?`The engine assigned ${best.score}/100 with ${best.attributes.confidence||0}% calibrated confidence and routed it as ${best.state}.`:"The scheduler is preparing the first machine-owned scoring cycle."}</p><footer><small>{best?.attributes.algorithm||autonomy?.algorithmVersion||"Adaptive ensemble"}</small><span><CheckCircle2/>No human review</span></footer></section></aside></div>
    <section className={`${styles.panel} ${styles.tablePanel}`}><header className={styles.tableHead}><h2>Autonomously Ranked Opportunities</h2><span className={styles.locked}><ShieldCheck/>Model: {data?.modelName||"Adaptive Opportunity v4"}</span><span className={styles.locked}><Zap/>Lifecycle routing automatic</span></header><div className={styles.table}><div className={styles.rankHeader}><span>Rank</span><span>Opportunity</span><span>Final Score</span><span>Demand</span><span>Gap</span><span>Momentum</span><span>Resonance</span><span>Feasibility</span><span>Confidence</span><span>Autonomous State</span><span/></div>{data?.items.map((item,index)=><div className={styles.rankRow} key={item.id}><b>{index+1}</b><b>{item.title}</b><span className={styles.scorePill}>{item.score}</span>{["demand","gap","momentum","resonance","feasibility","confidence"].map(key=><span className={styles.mini} key={key}>{item.attributes[key]}<i><u style={{width:`${item.attributes[key]}%`}}/></i></span>)}<span className={styles.status}>{item.state}</span><CheckCircle2/></div>)}</div><footer className={styles.pagination}>Showing {data?.items.length||0} machine-scored opportunities <span>{last?.trigger==="scheduler"?"Scheduler verified":"Waiting for scheduler"}</span></footer></section>
  </main>;
}
function relative(value:string|null|undefined){if(!value)return "Pending";const seconds=Math.round((new Date(value).getTime()-Date.now())/1000);return seconds<=0?"Due now":`${seconds}s`;}
