"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, ChevronDown, Download, Filter, Grid2X2, List, MoreVertical, Plus, RefreshCw, Search, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { actOnOpportunity, discoverOpportunity, loadOpportunityDashboard } from "@/lib/opportunity-intelligence-api";
import type { OpportunityDashboardData, OpportunityRecord } from "@/types/opportunity-intelligence";
import styles from "./OpportunityIntelligence.module.css";

export function OpportunityDashboard(){
 const [data,setData]=useState<OpportunityDashboardData|null>(null),[selected,setSelected]=useState<string>(""),[query,setQuery]=useState(""),[tab,setTab]=useState("All Opportunities"),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const refresh=useCallback(async(signal?:AbortSignal)=>{setBusy("refresh");try{const next=await loadOpportunityDashboard(signal);setData(next);setSelected(current=>current||next.opportunities[0]?.id||"");setMessage("");}catch(error){if((error as Error).name!=="AbortError")setMessage((error as Error).message);}finally{setBusy("");}},[]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);return()=>controller.abort();},[refresh]);
 const rows=useMemo(()=>data?.opportunities.filter(item=>`${item.title} ${item.subtitle} ${item.category}`.toLowerCase().includes(query.toLowerCase())&&(tab==="All Opportunities"||(tab==="High Priority"&&item.highPriority)||(tab==="Monitoring"&&item.status==="Monitoring")||(tab==="Archived"&&false)))||[],[data,query,tab]);
 const active=data?.opportunities.find(item=>item.id===selected)||data?.opportunities[0];
 async function discover(){setBusy("discover");try{const item=await discoverOpportunity();await refresh();setSelected(item.id);setMessage("New opportunity saved to the database.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}}
 async function act(action:"open"|"initiative"){if(!active)return;setBusy(action);try{await actOnOpportunity(active.id,action);await refresh();setMessage(action==="initiative"?"Initiative created and saved.":"Opportunity activity saved.");}catch(e){setMessage((e as Error).message);}finally{setBusy("");}}
 return <div className={styles.page}><PageTop current="Opportunity Dashboard" title="Opportunity Dashboard" subtitle="Discover, score, prioritize, and activate high-value opportunities across markets, audiences, content, partnerships, and revenue."/>
  <section className={styles.workspaceBar}><span className={styles.heroIcon}><Sparkles/></span><div><b>Opportunity Intelligence Workspace</b><small>Last opportunity scan: 6 minutes ago　 <i/> Signals live</small></div><div className={styles.barActions}><button onClick={()=>refresh()}><RefreshCw/>Refresh</button><button><Download/>Export</button><button className={styles.primary} onClick={discover} disabled={!!busy}><Plus/>{busy==="discover"?"Discovering…":"Discover Opportunities"}</button></div></section>
  {message?<div className={styles.notice}>{message}</div>:null}
  <div className={styles.metrics}>{([
    [data?.metrics.active??"—","Active Opportunities","+16 this week",Target,"purple"],[money(data?.metrics.estimatedValue),"Estimated Value","+18.4% potential",TrendingUp,"green"],[data?.metrics.highPriority??"—","High Priority","Ready to activate",TrendingUp,"orange"],[`${data?.metrics.averageConfidence??"—"}%`,"Avg. Confidence","Based on live signals",ShieldCheck,"blue"],[data?.metrics.atRisk??"—","At Risk","Require action",AlertTriangle,"red"]
   ] as Array<[string|number,string,string,LucideIcon,string]>).map(([value,label,detail,Icon,tone])=><article key={label} data-tone={tone}><span><Icon/></span><div><strong>{String(value)}</strong><b>{label}</b><small>{detail}</small></div></article>)}</div>
  <div className={styles.dashboardGrid}><section className={styles.panel}><PanelHead title="Opportunity Command Center" subtitle="AI-ranked opportunities based on strategic fit, value potential, timing, confidence, and execution readiness."/>
   <nav className={styles.tabs}>{[["All Opportunities",data?.metrics.active],["High Priority",data?.metrics.highPriority],["Quick Wins",28],["Strategic Bets",22],["Monitoring",31],["Archived",13]].map(([name,count])=><button key={String(name)} className={tab===name?styles.active:""} onClick={()=>setTab(String(name))}>{name}<b>{count}</b></button>)}</nav>
   <div className={styles.tools}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search opportunities, markets, audiences, or signals..."/></label><button><Filter/>Filters <b>5</b></button><button>Sort: Opportunity Score <ChevronDown/></button><span><button className={styles.selected}><List/></button><button><Grid2X2/></button></span></div>
   <div className={styles.scoreStrip}><span>Market demand <b>82%</b></span><span>Strategic alignment <b>88%</b></span><span>Execution readiness <b className={styles.orangeText}>71%</b></span><span>Competitive whitespace <b className={styles.orangeText}>64%</b></span></div>
   <OpportunityTable rows={rows} selected={active?.id} onSelect={setSelected}/><footer className={styles.pagination}>Showing 1–{rows.length} of {data?.metrics.active??0} opportunities <span>‹　<b>1</b>　2　3　4　5　…　22　›</span></footer>
  </section><aside className={styles.rightRail}><Portfolio data={data}/>{active?<Selected item={active} onAction={act} busy={busy}/>:null}<section className={styles.smallPanel}><h3>Pipeline Health</h3>{data?.pipeline.map((item,index)=><div className={styles.pipeline} key={item.label}><span>{item.label}</span><b>{item.count}</b><i><u style={{width:`${100-index*18}%`}}/></i></div>)}</section><section className={styles.brief}><h3><Sparkles/> AI Opportunity Brief</h3><p>Demand for practical industrial AI training is accelerating across West Africa while enterprise-grade learning supply remains limited.</p><span><b>High demand</b><b>Low competition</b><b>Strong brand fit</b></span><button>Review recommendation ↗</button></section></aside></div>
 </div>;
}

function PageTop({current,title,subtitle}:{current:string;title:string;subtitle:string}){return <><div className={styles.utility}><span>Opportunity Intelligence　/　<b>{current}</b></span><div><button>Workspace　·　CACSMS Studio　<ChevronDown/></button><button>Brand　·　CACSMS　<ChevronDown/></button><Bell/></div></div><header className={styles.pageTitle}><h1>{title}</h1><p>{subtitle}</p></header></>}
function PanelHead({title,subtitle}:{title:string;subtitle:string}){return <header className={styles.panelHead}><div><h2>{title}</h2><p>{subtitle}</p></div><button><Download/>Export</button><button><MoreVertical/></button></header>}
function money(value?:number){if(value===undefined)return"—";return `₦${Math.round(value/1_000_000)}M`;}
function OpportunityTable({rows,selected,onSelect}:{rows:OpportunityRecord[];selected?:string;onSelect:(id:string)=>void}){return <div className={styles.table}><header><span>OPPORTUNITY</span><span>CATEGORY</span><span>EST. VALUE</span><span>CONFIDENCE</span><span>TIMING</span><span>OWNER</span><span>OPPORTUNITY SCORE</span><span>STATUS</span><span/></header>{rows.map((item,index)=><button className={selected===item.id?styles.rowSelected:""} key={item.id} onClick={()=>onSelect(item.id)}><em>{index+1}</em><span><b>{item.title}</b><small>{item.subtitle}</small></span><span>{item.category}</span><strong>{money(item.estimatedValue)}</strong><strong className={item.confidence<60?styles.redText:styles.greenText}>{item.confidence}%</strong><i>{item.timing}</i><span><b>{item.owner}</b></span><span className={styles.score}><b>{item.score} / 100</b><i><u style={{width:`${item.score}%`}}/></i></span><i data-status={item.status}>{item.status}</i><MoreVertical/></button>)}</div>}
function Portfolio({data}:{data:OpportunityDashboardData|null}){let offset=0;const gradient=(data?.portfolio||[]).map(x=>{const start=offset;offset+=x.value;return `${x.color} ${start}% ${offset}%`;}).join(",");return <section className={styles.smallPanel}><h3>Opportunity Portfolio <span>Value　 Count</span></h3><div className={styles.portfolio}><div className={styles.donut} style={{background:`conic-gradient(${gradient||"#eee 0 100%"})`}}><i><b>{money(data?.metrics.estimatedValue)}</b><small>total potential</small></i></div><div>{data?.portfolio.map(item=><p key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.value}%</b></p>)}</div></div></section>}
function Selected({item,onAction,busy}:{item:OpportunityRecord;onAction:(a:"open"|"initiative")=>void;busy:string}){const facts=[["Estimated value",money(item.estimatedValue)],["Confidence",`${item.confidence}%`],["Time to value",item.timing],["Strategic fit",`${item.strategicFit}%`],["Demand strength",`${item.marketDemand}%`],["Competitive whitespace",`${item.competitiveWhitespace}%`],["Execution readiness",`${item.executionReadiness}%`]];return <section className={styles.smallPanel}><small>Selected Opportunity</small><h3>{item.title}</h3><div className={styles.selectedOpportunity}><div className={styles.ring}><b>{item.score}</b><small>/ 100</small></div><div>{facts.map(([label,value])=><p key={label}><span>{label}</span><i><u style={{width:typeof value==="string"&&value.endsWith("%")?value:"88%"}}/></i><b>{value}</b></p>)}</div></div><div className={styles.splitButtons}><button className={styles.primary} onClick={()=>onAction("open")} disabled={!!busy}>Open opportunity</button><button onClick={()=>onAction("initiative")} disabled={!!busy}>Create initiative</button></div></section>}
export {PageTop};
