"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, BarChart3, Brain, CalendarDays, CheckCircle2, ChevronRight, CircleDot,
  ClipboardCheck, FileOutput, FileText, Gauge, Infinity, Layers3, Monitor, PlaySquare, Rocket,
  Search, Settings2, ShieldCheck, Sparkles, Target, UsersRound
} from "lucide-react";
import { lifecyclePhases, productionLifecycleStages, type ProductionLifecycleStage } from "@cacsms/contracts";
import styles from "./ProductionLifecycleWorkspace.module.css";

const icons = {discover:Target,research:Search,evaluate:ClipboardCheck,"pre-plan":FileText,schedule:CalendarDays,produce:PlaySquare,assemble:Layers3,quality:ShieldCheck,export:FileOutput,publish:Rocket,monitor:BarChart3,learn:Brain,repeat:Infinity} as const;
const phaseNames={intelligence:"Intelligence",planning:"Planning",creation:"Creation",release:"Release",improvement:"Improvement"};

export function ProductionLifecycleWorkspace({stage}:{stage:ProductionLifecycleStage}){
  const [autoAdvance,setAutoAdvance]=useState(true); const [role,setRole]=useState<"all"|"primary"|"supporting">("all");
  const currentIndex=productionLifecycleStages.findIndex(item=>item.id===stage.id); const previous=productionLifecycleStages[currentIndex-1]; const next=productionLifecycleStages[currentIndex+1];
  const grouped=useMemo(()=>{const pages=role==="all"?stage.pages:stage.pages.filter(item=>item.role===role);return pages.reduce<Record<string,typeof pages>>((groups,item)=>{(groups[item.module]??=[]).push(item);return groups},{});},[role,stage.pages]);
  return <section className={styles.page}>
    <header className={styles.pageHeader}><div><span>Production Workflow <i>/</i> Stage {stage.order} of 13</span><h1>{stage.label}</h1><p>{stage.description}</p></div><div className={styles.headerActions}><Link href="/production-pipeline/index.html"><Gauge size={16}/>Pipeline Overview</Link><Link className={styles.primary} href={stage.pages[0]?.href??"/dashboard"}><ArrowRight size={16}/>Open Primary Workspace</Link></div></header>
    <section className={styles.lifecycle} aria-label="Production life cycle"><header><div><h2>Production Life Cycle</h2><p>Navigate the end-to-end autonomous production workflow.</p></div><label>Auto-Advance <button type="button" role="switch" aria-checked={autoAdvance} className={autoAdvance?styles.switchOn:styles.switch} onClick={()=>setAutoAdvance(value=>!value)}><span/></button></label><Link href="/settings/production-defaults"><Settings2 size={14}/>Configure</Link></header><div className={styles.phaseBand}>{lifecyclePhases.map(phase=><span key={phase.id} data-active={phase.id===stage.phase}>{phase.label}<small>{phase.description}</small></span>)}</div><div className={styles.stageRail}>{productionLifecycleStages.map((item,index)=>{const Icon=icons[item.id];const complete=item.order<stage.order;return <div className={styles.stageWrap} key={item.id}><Link href={`/production-workflow/${item.id}`} className={`${styles.stage}${item.id===stage.id?` ${styles.active}`:""}${complete?` ${styles.complete}`:""}`} aria-current={item.id===stage.id?"step":undefined}><b>{item.order}</b><i><Icon size={21}/></i><strong>{item.label}</strong><small>{item.description}</small><em>{item.statusLabel}</em></Link>{index<productionLifecycleStages.length-1?<ChevronRight className={styles.arrow} size={18}/>:null}</div>})}</div></section>
    <section className={styles.stageSummary}><article><i><CircleDot size={22}/></i><span><small>Current phase</small><b>{phaseNames[stage.phase]}</b><em>Stage {stage.order} of 13</em></span></article><article><i><CheckCircle2 size={22}/></i><span><small>Required outcome</small><b>{stage.outcome}</b><em>Complete this outcome before advancing.</em></span></article><article><i><UsersRound size={22}/></i><span><small>Connected workspaces</small><b>{stage.pages.length} canonical pages</b><em>{new Set(stage.pages.map(item=>item.module)).size} capability modules</em></span></article><article><i><Sparkles size={22}/></i><span><small>Automation policy</small><b>{autoAdvance?"Auto-advance enabled":"Manual advancement"}</b><em>{autoAdvance?"Advance when required checks pass.":"A user must approve stage completion."}</em></span></article></section>
    <div className={styles.contentGrid}><main><header className={styles.directoryHeader}><div><h2>{stage.label} workspace directory</h2><p>Open the existing canonical page needed for this stage. No pages are duplicated.</p></div><div><button className={role==="all"?styles.selected:""} onClick={()=>setRole("all")}>All</button><button className={role==="primary"?styles.selected:""} onClick={()=>setRole("primary")}>Primary</button><button className={role==="supporting"?styles.selected:""} onClick={()=>setRole("supporting")}>Supporting</button></div></header><div className={styles.moduleGroups}>{Object.entries(grouped).map(([module,pages])=><section key={module}><header><h3>{module}</h3><span>{pages.length} page{pages.length===1?"":"s"}</span></header><div>{pages.map(link=><Link href={link.href} key={`${module}-${link.label}`}><i>{link.role==="primary"?<CircleDot size={16}/>:<Monitor size={16}/>}</i><span><b>{link.label}</b><small>{link.purpose}</small></span><em>{link.role}</em><ArrowRight size={15}/></Link>)}</div></section>)}</div></main><aside><section className={styles.checklist}><h2>Stage completion standard</h2><p>Advance only when the required outcome is complete and supporting evidence is recorded.</p>{["Required work completed","Validation checks passed","Exceptions and blockers resolved","Stage output recorded","Next stage is ready"].map((item,index)=><label key={item}><input type="checkbox" defaultChecked={index<2}/><span>{item}</span></label>)}<button><CheckCircle2 size={15}/>Mark stage ready</button></section><section className={styles.governance}><h2>Lifecycle governance</h2><dl><div><dt>Stage owner</dt><dd>{stage.pages[0]?.module}</dd></div><div><dt>Canonical route</dt><dd>/production-workflow/{stage.id}</dd></div><div><dt>Auto-advance</dt><dd>{autoAdvance?"Enabled":"Disabled"}</dd></div><div><dt>Page ownership</dt><dd>Capability modules</dd></div></dl></section></aside></div>
    <footer className={styles.stageNavigation}>{previous?<Link href={`/production-workflow/${previous.id}`}><ArrowLeft size={16}/><span><small>Previous stage</small><b>{previous.label}</b></span></Link>:<span/>}<Link href="/production-workflow/discover" className={styles.allStages}>View complete lifecycle</Link>{next?<Link href={`/production-workflow/${next.id}`}><span><small>Next stage</small><b>{next.label}</b></span><ArrowRight size={16}/></Link>:<span/>}</footer>
  </section>
}
