"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,Bot,BrainCircuit,CheckCircle2,Clock3,Clapperboard,Film,Layers3,Radio,ShieldCheck,Sparkles,Workflow} from "lucide-react";
import type {OrchestrationStatus} from "@/lib/autonomous-production-orchestrator";
import styles from "./AutonomousCreateProductionPage.module.css";

const empty:OrchestrationStatus={enabled:true,state:"waiting",algorithmVersion:"adaptive-multimodal-production-orchestrator-v6",intervalSeconds:30,nextRunAt:null,lastRun:null,productions:[],decisions:[]};
const pipeline=["research","scripting","storyboard","visual-generation","audio-generation","assembly","quality-assurance","publishing","completed"];
const label=(value:string)=>value.replaceAll("-"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export function CreateProductionPage(){
  const [data,setData]=useState(empty);const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/production-studio/create-production",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message||"Production orchestration telemetry is unavailable.");setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Production orchestration telemetry is unavailable.");}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10_000);return()=>window.clearInterval(timer);},[load]);
  const last=data.lastRun;const active=data.productions.filter(row=>row.status!=="published"&&row.stage!=="completed").length;const published=data.productions.filter(row=>row.status==="published"||row.stage==="completed").length;const agents=data.productions.length*8;const stageCounts=useMemo(()=>pipeline.map(stage=>({stage,count:data.productions.filter(row=>row.stage===stage).length})),[data.productions]);
  return <section className={styles.page}>
    <header className={styles.pageHeader}><div><div className={styles.breadcrumb}><span>Home</span><i>/</i><span>Production Studio</span><i>/</i><strong>Autonomous Production</strong></div><h1>Autonomous Production Orchestrator</h1><p>Continuously converts approved intelligence into planned, generated, quality-assured, and distributed media without operator input.</p></div><span><ShieldCheck/>Zero-input production</span><span><Clock3/>Every {data.intervalSeconds}s</span></header>
    {error?<div className={styles.error}><AlertTriangle/>{error}</div>:null}
    <section className={styles.engine}><BrainCircuit/><div><small>PRODUCTION AUTONOMY ENGINE</small><h2>Adaptive multimodal orchestration is active</h2><p>Semantic format selection, audience targeting, agent allocation, capacity control, stage routing, rendering, quality assurance, and publishing are machine-owned.</p></div><aside><span><b>{last?.scanned??0}</b>Signals</span><span><b>{last?.generated??0}</b>Generated</span><span><b>{last?.advanced??0}</b>Advanced</span><span><b>{last?.agents??0}</b>Agents allocated</span><span><b>{last?.averageConfidence??0}%</b>Confidence</span></aside><em><i/>{data.state}<small>{data.algorithmVersion}</small></em></section>
    <section className={styles.metrics}>
      <article><i><Clapperboard/></i><span><small>Autonomous Productions</small><strong>{data.productions.length}</strong><em>Generated from executive intelligence</em></span></article>
      <article><i><Activity/></i><span><small>Actively Orchestrated</small><strong>{active}</strong><em>No manual workflow steps</em></span></article>
      <article><i><Bot/></i><span><small>AI Agent Capacity</small><strong>{agents}</strong><em>Eight specialist agents per production</em></span></article>
      <article><i><Radio/></i><span><small>Published Autonomously</small><strong>{published}</strong><em>Multi-platform distribution</em></span></article>
    </section>
    <section className={styles.stepper}>{pipeline.map((stage,index)=><div key={stage} className={stageCounts[index].count?styles.activeStage:""}><span>{index+1}</span><b>{label(stage)}</b><small>{stageCounts[index].count} production{stageCounts[index].count===1?"":"s"}</small>{index<pipeline.length-1?<i/>:null}</div>)}</section>
    <div className={styles.grid}>
      <section className={styles.panel}><header><div><h2>Autonomous Production Pipeline</h2><p>Live stage distribution with scheduler-owned advancement</p></div><Workflow/></header><div className={styles.pipeline}>{stageCounts.map(({stage,count})=><div key={stage}><span><b>{label(stage)}</b><small>{count} active</small></span><i><u style={{width:`${data.productions.length?Math.max(count?8:0,count/data.productions.length*100):0}%`}}/></i><strong>{count}</strong></div>)}</div></section>
      <aside className={styles.panel}><header><div><h2>Autonomous Agent Team</h2><p>Specialists allocated per production</p></div><Bot/></header><div className={styles.agents}>{[["Evidence Research","research"],["Narrative Synthesis","script"],["Story Architecture","storyboard"],["Multimodal Visual","visual"],["Voice & Sound","audio"],["Timeline Assembly","assembly"],["Autonomous QA","quality"],["Distribution","publishing"]].map(([name,role])=><div key={role}><span><i/><b>{name}</b></span><em>{data.productions.filter(item=>item.stage.includes(role)||role==="script"&&item.stage==="scripting"||role==="quality"&&item.stage==="quality-assurance").length} running</em></div>)}</div></aside>
    </div>
    <section className={styles.panel}><header><div><h2>Machine-Generated Productions</h2><p>Format, audience, channel, readiness, and lifecycle selected autonomously</p></div><span className={styles.healthy}><i/>{data.state}</span></header><div className={styles.table}><div><b>Production</b><b>Format</b><b>Audience</b><b>Stage</b><b>Progress</b><b>Readiness</b><b>Risk</b><b>Channels</b></div>{data.productions.map(row=><div key={row.id}><span><b>{row.title}</b><small>{row.code} · {row.priority} priority</small></span><span>{row.type}</span><span>{row.audience}</span><em>{label(row.stage)}</em><span><i><u style={{width:`${row.progress}%`}}/></i>{row.progress}%</span><strong>{row.readiness.toFixed(1)}%</strong><span>{row.risk.toFixed(1)}%</span><small>{row.channels.join(" · ")}</small></div>)}</div>{!data.productions.length?<div className={styles.empty}><Film/><h3>Autonomous intake is active</h3><p>Eligible executive recommendations will be converted into productions on the next cycle.</p></div>:null}</section>
    <section className={styles.panel}><header><div><h2>Recent Orchestration Decisions</h2><p>Persisted machine rationale and lifecycle actions</p></div><Sparkles/></header><div className={styles.decisions}>{data.decisions.slice(0,12).map(item=><article key={item.id}><CheckCircle2/><div><b>{item.title??"Capacity decision"}</b><small>{label(item.action)} · {item.format??"Format pending"}</small></div><span>Readiness <b>{item.readiness.toFixed(1)}%</b></span><span>Risk <b>{item.risk.toFixed(1)}%</b></span><span>Confidence <b>{item.confidence.toFixed(1)}%</b></span></article>)}</div></section>
  </section>;
}
