"use client";
import { RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { fetchProductionStudioPage } from "@/lib/api/production-studio";
import type { ProductionPageResponse } from "@/types/production-studio";
import styles from "./ProductionStudio.module.css";
const stages = ["Ideas", "Research", "Writing", "Storyboard", "Production", "Review", "Approval", "Scheduled", "Published"];
const empty: ProductionPageResponse = { generatedAt: new Date(0).toISOString(), slug: "production-pipeline", metrics: [], records: [], panels: {}, total: 0 };
export function ProductionPipelinePage() { const [data,setData]=useState(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{setData(await fetchProductionStudioPage("production-pipeline",signal))}catch(cause){if((cause as Error).name!=="AbortError")setError(cause instanceof Error?cause.message:"Unable to load pipeline.")}finally{if(!signal?.aborted)setLoading(false)}},[]); useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]); return <section className={styles.page}><header className={styles.header}><div><div className={styles.breadcrumb}>Production Studio / Production Pipeline</div><h1 className={styles.title}>Production Pipeline</h1><p className={styles.subtitle}>Visualize stage capacity, work in progress, bottlenecks, dependencies, and SLA performance.</p></div><div className={styles.actions}><button className={styles.control}>Workspace · CACSMS Studio</button><button className={styles.button} onClick={()=>void load()} disabled={loading}><RefreshCw size={13}/> Refresh</button><button className={styles.primary}>Configure Pipeline</button></div></header>{error?<div className={styles.error}>{error}</div>:null}<section className={`${styles.card} ${styles.board}`}>{stages.map(stage=>{const records=data.records.filter(record=>record.stage===stage);return <div className={styles.boardColumn} key={stage}><div className={styles.boardHeader}><span>{stage}</span><span>{records.length}</span></div>{records.map(record=><article className={styles.boardCard} key={record.id}><div className={styles.primaryText}>{record.title}</div><div className={styles.meta}>{record.code} · {record.owner}</div><div className={styles.progress} style={{marginTop:10}}><div className={styles.track}><div className={styles.fill} style={{width:`${record.progress}%`}}/></div><strong>{record.progress}%</strong></div><span className={styles.badge}>{record.status}</span></article>)}{!loading&&records.length===0?<div className={styles.empty}>No items</div>:null}{loading?<div className={styles.empty}>Loading…</div>:null}</div>})}</section></section> }
