IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name=N'cacsms') EXEC(N'CREATE SCHEMA cacsms');
IF OBJECT_ID(N'cacsms.OpportunitySchedulerAutonomySettings','U') IS NULL
CREATE TABLE cacsms.OpportunitySchedulerAutonomySettings(WorkspaceId uniqueidentifier NOT NULL PRIMARY KEY,Enabled bit NOT NULL CONSTRAINT DF_SchedulerSettings_Enabled DEFAULT(1),RunIntervalSeconds int NOT NULL CONSTRAINT DF_SchedulerSettings_Interval DEFAULT(30),AlgorithmVersion nvarchar(120) NOT NULL,TimingThreshold decimal(5,2) NOT NULL,ConflictThreshold decimal(5,2) NOT NULL,MaximumRisk decimal(5,2) NOT NULL,LastRunAt datetimeoffset NULL,NextRunAt datetimeoffset NULL,UpdatedAt datetimeoffset NOT NULL CONSTRAINT DF_SchedulerSettings_Updated DEFAULT(SYSUTCDATETIME()));
IF OBJECT_ID(N'cacsms.OpportunitySchedulerAutonomyRuns','U') IS NULL
CREATE TABLE cacsms.OpportunitySchedulerAutonomyRuns(SchedulerRunId uniqueidentifier NOT NULL CONSTRAINT PK_SchedulerRuns PRIMARY KEY DEFAULT NEWSEQUENTIALID(),WorkspaceId uniqueidentifier NOT NULL,TriggerSource nvarchar(40) NOT NULL,AlgorithmVersion nvarchar(120) NOT NULL,Status nvarchar(30) NOT NULL,CampaignAssetsScanned int NOT NULL DEFAULT(0),SchedulesGenerated int NOT NULL DEFAULT(0),SchedulesUpdated int NOT NULL DEFAULT(0),UpcomingCount int NOT NULL DEFAULT(0),RebalancedCount int NOT NULL DEFAULT(0),ConflictsDetected int NOT NULL DEFAULT(0),HeldCount int NOT NULL DEFAULT(0),DuplicatesSuppressed int NOT NULL DEFAULT(0),AverageTimingScore decimal(5,2) NOT NULL DEFAULT(0),AverageCapacityScore decimal(5,2) NOT NULL DEFAULT(0),AverageConfidence decimal(5,2) NOT NULL DEFAULT(0),ErrorMessage nvarchar(1000) NULL,StartedAt datetimeoffset NOT NULL DEFAULT(SYSUTCDATETIME()),CompletedAt datetimeoffset NULL);
IF OBJECT_ID(N'cacsms.OpportunitySchedulerAutonomyDecisions','U') IS NULL
CREATE TABLE cacsms.OpportunitySchedulerAutonomyDecisions(SchedulerDecisionId uniqueidentifier NOT NULL CONSTRAINT PK_SchedulerDecisions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),SchedulerRunId uniqueidentifier NOT NULL,RecordId uniqueidentifier NOT NULL,SourceCampaignRecordId uniqueidentifier NOT NULL,Action nvarchar(60) NOT NULL,Channel nvarchar(120) NOT NULL,ScheduledAt datetimeoffset NOT NULL,TimingScore decimal(5,2) NOT NULL,CapacityScore decimal(5,2) NOT NULL,ConflictScore decimal(5,2) NOT NULL,RiskScore decimal(5,2) NOT NULL,Confidence decimal(5,2) NOT NULL,RationaleJson nvarchar(max) NOT NULL,CreatedAt datetimeoffset NOT NULL DEFAULT(SYSUTCDATETIME()));
IF NOT EXISTS (SELECT 1 FROM cacsms.OpportunitySchedulerAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active')
INSERT cacsms.OpportunitySchedulerAutonomySettings(WorkspaceId,AlgorithmVersion,TimingThreshold,ConflictThreshold,MaximumRisk,NextRunAt) SELECT TOP(1) WorkspaceId,N'capacity-aware-opportunity-scheduler-v5',82,70,35,SYSUTCDATETIME() FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;
