import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";

export const OPPORTUNITY_PORTFOLIO_ALGORITHM="adaptive-portfolio-orchestrator-v4";
type Settings={WorkspaceId:string;Enabled:boolean;RunIntervalSeconds:number;PromoteThreshold:number;PrioritizeThreshold:number;NextRunAt:Date|null};
type ScoredItem={IntelligenceItemId:string;Title:string;Subtitle:string|null;Category:string;Score:number;AttributesJson:string};
type Opportunity={OpportunityId:string;Title:string;Category:string;Confidence:number;OpportunityScore:number;MarketDemand:number;StrategicFit:number;ExecutionReadiness:number;CompetitiveWhitespace:number;IsAtRisk:boolean};
export type PortfolioCycleResult={runId:string;status:"completed"|"skipped";scanned:number;ingested:number;updated:number;promoted:number;enriching:number;duplicates:number;portfolioScore:number;averageConfidence:number};
const globalPortfolio=globalThis as typeof globalThis&{__portfolioCycle?:Promise<PortfolioCycleResult>};
const clamp=(value:number)=>Math.max(0,Math.min(100,Number.isFinite(value)?value:0));
const round=(value:number)=>Math.round(clamp(value)*10)/10;
const parse=(value:string)=>{try{return JSON.parse(value) as Record<string,unknown>;}catch{return {};}};
const value=(attributes:Record<string,unknown>,key:string,fallback:number)=>{const result=Number(attributes[key]);return Number.isFinite(result)?clamp(result):clamp(fallback);};
const tokens=(text:string)=>new Set(text.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(token=>token.length>2));
function similarity(left:string,right:string){const a=tokens(left),b=tokens(right);if(!a.size||!b.size)return 0;let common=0;for(const token of a)if(b.has(token))common++;return common/(a.size+b.size-common)*100;}

async function configuration(){const pool=await getMssqlPool();const result=await pool.request().query<Settings>(`SELECT TOP(1) s.* FROM cacsms.OpportunityPortfolioAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active' ORDER BY w.CreatedAt`);if(!result.recordset[0])throw new Error("Autonomous opportunity portfolio is not configured.");return {pool,settings:result.recordset[0]};}
export async function runAutonomousOpportunityPortfolioCycle(trigger="scheduler",force=false){if(globalPortfolio.__portfolioCycle)return globalPortfolio.__portfolioCycle;const operation=execute(trigger,force).finally(()=>{globalPortfolio.__portfolioCycle=undefined;});globalPortfolio.__portfolioCycle=operation;return operation;}

async function execute(trigger:string,force:boolean):Promise<PortfolioCycleResult>{
  const {pool,settings}=await configuration();if(!settings.Enabled||(!force&&settings.NextRunAt&&settings.NextRunAt.getTime()>Date.now()))return {runId:"",status:"skipped",scanned:0,ingested:0,updated:0,promoted:0,enriching:0,duplicates:0,portfolioScore:0,averageConfidence:0};
  const started=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("trigger",sql.NVarChar(40),trigger.slice(0,40)).input("algorithm",sql.NVarChar(100),OPPORTUNITY_PORTFOLIO_ALGORITHM).query<{id:string}>(`INSERT cacsms.OpportunityPortfolioAutonomyRuns(WorkspaceId,TriggerSource,AlgorithmVersion,Status) OUTPUT CONVERT(nvarchar(36),inserted.OpportunityPortfolioRunId) id VALUES(@workspace,@trigger,@algorithm,N'running')`);
  const runId=started.recordset[0].id;let ingested=0,updated=0,promoted=0,enriching=0,duplicates=0;const scores:number[]=[];const confidences:number[]=[];
  try{
    const scored=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("threshold",sql.TinyInt,Math.round(settings.PrioritizeThreshold)).query<ScoredItem>(`SELECT CONVERT(nvarchar(36),IntelligenceItemId) IntelligenceItemId,Title,Subtitle,Category,Score,AttributesJson FROM cacsms.IntelligenceItems WHERE WorkspaceId=@workspace AND EngineSlug=N'scoring-engine' AND Score>=@threshold ORDER BY Score DESC`)).recordset;
    const existingTitles=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<{Title:string}>(`SELECT Title FROM cacsms.Opportunities WHERE WorkspaceId=@workspace AND IsArchived=0`)).recordset.map(row=>row.Title);
    for(const item of scored){const nearest=existingTitles.reduce((best,title)=>Math.max(best,similarity(item.Title,title)),0);if(nearest>=88){duplicates++;continue;}const attributes=parse(item.AttributesJson);const confidence=value(attributes,"confidence",item.Score);const demand=value(attributes,"demand",item.Score);const fit=value(attributes,"strategicFit",item.Score*.92);const readiness=value(attributes,"feasibility",item.Score*.82);const whitespace=value(attributes,"gap",item.Score);await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("title",sql.NVarChar(300),item.Title).input("subtitle",sql.NVarChar(400),item.Subtitle??"Autonomously ingested from adaptive scoring").input("category",sql.NVarChar(100),item.Category.slice(0,100)).input("value",sql.Decimal(18,2),Math.round(item.Score*250_000)).input("confidence",sql.TinyInt,Math.round(confidence)).input("score",sql.TinyInt,item.Score).input("demand",sql.TinyInt,Math.round(demand)).input("fit",sql.TinyInt,Math.round(fit)).input("readiness",sql.TinyInt,Math.round(readiness)).input("whitespace",sql.TinyInt,Math.round(whitespace)).query(`DECLARE @brand uniqueidentifier=(SELECT TOP(1) BrandId FROM cacsms.Brands WHERE WorkspaceId=@workspace AND IsActive=1); INSERT cacsms.Opportunities(WorkspaceId,BrandId,Title,Subtitle,Category,EstimatedValue,Confidence,Timing,OwnerName,OpportunityScore,Status,MarketDemand,StrategicFit,ExecutionReadiness,CompetitiveWhitespace,IsHighPriority,IsAtRisk) VALUES(@workspace,@brand,@title,@subtitle,@category,@value,@confidence,N'Autonomous cadence',N'Portfolio Autonomy Engine',@score,N'Autonomous enrichment',@demand,@fit,@readiness,@whitespace,CASE WHEN @score>=85 THEN 1 ELSE 0 END,0)`);existingTitles.push(item.Title);ingested++;}
    const opportunities=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Opportunity>(`SELECT CONVERT(nvarchar(36),OpportunityId) OpportunityId,Title,Category,Confidence,OpportunityScore,MarketDemand,StrategicFit,ExecutionReadiness,CompetitiveWhitespace,IsAtRisk FROM cacsms.Opportunities WHERE WorkspaceId=@workspace AND IsArchived=0 ORDER BY OpportunityScore DESC`)).recordset;
    const categoryCounts=new Map<string,number>();for(const opportunity of opportunities)categoryCounts.set(opportunity.Category,(categoryCounts.get(opportunity.Category)??0)+1);
    for(const opportunity of opportunities){const concentration=(categoryCounts.get(opportunity.Category)??1)/Math.max(1,opportunities.length)*100;const agreementValues=[opportunity.OpportunityScore,opportunity.Confidence,opportunity.MarketDemand,opportunity.StrategicFit,opportunity.ExecutionReadiness,opportunity.CompetitiveWhitespace];const mean=agreementValues.reduce((a,b)=>a+b,0)/agreementValues.length;const deviation=Math.sqrt(agreementValues.reduce((sum,current)=>sum+(current-mean)**2,0)/agreementValues.length);const decisionConfidence=round(opportunity.Confidence*.55+(100-deviation*2)*.3+Math.min(100,opportunities.length*8)*.15);const concentrationPenalty=Math.max(0,concentration-35)*.08;const riskPenalty=opportunity.IsAtRisk?12:0;const score=round(opportunity.OpportunityScore*.27+opportunity.Confidence*.2+opportunity.MarketDemand*.17+opportunity.StrategicFit*.15+opportunity.ExecutionReadiness*.1+opportunity.CompetitiveWhitespace*.11-concentrationPenalty-riskPenalty);const action=opportunity.IsAtRisk?"auto-risk-manage":score>=settings.PromoteThreshold?"auto-promote":score>=settings.PrioritizeThreshold?"auto-prioritize":"autonomous-enrichment";const status=action==="auto-risk-manage"?"Auto-risk-managed":action==="auto-promote"?"Auto-promoted":action==="auto-prioritize"?"Auto-prioritized":"Autonomous enrichment";const progress=Math.round(clamp(score*.5+decisionConfidence*.25+opportunity.ExecutionReadiness*.25));scores.push(score);confidences.push(decisionConfidence);if(action==="auto-promote")promoted++;if(action==="autonomous-enrichment")enriching++;await pool.request().input("id",sql.UniqueIdentifier,opportunity.OpportunityId).input("score",sql.TinyInt,Math.round(score)).input("confidence",sql.TinyInt,Math.round(decisionConfidence)).input("progress",sql.TinyInt,progress).input("status",sql.NVarChar(50),status).input("high",sql.Bit,action==="auto-promote").query(`UPDATE cacsms.Opportunities SET OpportunityScore=@score,Confidence=@confidence,ExecutionReadiness=@progress,Status=@status,OwnerName=N'Portfolio Autonomy Engine',Timing=N'Autonomous cadence',IsHighPriority=@high,UpdatedAt=SYSUTCDATETIME() WHERE OpportunityId=@id`);updated++;await pool.request().input("run",sql.UniqueIdentifier,runId).input("opportunity",sql.UniqueIdentifier,opportunity.OpportunityId).input("action",sql.NVarChar(60),action).input("score",sql.Decimal(5,2),score).input("confidence",sql.Decimal(5,2),decisionConfidence).input("rationale",sql.NVarChar(sql.MAX),JSON.stringify({algorithm:OPPORTUNITY_PORTFOLIO_ALGORITHM,concentration,concentrationPenalty,riskPenalty,signalAgreement:round(100-deviation*2),progress,humanInputRequired:false})).query(`INSERT cacsms.OpportunityPortfolioAutonomyDecisions(OpportunityPortfolioRunId,OpportunityId,Action,Score,Confidence,RationaleJson) VALUES(@run,@opportunity,@action,@score,@confidence,@rationale)`);}
    const portfolioScore=scores.length?round(scores.reduce((a,b)=>a+b,0)/scores.length):0;const averageConfidence=confidences.length?round(confidences.reduce((a,b)=>a+b,0)/confidences.length):0;await pool.request().input("run",sql.UniqueIdentifier,runId).input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("scanned",sql.Int,opportunities.length).input("ingested",sql.Int,ingested).input("updated",sql.Int,updated).input("promoted",sql.Int,promoted).input("enriching",sql.Int,enriching).input("duplicates",sql.Int,duplicates).input("score",sql.Decimal(5,2),portfolioScore).input("confidence",sql.Decimal(5,2),averageConfidence).input("interval",sql.Int,settings.RunIntervalSeconds).query(`UPDATE cacsms.OpportunityPortfolioAutonomyRuns SET Status=N'completed',CandidatesScanned=@scanned,RecordsIngested=@ingested,RecordsUpdated=@updated,RecordsPromoted=@promoted,RecordsEnriching=@enriching,DuplicatesSuppressed=@duplicates,PortfolioScore=@score,AverageConfidence=@confidence,CompletedAt=SYSUTCDATETIME() WHERE OpportunityPortfolioRunId=@run; UPDATE cacsms.OpportunityPortfolioAutonomySettings SET Enabled=1,LastRunAt=SYSUTCDATETIME(),NextRunAt=DATEADD(SECOND,@interval,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace`);return {runId,status:"completed",scanned:opportunities.length,ingested,updated,promoted,enriching,duplicates,portfolioScore,averageConfidence};
  }catch(error){const message=error instanceof Error?error.message:"Autonomous portfolio cycle failed";await pool.request().input("run",sql.UniqueIdentifier,runId).input("error",sql.NVarChar(1000),message.slice(0,1000)).query(`UPDATE cacsms.OpportunityPortfolioAutonomyRuns SET Status=N'failed',ErrorMessage=@error,CompletedAt=SYSUTCDATETIME() WHERE OpportunityPortfolioRunId=@run`);throw error;}
}
