import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";

export const MULTI_FORMAT_AUTONOMY_ALGORITHM="narrative-consistency-adaptation-orchestrator-v5";

type Settings={WorkspaceId:string;Enabled:boolean;RunIntervalSeconds:number;ReadyThreshold:number;OptimizeThreshold:number;MaximumRisk:number;MaxVariantsPerMaster:number;NextRunAt:Date|null};
type Master={ProductionId:string;Title:string;ProductionType:string;MetadataJson:string|null;UpdatedAt:Date};
type Variant={RecordId:string;MetadataJson:string|null};
type Spec={channel:string;format:string;effort:number;nativeFit:number};
export type MultiFormatCycleResult={runId:string;status:"completed"|"skipped";masters:number;generated:number;updated:number;ready:number;optimized:number;held:number;duplicates:number;channelCoverage:number;reuseEfficiency:number;adaptationQuality:number;averageConfidence:number};

const plannerGlobal=globalThis as typeof globalThis&{__multiFormatCycle?:Promise<MultiFormatCycleResult>};
const clamp=(value:number)=>Math.max(0,Math.min(100,Number.isFinite(value)?value:0));
const round=(value:number)=>Math.round(clamp(value)*10)/10;
function parse(value:string|null){try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
function numeric(metadata:Record<string,unknown>,key:string,fallback:number){const value=Number(metadata[key]);return Number.isFinite(value)?clamp(value):clamp(fallback);}
function sourceChannels(metadata:Record<string,unknown>){return Array.isArray(metadata.channels)?metadata.channels.map(String):[];}
function specifications(master:Master):Spec[]{
  const type=master.ProductionType.toLowerCase();
  if(type.includes("podcast"))return [{channel:"Podcast Feed",format:"Full Podcast Episode",effort:12,nativeFit:98},{channel:"YouTube",format:"Video Podcast",effort:26,nativeFit:91},{channel:"Website",format:"Evidence Transcript Article",effort:21,nativeFit:94},{channel:"LinkedIn",format:"Executive Audiogram",effort:30,nativeFit:89}];
  if(type.includes("social"))return [{channel:"Instagram",format:"Vertical Story Sequence",effort:16,nativeFit:97},{channel:"YouTube Shorts",format:"Vertical Short",effort:18,nativeFit:96},{channel:"LinkedIn",format:"Insight Carousel",effort:24,nativeFit:92},{channel:"Website",format:"Campaign Evidence Hub",effort:35,nativeFit:87}];
  if(type.includes("teaching"))return [{channel:"Learning Portal",format:"Adaptive Learning Module",effort:20,nativeFit:97},{channel:"YouTube",format:"Instructional Video",effort:17,nativeFit:95},{channel:"Website",format:"Learning Guide",effort:24,nativeFit:92},{channel:"LinkedIn",format:"Skills Carousel",effort:29,nativeFit:89}];
  return [{channel:"YouTube",format:type.includes("documentary")?"Documentary Feature":"Explainer Video",effort:15,nativeFit:96},{channel:"Website",format:"Evidence-led Article",effort:24,nativeFit:94},{channel:"LinkedIn",format:"Executive Insight Carousel",effort:29,nativeFit:92},{channel:"YouTube Shorts",format:"Vertical Insight Cut",effort:32,nativeFit:90}];
}

async function configuration(){const pool=await getMssqlPool();const result=await pool.request().query<Settings>(`SELECT TOP(1) s.* FROM cacsms.MultiFormatAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active' ORDER BY w.CreatedAt`);if(!result.recordset[0])throw new Error("Autonomous multi-format planning is not configured.");return {pool,settings:result.recordset[0]};}

export async function runAutonomousMultiFormatCycle(trigger="scheduler",force=false){
  if(plannerGlobal.__multiFormatCycle)return plannerGlobal.__multiFormatCycle;
  const operation=execute(trigger,force).finally(()=>{plannerGlobal.__multiFormatCycle=undefined;});plannerGlobal.__multiFormatCycle=operation;return operation;
}

async function execute(trigger:string,force:boolean):Promise<MultiFormatCycleResult>{
  const {pool,settings}=await configuration();
  const empty={runId:"",status:"skipped" as const,masters:0,generated:0,updated:0,ready:0,optimized:0,held:0,duplicates:0,channelCoverage:0,reuseEfficiency:0,adaptationQuality:0,averageConfidence:0};
  if(!settings.Enabled||(!force&&settings.NextRunAt&&settings.NextRunAt.getTime()>Date.now()))return empty;
  const started=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("trigger",sql.NVarChar(40),trigger.slice(0,40)).input("algorithm",sql.NVarChar(100),MULTI_FORMAT_AUTONOMY_ALGORITHM).query<{id:string}>(`INSERT cacsms.MultiFormatAutonomyRuns(WorkspaceId,TriggerSource,AlgorithmVersion,Status) OUTPUT CONVERT(nvarchar(36),inserted.MultiFormatAutonomyRunId) id VALUES(@workspace,@trigger,@algorithm,N'running')`);
  const runId=started.recordset[0].id;let generated=0,updated=0,ready=0,optimized=0,held=0,duplicates=0;const qualityScores:number[]=[];const confidenceScores:number[]=[];const reuseScores:number[]=[];const coveredChannels=new Set<string>();let expectedChannels=0;
  try{
    const masters=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Master>(`SELECT CONVERT(nvarchar(36),ProductionId) ProductionId,Title,ProductionType,MetadataJson,UpdatedAt FROM cacsms.Productions WHERE WorkspaceId=@workspace AND AutonomousSourceRecordId IS NOT NULL AND (Status=N'published' OR Stage=N'completed') ORDER BY UpdatedAt DESC`)).recordset;
    const existing=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Variant>(`SELECT CONVERT(nvarchar(36),RecordId) RecordId,MetadataJson FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'multi-format-planner'`)).recordset;
    const byKey=new Map<string,Variant>();for(const row of existing){const key=String(parse(row.MetadataJson).variantKey??"").toLowerCase();if(key){if(byKey.has(key))duplicates++;else byKey.set(key,row);}}
    for(const master of masters){
      const source=parse(master.MetadataJson);const sourceConfidence=numeric(source,"decisionConfidence",88);const readiness=numeric(source,"readiness",86);const sourceRisk=numeric(source,"risk",14);const evidence=numeric(source,"evidence",readiness);const audience=String(source.audience??"General and Professional Audiences");const originalChannels=sourceChannels(source);const specs=specifications(master).slice(0,Math.max(1,settings.MaxVariantsPerMaster));expectedChannels+=specs.length;
      for(const spec of specs){
        const variantKey=`${master.ProductionId}:${spec.channel}:${spec.format}`.toLowerCase();let record=byKey.get(variantKey);const alreadyNative=originalChannels.some(channel=>channel.toLowerCase()===spec.channel.toLowerCase());
        const narrativeConsistency=round(readiness*.34+sourceConfidence*.27+evidence*.24+(100-spec.effort)*.15);
        const channelFit=round(spec.nativeFit+(alreadyNative?3:0));
        const audienceFit=round(sourceConfidence*.28+readiness*.22+spec.nativeFit*.38+(audience.toLowerCase().includes("general")?7:10));
        const reuseScore=round(100-spec.effort*.58+(alreadyNative?5:0));
        const riskScore=round(sourceRisk*.38+(100-narrativeConsistency)*.28+(100-channelFit)*.2+(100-audienceFit)*.14);
        const decisionConfidence=round(sourceConfidence*.31+narrativeConsistency*.27+channelFit*.18+audienceFit*.14+evidence*.1);
        const adaptationScore=round(narrativeConsistency*.3+channelFit*.25+audienceFit*.18+reuseScore*.17+decisionConfidence*.1-riskScore*.12);
        const action=riskScore>settings.MaximumRisk?"auto-hold-risk":adaptationScore>=settings.OptimizeThreshold?"auto-optimize-and-route":adaptationScore>=settings.ReadyThreshold?"auto-ready-and-route":"autonomous-adapt";
        const status=action==="auto-hold-risk"?"Auto-held by risk":action==="auto-optimize-and-route"?"Auto-optimized":action==="auto-ready-and-route"?"Auto-ready":"Autonomous adapting";
        const progress=action==="auto-hold-risk"?0:action==="auto-optimize-and-route"?100:action==="auto-ready-and-route"?92:Math.max(35,Math.round(adaptationScore));
        const title=`${master.Title} — ${spec.format}`.slice(0,300);const description=`Autonomously adapted from “${master.Title}” for ${spec.channel}; narrative, evidence, audience, and channel constraints are continuously optimized.`.slice(0,1000);
        const rationale={algorithm:MULTI_FORMAT_AUTONOMY_ALGORITHM,variantKey,sourceProductionId:master.ProductionId,masterTitle:master.Title,masterFormat:master.ProductionType,targetChannel:spec.channel,selectedFormat:spec.format,audience,narrativeConsistency,channelFit,audienceFit,reuseScore,riskScore,adaptationScore,decisionConfidence,action,humanInputRequired:false};
        if(!record){const inserted=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),spec.channel).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(adaptationScore)).input("progress",sql.TinyInt,progress).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query<{RecordId:string}>(`INSERT cacsms.OpportunityOperationalRecords(WorkspaceId,PageSlug,RecordType,Title,Description,Category,Status,OwnerName,Score,Progress,StartAt,MetadataJson) OUTPUT CONVERT(nvarchar(36),inserted.RecordId) RecordId VALUES(@workspace,N'multi-format-planner',N'autonomous-format-variant',@title,@description,@category,@status,N'Multi-Format Autonomy Engine',@score,@progress,SYSUTCDATETIME(),@metadata)`);record={RecordId:inserted.recordset[0].RecordId,MetadataJson:JSON.stringify(rationale)};byKey.set(variantKey,record);generated++;}
        else{await pool.request().input("record",sql.UniqueIdentifier,record.RecordId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),spec.channel).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(adaptationScore)).input("progress",sql.TinyInt,progress).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`UPDATE cacsms.OpportunityOperationalRecords SET Title=@title,Description=@description,Category=@category,Status=@status,OwnerName=N'Multi-Format Autonomy Engine',Score=@score,Progress=@progress,MetadataJson=@metadata,UpdatedAt=SYSUTCDATETIME() WHERE RecordId=@record`);updated++;}
        await pool.request().input("run",sql.UniqueIdentifier,runId).input("record",sql.UniqueIdentifier,record.RecordId).input("source",sql.UniqueIdentifier,master.ProductionId).input("action",sql.NVarChar(60),action).input("adaptation",sql.Decimal(5,2),adaptationScore).input("consistency",sql.Decimal(5,2),narrativeConsistency).input("channelFit",sql.Decimal(5,2),channelFit).input("audienceFit",sql.Decimal(5,2),audienceFit).input("reuse",sql.Decimal(5,2),reuseScore).input("risk",sql.Decimal(5,2),riskScore).input("confidence",sql.Decimal(5,2),decisionConfidence).input("format",sql.NVarChar(100),spec.format).input("channel",sql.NVarChar(100),spec.channel).input("rationale",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`INSERT cacsms.MultiFormatAutonomyDecisions(MultiFormatAutonomyRunId,RecordId,SourceProductionId,Action,AdaptationScore,NarrativeConsistency,ChannelFit,AudienceFit,ReuseScore,RiskScore,Confidence,SelectedFormat,TargetChannel,RationaleJson) VALUES(@run,@record,@source,@action,@adaptation,@consistency,@channelFit,@audienceFit,@reuse,@risk,@confidence,@format,@channel,@rationale)`);
        coveredChannels.add(`${master.ProductionId}:${spec.channel}`);qualityScores.push(adaptationScore);confidenceScores.push(decisionConfidence);reuseScores.push(reuseScore);if(action==="auto-optimize-and-route")optimized++;else if(action==="auto-ready-and-route")ready++;else if(action==="auto-hold-risk")held++;
      }
    }
    const average=(values:number[])=>values.length?round(values.reduce((a,b)=>a+b,0)/values.length):0;const channelCoverage=expectedChannels?round(coveredChannels.size/expectedChannels*100):0;const reuseEfficiency=average(reuseScores);const adaptationQuality=average(qualityScores);const averageConfidence=average(confidenceScores);
    await pool.request().input("run",sql.UniqueIdentifier,runId).input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("masters",sql.Int,masters.length).input("generated",sql.Int,generated).input("updated",sql.Int,updated).input("ready",sql.Int,ready).input("optimized",sql.Int,optimized).input("held",sql.Int,held).input("duplicates",sql.Int,duplicates).input("coverage",sql.Decimal(5,2),channelCoverage).input("reuse",sql.Decimal(5,2),reuseEfficiency).input("quality",sql.Decimal(5,2),adaptationQuality).input("confidence",sql.Decimal(5,2),averageConfidence).input("interval",sql.Int,settings.RunIntervalSeconds).query(`UPDATE cacsms.MultiFormatAutonomyRuns SET Status=N'completed',MastersScanned=@masters,VariantsGenerated=@generated,VariantsUpdated=@updated,VariantsReady=@ready,VariantsOptimized=@optimized,VariantsHeld=@held,DuplicatesSuppressed=@duplicates,ChannelCoverage=@coverage,ReuseEfficiency=@reuse,AverageAdaptationQuality=@quality,AverageConfidence=@confidence,CompletedAt=SYSUTCDATETIME() WHERE MultiFormatAutonomyRunId=@run;UPDATE cacsms.MultiFormatAutonomySettings SET Enabled=1,LastRunAt=SYSUTCDATETIME(),NextRunAt=DATEADD(SECOND,@interval,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace`);
    return {runId,status:"completed",masters:masters.length,generated,updated,ready,optimized,held,duplicates,channelCoverage,reuseEfficiency,adaptationQuality,averageConfidence};
  }catch(error){const message=error instanceof Error?error.message:"Autonomous multi-format cycle failed";await pool.request().input("run",sql.UniqueIdentifier,runId).input("error",sql.NVarChar(1000),message.slice(0,1000)).query(`UPDATE cacsms.MultiFormatAutonomyRuns SET Status=N'failed',ErrorMessage=@error,CompletedAt=SYSUTCDATETIME() WHERE MultiFormatAutonomyRunId=@run`);throw error;}
}
