import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";

export const TEMPLATE_AUTONOMY_ALGORITHM="adaptive-template-intelligence-orchestrator-v5";
type Settings={WorkspaceId:string;Enabled:boolean;RunIntervalSeconds:number;ApproveThreshold:number;RefreshThreshold:number;MaximumRisk:number;NextRunAt:Date|null};
type Production={ProductionId:string;Title:string;ProductionType:string;MetadataJson:string|null};
type Existing={RecordId:string;MetadataJson:string|null;Status:string};
type Structure={ProductionId:string;Quality:number;Confidence:number;Mode:string};
export type TemplateCycleResult={runId:string;status:"completed"|"skipped";scanned:number;generated:number;updated:number;approved:number;refreshing:number;retired:number;duplicates:number;averageFit:number;averageReuse:number;averageConfidence:number};
const templateGlobal=globalThis as typeof globalThis&{__templateCycle?:Promise<TemplateCycleResult>};
const clamp=(value:number)=>Math.max(0,Math.min(100,Number.isFinite(value)?value:0));const round=(value:number)=>Math.round(clamp(value)*10)/10;
function parse(value:string|null){try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
function numeric(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)?clamp(n):clamp(fallback);}
function templateName(type:string){const t=type.toLowerCase();if(/documentary/.test(t))return "Evidence Documentary Master";if(/teaching|course|lesson/.test(t))return "Adaptive Learning Master";if(/podcast|interview/.test(t))return "Expert Conversation Master";if(/social|short/.test(t))return "Vertical Social Master";if(/marketing|campaign/.test(t))return "Evidence Campaign Master";if(/corporate|business/.test(t))return "Executive Briefing Master";return "Adaptive Explainer Master";}
function templateFamily(type:string){const t=type.toLowerCase();return /teaching|course|lesson|education/.test(t)?"learning":/marketing|campaign|corporate|business/.test(t)?"hybrid":"narrative";}
async function configuration(){const pool=await getMssqlPool();const result=await pool.request().query<Settings>(`SELECT TOP(1) s.* FROM cacsms.TemplateAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active' ORDER BY w.CreatedAt`);if(!result.recordset[0])throw new Error("Autonomous template intelligence is not configured.");return {pool,settings:result.recordset[0]};}
export async function runAutonomousTemplateCycle(trigger="scheduler",force=false){if(templateGlobal.__templateCycle)return templateGlobal.__templateCycle;const operation=execute(trigger,force).finally(()=>{templateGlobal.__templateCycle=undefined;});templateGlobal.__templateCycle=operation;return operation;}
async function execute(trigger:string,force:boolean):Promise<TemplateCycleResult>{
  const {pool,settings}=await configuration();const empty={runId:"",status:"skipped" as const,scanned:0,generated:0,updated:0,approved:0,refreshing:0,retired:0,duplicates:0,averageFit:0,averageReuse:0,averageConfidence:0};if(!settings.Enabled||(!force&&settings.NextRunAt&&settings.NextRunAt.getTime()>Date.now()))return empty;
  const started=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("trigger",sql.NVarChar(40),trigger.slice(0,40)).input("algorithm",sql.NVarChar(100),TEMPLATE_AUTONOMY_ALGORITHM).query<{id:string}>(`INSERT cacsms.TemplateAutonomyRuns(WorkspaceId,TriggerSource,AlgorithmVersion,Status) OUTPUT CONVERT(nvarchar(36),inserted.TemplateAutonomyRunId) id VALUES(@workspace,@trigger,@algorithm,N'running')`);const runId=started.recordset[0].id;
  let generated=0,updated=0,approved=0,refreshing=0,retired=0,duplicates=0;const fits:number[]=[];const reuses:number[]=[];const confidences:number[]=[];
  try{
    const productions=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Production>(`SELECT CONVERT(nvarchar(36),ProductionId) ProductionId,Title,ProductionType,MetadataJson FROM cacsms.Productions WHERE WorkspaceId=@workspace AND AutonomousSourceRecordId IS NOT NULL AND (Status=N'published' OR Stage=N'completed') ORDER BY UpdatedAt DESC`)).recordset;
    const structures=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Structure>(`SELECT CONVERT(nvarchar(36),ProductionId) ProductionId,CONVERT(float,CoherenceScore*.29+PedagogyScore*.22+EngagementScore*.22+KnowledgeAlignment*.27) Quality,CONVERT(float,Confidence) Confidence,StructureMode Mode FROM cacsms.StoryStructures WHERE WorkspaceId=@workspace`)).recordset;const structureMap=new Map(structures.map(row=>[row.ProductionId.toLowerCase(),row]));
    const evergreen=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<{count:number;reuse:number}>(`SELECT COUNT(*) count,ISNULL(AVG(CONVERT(float,Score)),0) reuse FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'evergreen-knowledge-bank' AND Status=N'Auto-certified Evergreen'`)).recordset[0];
    const existing=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Existing>(`SELECT CONVERT(nvarchar(36),RecordId) RecordId,MetadataJson,Status FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'template-dashboard'`)).recordset;const byKey=new Map<string,Existing>();for(const row of existing){const key=String(parse(row.MetadataJson).templateKey??"").toLowerCase();if(key){if(byKey.has(key))duplicates++;else byKey.set(key,row);}}
    const groups=new Map<string,Production>();for(const production of productions){const key=production.ProductionType.toLowerCase();if(!groups.has(key))groups.set(key,production);}
    for(const [key,production] of groups){const source=parse(production.MetadataJson);const structure=structureMap.get(production.ProductionId.toLowerCase());const readiness=numeric(source.readiness,86);const sourceConfidence=numeric(source.decisionConfidence,88);const quality=numeric(structure?.Quality,readiness);const confidence=numeric(structure?.Confidence,sourceConfidence);const evergreenReuse=numeric(evergreen?.reuse,82);const coverage=clamp(Number(evergreen?.count??0)/Math.max(1,productions.length)*100);const templateFit=round(readiness*.24+quality*.28+confidence*.2+evergreenReuse*.18+coverage*.1);const reuseScore=round(evergreenReuse*.45+quality*.25+templateFit*.2+coverage*.1);const driftScore=round((100-quality)*.45+(100-confidence)*.3+(100-coverage)*.25);const riskScore=round((100-templateFit)*.45+(100-confidence)*.3+driftScore*.25);const action=riskScore>settings.MaximumRisk?"auto-retire-risk":driftScore>settings.RefreshThreshold?"auto-refresh-version":templateFit>=settings.ApproveThreshold?"auto-approve-template":"autonomous-refine";const status=action==="auto-retire-risk"?"Auto-retired by risk":action==="auto-refresh-version"?"Autonomous refreshing":action==="auto-approve-template"?"Auto-approved Template":"Autonomous refining";let current=byKey.get(key);const priorMeta=parse(current?.MetadataJson??null);const version=Math.max(1,Number(priorMeta.version??0)+(action==="auto-refresh-version"&&current?.Status!=="Autonomous refreshing"?1:0));const rationale={algorithm:TEMPLATE_AUTONOMY_ALGORITHM,templateKey:key,templateName:templateName(production.ProductionType),templateFamily:templateFamily(production.ProductionType),productionType:production.ProductionType,sourceProductionId:production.ProductionId,sourceStructureMode:structure?.Mode??"narrative",version,templateFit,reuseScore,driftScore,riskScore,confidence,evergreenAssets:Number(evergreen?.count??0),action,humanInputRequired:false};const title=`${templateName(production.ProductionType)} v${version}`;const description=`Autonomously selected for ${production.ProductionType}; fit, structure coherence, evergreen coverage, reuse potential, and drift are continuously evaluated.`;
      let recordId=current?.RecordId;if(!recordId){const inserted=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),production.ProductionType).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(templateFit)).input("progress",sql.TinyInt,action==="auto-approve-template"?100:action==="auto-retire-risk"?0:82).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query<{RecordId:string}>(`INSERT cacsms.OpportunityOperationalRecords(WorkspaceId,PageSlug,RecordType,Title,Description,Category,Status,OwnerName,Score,Progress,StartAt,MetadataJson) OUTPUT CONVERT(nvarchar(36),inserted.RecordId) RecordId VALUES(@workspace,N'template-dashboard',N'autonomous-template',@title,@description,@category,@status,N'Template Autonomy Engine',@score,@progress,SYSUTCDATETIME(),@metadata)`);recordId=inserted.recordset[0].RecordId;generated++;}else{await pool.request().input("record",sql.UniqueIdentifier,recordId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),production.ProductionType).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(templateFit)).input("progress",sql.TinyInt,action==="auto-approve-template"?100:action==="auto-retire-risk"?0:82).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`UPDATE cacsms.OpportunityOperationalRecords SET Title=@title,Description=@description,Category=@category,Status=@status,OwnerName=N'Template Autonomy Engine',Score=@score,Progress=@progress,MetadataJson=@metadata,UpdatedAt=SYSUTCDATETIME() WHERE RecordId=@record`);updated++;}
      await pool.request().input("run",sql.UniqueIdentifier,runId).input("record",sql.UniqueIdentifier,recordId).input("production",sql.UniqueIdentifier,production.ProductionId).input("action",sql.NVarChar(60),action).input("key",sql.NVarChar(120),key).input("version",sql.Int,version).input("fit",sql.Decimal(5,2),templateFit).input("reuse",sql.Decimal(5,2),reuseScore).input("drift",sql.Decimal(5,2),driftScore).input("risk",sql.Decimal(5,2),riskScore).input("confidence",sql.Decimal(5,2),confidence).input("rationale",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`INSERT cacsms.TemplateAutonomyDecisions(TemplateAutonomyRunId,OperationalRecordId,ProductionId,Action,TemplateKey,VersionNumber,TemplateFit,ReuseScore,DriftScore,RiskScore,Confidence,RationaleJson) VALUES(@run,@record,@production,@action,@key,@version,@fit,@reuse,@drift,@risk,@confidence,@rationale)`);if(action==="auto-approve-template")approved++;else if(action==="auto-refresh-version")refreshing++;else if(action==="auto-retire-risk")retired++;fits.push(templateFit);reuses.push(reuseScore);confidences.push(confidence);
    }
    const average=(values:number[])=>values.length?round(values.reduce((a,b)=>a+b,0)/values.length):0;const averageFit=average(fits),averageReuse=average(reuses),averageConfidence=average(confidences);await pool.request().input("run",sql.UniqueIdentifier,runId).input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("scanned",sql.Int,productions.length).input("generated",sql.Int,generated).input("updated",sql.Int,updated).input("approved",sql.Int,approved).input("refreshing",sql.Int,refreshing).input("retired",sql.Int,retired).input("duplicates",sql.Int,duplicates).input("fit",sql.Decimal(5,2),averageFit).input("reuse",sql.Decimal(5,2),averageReuse).input("confidence",sql.Decimal(5,2),averageConfidence).input("interval",sql.Int,settings.RunIntervalSeconds).query(`UPDATE cacsms.TemplateAutonomyRuns SET Status=N'completed',ProductionsScanned=@scanned,TemplatesGenerated=@generated,TemplatesUpdated=@updated,TemplatesApproved=@approved,TemplatesRefreshing=@refreshing,TemplatesRetired=@retired,DuplicatesSuppressed=@duplicates,AverageFit=@fit,AverageReuse=@reuse,AverageConfidence=@confidence,CompletedAt=SYSUTCDATETIME() WHERE TemplateAutonomyRunId=@run;UPDATE cacsms.TemplateAutonomySettings SET Enabled=1,LastRunAt=SYSUTCDATETIME(),NextRunAt=DATEADD(SECOND,@interval,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace`);return {runId,status:"completed",scanned:productions.length,generated,updated,approved,refreshing,retired,duplicates,averageFit,averageReuse,averageConfidence};
  }catch(error){const message=error instanceof Error?error.message:"Autonomous template cycle failed";await pool.request().input("run",sql.UniqueIdentifier,runId).input("error",sql.NVarChar(1000),message.slice(0,1000)).query(`UPDATE cacsms.TemplateAutonomyRuns SET Status=N'failed',ErrorMessage=@error,CompletedAt=SYSUTCDATETIME() WHERE TemplateAutonomyRunId=@run`);throw error;}
}
