import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";

export const CAMPAIGN_AUTONOMY_ALGORITHM="multi-objective-campaign-orchestrator-v6";
type Settings={WorkspaceId:string;Enabled:boolean;RunIntervalSeconds:number;ScheduleThreshold:number;LaunchThreshold:number;MaximumRisk:number;NextRunAt:Date|null};
type Asset={RecordId:string;Title:string;Description:string|null;Category:string|null;Status:string;Score:number;Progress:number;MetadataJson:string|null;UpdatedAt:Date};
type Existing={RecordId:string;MetadataJson:string|null};
export type CampaignCycleResult={runId:string;status:"completed"|"skipped";scanned:number;campaigns:number;generated:number;updated:number;scheduled:number;launched:number;held:number;duplicates:number;projectedReach:number;budgetAllocated:number;launchReadiness:number;averageConfidence:number};

const campaignGlobal=globalThis as typeof globalThis&{__campaignCycle?:Promise<CampaignCycleResult>};
const clamp=(value:number)=>Math.max(0,Math.min(100,Number.isFinite(value)?value:0));
const round=(value:number)=>Math.round(clamp(value)*10)/10;
function parse(value:string|null){try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
function numeric(metadata:Record<string,unknown>,key:string,fallback:number){const value=Number(metadata[key]);return Number.isFinite(value)?clamp(value):clamp(fallback);}
function wave(channel:string){const value=channel.toLowerCase();if(/short|instagram/.test(value))return {name:"Tease",offset:0};if(/linkedin/.test(value))return {name:"Educate",offset:1};if(/website/.test(value))return {name:"Deep Dive",offset:2};if(/learning/.test(value))return {name:"Deepen",offset:3};return {name:"Sustain",offset:4};}
function channelPotential(channel:string){const value=channel.toLowerCase();if(value.includes("youtube shorts"))return 480000;if(value.includes("youtube"))return 360000;if(value.includes("instagram"))return 420000;if(value.includes("linkedin"))return 190000;if(value.includes("website"))return 140000;if(value.includes("learning"))return 85000;return 100000;}
function objective(title:string){const text=title.toLowerCase();if(/training|skills|learning|education/.test(text))return "Build qualified learning demand and measurable capability adoption";if(/procurement|market|demand|growth/.test(text))return "Convert evidence-backed demand into high-intent market action";if(/governance|risk|cyber|security/.test(text))return "Build trusted executive awareness and accelerate governed adoption";return "Expand qualified awareness and move priority audiences toward adoption";}

async function configuration(){const pool=await getMssqlPool();const result=await pool.request().query<Settings>(`SELECT TOP(1) s.* FROM cacsms.CampaignAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active' ORDER BY w.CreatedAt`);if(!result.recordset[0])throw new Error("Autonomous campaign building is not configured.");return {pool,settings:result.recordset[0]};}
export async function runAutonomousCampaignCycle(trigger="scheduler",force=false){if(campaignGlobal.__campaignCycle)return campaignGlobal.__campaignCycle;const operation=execute(trigger,force).finally(()=>{campaignGlobal.__campaignCycle=undefined;});campaignGlobal.__campaignCycle=operation;return operation;}

async function execute(trigger:string,force:boolean):Promise<CampaignCycleResult>{
  const {pool,settings}=await configuration();const empty={runId:"",status:"skipped" as const,scanned:0,campaigns:0,generated:0,updated:0,scheduled:0,launched:0,held:0,duplicates:0,projectedReach:0,budgetAllocated:0,launchReadiness:0,averageConfidence:0};if(!settings.Enabled||(!force&&settings.NextRunAt&&settings.NextRunAt.getTime()>Date.now()))return empty;
  const started=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("trigger",sql.NVarChar(40),trigger.slice(0,40)).input("algorithm",sql.NVarChar(100),CAMPAIGN_AUTONOMY_ALGORITHM).query<{id:string}>(`INSERT cacsms.CampaignAutonomyRuns(WorkspaceId,TriggerSource,AlgorithmVersion,Status) OUTPUT CONVERT(nvarchar(36),inserted.CampaignAutonomyRunId) id VALUES(@workspace,@trigger,@algorithm,N'running')`);const runId=started.recordset[0].id;
  let generated=0,updated=0,scheduled=0,launched=0,held=0,duplicates=0,projectedReach=0,budgetAllocated=0;const readinessScores:number[]=[];const confidenceScores:number[]=[];
  try{
    const assets=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Asset>(`SELECT CONVERT(nvarchar(36),RecordId) RecordId,Title,Description,Category,Status,ISNULL(Score,0) Score,ISNULL(Progress,0) Progress,MetadataJson,UpdatedAt FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'multi-format-planner' AND Status IN(N'Auto-ready',N'Auto-optimized') ORDER BY UpdatedAt DESC`)).recordset;
    const existing=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Existing>(`SELECT CONVERT(nvarchar(36),RecordId) RecordId,MetadataJson FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'campaign-builder'`)).recordset;
    const bySource=new Map<string,Existing>();for(const row of existing){const source=String(parse(row.MetadataJson).sourceFormatRecordId??"").toLowerCase();if(source){if(bySource.has(source))duplicates++;else bySource.set(source,row);}}
    const campaignKeys=new Set<string>();const channelCounts=new Map<string,number>();for(const asset of assets){const channel=asset.Category||"Owned Channel";channelCounts.set(channel,(channelCounts.get(channel)??0)+1);}
    for(const asset of assets){
      const metadata=parse(asset.MetadataJson);const sourceProductionId=String(metadata.sourceProductionId??"");if(!sourceProductionId)continue;campaignKeys.add(sourceProductionId.toLowerCase());const channel=String(metadata.targetChannel??asset.Category??"Owned Channel");const format=String(metadata.selectedFormat??asset.Title);const masterTitle=String(metadata.masterTitle??asset.Title);const audience=String(metadata.audience??"Priority professional audiences");const sequence=wave(channel);
      const adaptation=numeric(metadata,"adaptationScore",asset.Score);const consistency=numeric(metadata,"narrativeConsistency",asset.Score);const channelFit=numeric(metadata,"channelFit",asset.Score);const sourceConfidence=numeric(metadata,"decisionConfidence",asset.Score);const reuse=numeric(metadata,"reuseScore",asset.Progress);const audienceFit=round(sourceConfidence*.3+channelFit*.32+consistency*.23+(audience.length>8?15:8));const diversityBonus=round(Math.min(100,(channelCounts.size/5)*100));const channelSynergy=round(channelFit*.58+diversityBonus*.22+consistency*.2);const freshness=round(100-Math.max(0,(Date.now()-new Date(asset.UpdatedAt).getTime())/86_400_000)*2);const riskScore=round((100-consistency)*.32+(100-audienceFit)*.23+(100-channelSynergy)*.2+(100-sourceConfidence)*.15+(100-freshness)*.1);const launchReadiness=round(adaptation*.24+consistency*.2+channelSynergy*.19+audienceFit*.17+sourceConfidence*.12+reuse*.08-riskScore*.1);const decisionConfidence=round(sourceConfidence*.38+consistency*.25+audienceFit*.2+channelSynergy*.17);
      const action=riskScore>settings.MaximumRisk?"auto-hold-risk":launchReadiness>=settings.LaunchThreshold?"auto-launch":launchReadiness>=settings.ScheduleThreshold?"auto-schedule":"autonomous-optimize";const status=action==="auto-hold-risk"?"Auto-held by risk":action==="auto-launch"?"Auto-launched":action==="auto-schedule"?"Auto-scheduled":"Autonomous optimizing";const progress=action==="auto-launch"?100:action==="auto-schedule"?92:action==="auto-hold-risk"?0:Math.max(40,Math.round(launchReadiness));
      const reach=Math.round(channelPotential(channel)*(launchReadiness/100)*(audienceFit/100)*(1-riskScore/100));const cpm=/short|instagram/i.test(channel)?7.5:/youtube/i.test(channel)?9.5:/linkedin/i.test(channel)?13:/website/i.test(channel)?5.5:8;const budget=Math.round(reach/1000*cpm*100)/100;const startAt=new Date(Date.now()+sequence.offset*86_400_000);const dueAt=new Date(startAt.getTime()+2*86_400_000);const campaignKey=sourceProductionId.toLowerCase();const title=`${masterTitle} — ${channel} campaign asset`.slice(0,300);const description=`${objective(masterTitle)}. ${format} is autonomously sequenced in the ${sequence.name} wave for ${audience}.`.slice(0,1000);const rationale={algorithm:CAMPAIGN_AUTONOMY_ALGORITHM,campaignKey,sourceFormatRecordId:asset.RecordId,sourceProductionId,masterTitle,objective:objective(masterTitle),audience,targetChannel:channel,format,wave:sequence.name,waveOffsetDays:sequence.offset,adaptationScore:adaptation,narrativeConsistency:consistency,audienceFit,channelSynergy,reuseScore:reuse,riskScore,launchReadiness,decisionConfidence,projectedReach:reach,budgetAllocation:budget,action,humanInputRequired:false};
      let record=bySource.get(asset.RecordId.toLowerCase());if(!record){const inserted=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),channel).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(launchReadiness)).input("progress",sql.TinyInt,progress).input("amount",sql.Decimal(18,2),budget).input("start",sql.DateTimeOffset,startAt).input("due",sql.DateTimeOffset,dueAt).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query<{RecordId:string}>(`INSERT cacsms.OpportunityOperationalRecords(WorkspaceId,PageSlug,RecordType,Title,Description,Category,Status,OwnerName,Score,Progress,Amount,StartAt,DueAt,MetadataJson) OUTPUT CONVERT(nvarchar(36),inserted.RecordId) RecordId VALUES(@workspace,N'campaign-builder',N'autonomous-campaign-asset',@title,@description,@category,@status,N'Campaign Autonomy Engine',@score,@progress,@amount,@start,@due,@metadata)`);record={RecordId:inserted.recordset[0].RecordId,MetadataJson:JSON.stringify(rationale)};bySource.set(asset.RecordId.toLowerCase(),record);generated++;}else{await pool.request().input("record",sql.UniqueIdentifier,record.RecordId).input("title",sql.NVarChar(300),title).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),channel).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(launchReadiness)).input("progress",sql.TinyInt,progress).input("amount",sql.Decimal(18,2),budget).input("start",sql.DateTimeOffset,startAt).input("due",sql.DateTimeOffset,dueAt).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`UPDATE cacsms.OpportunityOperationalRecords SET Title=@title,Description=@description,Category=@category,Status=@status,OwnerName=N'Campaign Autonomy Engine',Score=@score,Progress=@progress,Amount=@amount,StartAt=@start,DueAt=@due,MetadataJson=@metadata,UpdatedAt=SYSUTCDATETIME() WHERE RecordId=@record`);updated++;}
      await pool.request().input("run",sql.UniqueIdentifier,runId).input("record",sql.UniqueIdentifier,record.RecordId).input("source",sql.UniqueIdentifier,asset.RecordId).input("action",sql.NVarChar(60),action).input("campaign",sql.NVarChar(100),campaignKey).input("wave",sql.NVarChar(40),sequence.name).input("readiness",sql.Decimal(5,2),launchReadiness).input("audience",sql.Decimal(5,2),audienceFit).input("synergy",sql.Decimal(5,2),channelSynergy).input("risk",sql.Decimal(5,2),riskScore).input("confidence",sql.Decimal(5,2),decisionConfidence).input("reach",sql.BigInt,reach).input("budget",sql.Decimal(18,2),budget).input("rationale",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`INSERT cacsms.CampaignAutonomyDecisions(CampaignAutonomyRunId,RecordId,SourceFormatRecordId,Action,CampaignKey,WaveName,LaunchReadiness,AudienceFit,ChannelSynergy,RiskScore,Confidence,ProjectedReach,BudgetAllocation,RationaleJson) VALUES(@run,@record,@source,@action,@campaign,@wave,@readiness,@audience,@synergy,@risk,@confidence,@reach,@budget,@rationale)`);
      if(action==="auto-launch")launched++;else if(action==="auto-schedule")scheduled++;else if(action==="auto-hold-risk")held++;projectedReach+=reach;budgetAllocated+=budget;readinessScores.push(launchReadiness);confidenceScores.push(decisionConfidence);
    }
    const average=(values:number[])=>values.length?round(values.reduce((a,b)=>a+b,0)/values.length):0;const launchReadiness=average(readinessScores);const averageConfidence=average(confidenceScores);budgetAllocated=Math.round(budgetAllocated*100)/100;
    await pool.request().input("run",sql.UniqueIdentifier,runId).input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("scanned",sql.Int,assets.length).input("campaigns",sql.Int,campaignKeys.size).input("generated",sql.Int,generated).input("updated",sql.Int,updated).input("scheduled",sql.Int,scheduled).input("launched",sql.Int,launched).input("held",sql.Int,held).input("duplicates",sql.Int,duplicates).input("reach",sql.BigInt,projectedReach).input("budget",sql.Decimal(18,2),budgetAllocated).input("readiness",sql.Decimal(5,2),launchReadiness).input("confidence",sql.Decimal(5,2),averageConfidence).input("interval",sql.Int,settings.RunIntervalSeconds).query(`UPDATE cacsms.CampaignAutonomyRuns SET Status=N'completed',AssetsScanned=@scanned,CampaignsPlanned=@campaigns,AssetsGenerated=@generated,AssetsUpdated=@updated,AssetsScheduled=@scheduled,AssetsLaunched=@launched,AssetsHeld=@held,DuplicatesSuppressed=@duplicates,ProjectedReach=@reach,BudgetAllocated=@budget,AverageLaunchReadiness=@readiness,AverageConfidence=@confidence,CompletedAt=SYSUTCDATETIME() WHERE CampaignAutonomyRunId=@run;UPDATE cacsms.CampaignAutonomySettings SET Enabled=1,LastRunAt=SYSUTCDATETIME(),NextRunAt=DATEADD(SECOND,@interval,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace`);
    return {runId,status:"completed",scanned:assets.length,campaigns:campaignKeys.size,generated,updated,scheduled,launched,held,duplicates,projectedReach,budgetAllocated,launchReadiness,averageConfidence};
  }catch(error){const message=error instanceof Error?error.message:"Autonomous campaign cycle failed";await pool.request().input("run",sql.UniqueIdentifier,runId).input("error",sql.NVarChar(1000),message.slice(0,1000)).query(`UPDATE cacsms.CampaignAutonomyRuns SET Status=N'failed',ErrorMessage=@error,CompletedAt=SYSUTCDATETIME() WHERE CampaignAutonomyRunId=@run`);throw error;}
}
