import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";

export const EVERGREEN_AUTONOMY_ALGORITHM="evergreen-retention-reuse-orchestrator-v5";
type Settings={WorkspaceId:string;Enabled:boolean;RunIntervalSeconds:number;CertifyThreshold:number;RefreshThreshold:number;MaximumRisk:number;NextRunAt:Date|null};
type Knowledge={KnowledgeRecordId:string;RecordType:string;Title:string;Summary:string;Status:string;Source:string;Confidence:number;QualityScore:number;MetadataJson:string|null;UpdatedAt:Date};
type Existing={RecordId:string;MetadataJson:string|null};
export type EvergreenCycleResult={runId:string;status:"completed"|"skipped";scanned:number;generated:number;updated:number;certified:number;refreshQueued:number;duplicates:number;held:number;averageFreshness:number;averageReuseReadiness:number;averageConfidence:number};
const evergreenGlobal=globalThis as typeof globalThis&{__evergreenCycle?:Promise<EvergreenCycleResult>};
const clamp=(value:number)=>Math.max(0,Math.min(100,Number.isFinite(value)?value:0));const round=(value:number)=>Math.round(clamp(value)*10)/10;
function parse(value:string|null){try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}}
function normalized(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function numeric(value:number,fallback:number){return Number.isFinite(Number(value))?clamp(Number(value)):clamp(fallback);}
function reusePotential(type:string){const value=type.toLowerCase();if(/guide|manual|report|dataset|reference/.test(value))return 96;if(/course|lesson|tutorial|educational/.test(value))return 93;if(/case|article|research/.test(value))return 88;return 82;}
async function configuration(){const pool=await getMssqlPool();const result=await pool.request().query<Settings>(`SELECT TOP(1) s.* FROM cacsms.EvergreenAutonomySettings s JOIN cacsms.Workspaces w ON w.WorkspaceId=s.WorkspaceId WHERE w.Status=N'active' ORDER BY w.CreatedAt`);if(!result.recordset[0])throw new Error("Autonomous evergreen knowledge is not configured.");return {pool,settings:result.recordset[0]};}
export async function runAutonomousEvergreenCycle(trigger="scheduler",force=false){if(evergreenGlobal.__evergreenCycle)return evergreenGlobal.__evergreenCycle;const operation=execute(trigger,force).finally(()=>{evergreenGlobal.__evergreenCycle=undefined;});evergreenGlobal.__evergreenCycle=operation;return operation;}
async function execute(trigger:string,force:boolean):Promise<EvergreenCycleResult>{
  const {pool,settings}=await configuration();const empty={runId:"",status:"skipped" as const,scanned:0,generated:0,updated:0,certified:0,refreshQueued:0,duplicates:0,held:0,averageFreshness:0,averageReuseReadiness:0,averageConfidence:0};if(!settings.Enabled||(!force&&settings.NextRunAt&&settings.NextRunAt.getTime()>Date.now()))return empty;
  const started=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("trigger",sql.NVarChar(40),trigger.slice(0,40)).input("algorithm",sql.NVarChar(100),EVERGREEN_AUTONOMY_ALGORITHM).query<{id:string}>(`INSERT cacsms.EvergreenAutonomyRuns(WorkspaceId,TriggerSource,AlgorithmVersion,Status) OUTPUT CONVERT(nvarchar(36),inserted.EvergreenAutonomyRunId) id VALUES(@workspace,@trigger,@algorithm,N'running')`);const runId=started.recordset[0].id;
  let generated=0,updated=0,certified=0,refreshQueued=0,duplicates=0,held=0;const freshnessValues:number[]=[];const reuseValues:number[]=[];const confidenceValues:number[]=[];
  try{
    const records=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Knowledge>(`SELECT CONVERT(nvarchar(36),KnowledgeRecordId) KnowledgeRecordId,RecordType,Title,Summary,Status,Source,CONVERT(float,Confidence) Confidence,CONVERT(float,QualityScore) QualityScore,MetadataJson,UpdatedAt FROM cacsms.KnowledgeRecords WHERE WorkspaceId=@workspace AND ArchivedAt IS NULL ORDER BY UpdatedAt DESC`)).recordset;
    const existing=(await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).query<Existing>(`SELECT CONVERT(nvarchar(36),RecordId) RecordId,MetadataJson FROM cacsms.OpportunityOperationalRecords WHERE WorkspaceId=@workspace AND PageSlug=N'evergreen-knowledge-bank'`)).recordset;const bySource=new Map<string,Existing>();for(const row of existing){const source=String(parse(row.MetadataJson).sourceKnowledgeRecordId??"").toLowerCase();if(source)bySource.set(source,row);}
    const titles=new Set<string>();
    for(const record of records){
      const duplicate=titles.has(normalized(record.Title));titles.add(normalized(record.Title));const ageDays=Math.max(0,(Date.now()-new Date(record.UpdatedAt).getTime())/86_400_000);const freshness=round(Math.max(0,100-ageDays*1.35));const quality=numeric(record.QualityScore,80);const confidence=numeric(record.Confidence,80);const sourceTrust=record.Status.toLowerCase()==="verified"?96:record.Status.toLowerCase()==="review"?72:58;const reuseReadiness=round(quality*.32+confidence*.23+freshness*.2+reusePotential(record.RecordType)*.25);const evergreenScore=round(quality*.3+confidence*.2+freshness*.25+reusePotential(record.RecordType)*.25);const riskScore=round((100-quality)*.25+(100-confidence)*.25+(100-freshness)*.3+(100-sourceTrust)*.2);const action=duplicate?"auto-deduplicate":riskScore>settings.MaximumRisk?"auto-hold-risk":freshness<settings.RefreshThreshold?"auto-queue-refresh":evergreenScore>=settings.CertifyThreshold?"auto-certify-evergreen":"autonomous-monitor";const status=action==="auto-deduplicate"?"Auto-deduplicated":action==="auto-hold-risk"?"Auto-held by risk":action==="auto-queue-refresh"?"Autonomous refresh queued":action==="auto-certify-evergreen"?"Auto-certified Evergreen":"Autonomous monitored";const progress=action==="auto-certify-evergreen"?100:action==="auto-queue-refresh"?65:action==="auto-hold-risk"?0:Math.max(45,Math.round(evergreenScore));const rationale={algorithm:EVERGREEN_AUTONOMY_ALGORITHM,sourceKnowledgeRecordId:record.KnowledgeRecordId,recordType:record.RecordType,source:record.Source,evergreenScore,freshness,quality,confidence,sourceTrust,reuseReadiness,riskScore,duplicate,action,humanInputRequired:false};let operational=bySource.get(record.KnowledgeRecordId.toLowerCase());
      const title=`${record.Title} — Evergreen Intelligence`;const description=`${record.Summary||"Reusable verified knowledge asset."} Continuously governed for freshness, trust, deduplication, and autonomous reuse.`.slice(0,1000);
      if(!operational){const inserted=await pool.request().input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("title",sql.NVarChar(300),title.slice(0,300)).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),record.RecordType).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(evergreenScore)).input("progress",sql.TinyInt,progress).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query<{RecordId:string}>(`INSERT cacsms.OpportunityOperationalRecords(WorkspaceId,PageSlug,RecordType,Title,Description,Category,Status,OwnerName,Score,Progress,StartAt,MetadataJson) OUTPUT CONVERT(nvarchar(36),inserted.RecordId) RecordId VALUES(@workspace,N'evergreen-knowledge-bank',N'autonomous-evergreen-asset',@title,@description,@category,@status,N'Evergreen Autonomy Engine',@score,@progress,SYSUTCDATETIME(),@metadata)`);operational={RecordId:inserted.recordset[0].RecordId,MetadataJson:JSON.stringify(rationale)};bySource.set(record.KnowledgeRecordId.toLowerCase(),operational);generated++;}else{await pool.request().input("record",sql.UniqueIdentifier,operational.RecordId).input("title",sql.NVarChar(300),title.slice(0,300)).input("description",sql.NVarChar(1000),description).input("category",sql.NVarChar(120),record.RecordType).input("status",sql.NVarChar(60),status).input("score",sql.TinyInt,Math.round(evergreenScore)).input("progress",sql.TinyInt,progress).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`UPDATE cacsms.OpportunityOperationalRecords SET Title=@title,Description=@description,Category=@category,Status=@status,OwnerName=N'Evergreen Autonomy Engine',Score=@score,Progress=@progress,MetadataJson=@metadata,UpdatedAt=SYSUTCDATETIME() WHERE RecordId=@record`);updated++;}
      await pool.request().input("run",sql.UniqueIdentifier,runId).input("knowledge",sql.UniqueIdentifier,record.KnowledgeRecordId).input("operational",sql.UniqueIdentifier,operational.RecordId).input("action",sql.NVarChar(60),action).input("evergreen",sql.Decimal(5,2),evergreenScore).input("freshness",sql.Decimal(5,2),freshness).input("reuse",sql.Decimal(5,2),reuseReadiness).input("quality",sql.Decimal(5,2),quality).input("risk",sql.Decimal(5,2),riskScore).input("confidence",sql.Decimal(5,2),confidence).input("rationale",sql.NVarChar(sql.MAX),JSON.stringify(rationale)).query(`INSERT cacsms.EvergreenAutonomyDecisions(EvergreenAutonomyRunId,KnowledgeRecordId,OperationalRecordId,Action,EvergreenScore,FreshnessScore,ReuseReadiness,QualityScore,RiskScore,Confidence,RationaleJson) VALUES(@run,@knowledge,@operational,@action,@evergreen,@freshness,@reuse,@quality,@risk,@confidence,@rationale)`);
      if(action==="auto-certify-evergreen")certified++;else if(action==="auto-queue-refresh")refreshQueued++;else if(action==="auto-deduplicate")duplicates++;else if(action==="auto-hold-risk")held++;freshnessValues.push(freshness);reuseValues.push(reuseReadiness);confidenceValues.push(confidence);
    }
    const average=(values:number[])=>values.length?round(values.reduce((a,b)=>a+b,0)/values.length):0;const averageFreshness=average(freshnessValues);const averageReuseReadiness=average(reuseValues);const averageConfidence=average(confidenceValues);await pool.request().input("run",sql.UniqueIdentifier,runId).input("workspace",sql.UniqueIdentifier,settings.WorkspaceId).input("scanned",sql.Int,records.length).input("generated",sql.Int,generated).input("updated",sql.Int,updated).input("certified",sql.Int,certified).input("refresh",sql.Int,refreshQueued).input("duplicates",sql.Int,duplicates).input("held",sql.Int,held).input("freshness",sql.Decimal(5,2),averageFreshness).input("reuse",sql.Decimal(5,2),averageReuseReadiness).input("confidence",sql.Decimal(5,2),averageConfidence).input("interval",sql.Int,settings.RunIntervalSeconds).query(`UPDATE cacsms.EvergreenAutonomyRuns SET Status=N'completed',RecordsScanned=@scanned,AssetsGenerated=@generated,AssetsUpdated=@updated,AssetsCertified=@certified,RefreshQueued=@refresh,DuplicatesSuppressed=@duplicates,AssetsHeld=@held,AverageFreshness=@freshness,AverageReuseReadiness=@reuse,AverageConfidence=@confidence,CompletedAt=SYSUTCDATETIME() WHERE EvergreenAutonomyRunId=@run;UPDATE cacsms.EvergreenAutonomySettings SET Enabled=1,LastRunAt=SYSUTCDATETIME(),NextRunAt=DATEADD(SECOND,@interval,SYSUTCDATETIME()),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace`);return {runId,status:"completed",scanned:records.length,generated,updated,certified,refreshQueued,duplicates,held,averageFreshness,averageReuseReadiness,averageConfidence};
  }catch(error){const message=error instanceof Error?error.message:"Autonomous evergreen cycle failed";await pool.request().input("run",sql.UniqueIdentifier,runId).input("error",sql.NVarChar(1000),message.slice(0,1000)).query(`UPDATE cacsms.EvergreenAutonomyRuns SET Status=N'failed',ErrorMessage=@error,CompletedAt=SYSUTCDATETIME() WHERE EvergreenAutonomyRunId=@run`);throw error;}
}
