import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";
import type {EngineItem,EngineMetric} from "@/types/intelligence-engine";
import type {GapData,ScoringData,ScoringWeight} from "@/types/gap-scoring";

type ItemRow={IntelligenceItemId:string;Title:string;Subtitle:string|null;Category:string;Score:number;State:string;AttributesJson:string;IsRisk:boolean;IsWatchlisted:boolean};
const mapItem=(r:ItemRow):EngineItem=>({id:String(r.IntelligenceItemId),title:r.Title,subtitle:r.Subtitle||"",category:r.Category,score:Number(r.Score),state:r.State,attributes:JSON.parse(r.AttributesJson),risk:Boolean(r.IsRisk),watchlisted:Boolean(r.IsWatchlisted)});
async function workspaceId(){const pool=await getMssqlPool();const result=await pool.request().query<{WorkspaceId:string}>(`SELECT TOP(1) WorkspaceId FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;`);if(!result.recordset[0])throw new Error("No active workspace.");return result.recordset[0].WorkspaceId;}
async function base(slug:string){const pool=await getMssqlPool(),workspace=await workspaceId();const [settings,items]=await Promise.all([
 pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).query<{MetricsJson:string;LastRunAt:Date|null}>(`SELECT MetricsJson,LastRunAt FROM cacsms.IntelligenceEngineSettings WHERE WorkspaceId=@workspace AND EngineSlug=@slug;`),
 pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).query<ItemRow>(`SELECT TOP(100) IntelligenceItemId,Title,Subtitle,Category,Score,State,AttributesJson,IsRisk,IsWatchlisted FROM cacsms.IntelligenceItems WHERE WorkspaceId=@workspace AND EngineSlug=@slug ORDER BY Score DESC,CreatedAt DESC;`)
 ]);if(!settings.recordset[0])throw new Error("Engine is not configured.");return{workspace,pool,metrics:JSON.parse(settings.recordset[0].MetricsJson) as EngineMetric[],lastRunAt:settings.recordset[0].LastRunAt?new Date(settings.recordset[0].LastRunAt).toISOString():null,items:items.recordset.map(mapItem)};}

export async function getGapData():Promise<GapData>{const result=await base("gap-detection"),items=result.items,high=items.filter(x=>x.score>=90).length,low=items.filter(x=>String(x.attributes.competition)==="Low").length,reach=items.reduce((s,x)=>s+Number(x.attributes.reach||0),0);return{metrics:[{value:String(items.length),label:"Detected Gaps",detail:"Live database records",tone:"purple"},{value:String(high),label:"High-Potential",detail:"Score 90 or above",tone:"green"},{value:String(low),label:"Low Competition",detail:"Calculated from records",tone:"orange"},{value:`${reach}M`,label:"Est. Audience Reach",detail:"Across stored gaps",tone:"blue"}],items,lastRunAt:result.lastRunAt};}
export async function runGapScan(){const {pool,workspace}=await base("gap-detection"),stamp=new Date().toLocaleDateString("en-GB");const result=await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("title",sql.NVarChar(300),`New underserved topic · ${stamp}`).query<ItemRow>(`INSERT cacsms.IntelligenceItems(WorkspaceId,EngineSlug,Title,Subtitle,Category,Score,State,AttributesJson) OUTPUT inserted.IntelligenceItemId,inserted.Title,inserted.Subtitle,inserted.Category,inserted.Score,inserted.State,inserted.AttributesJson,inserted.IsRisk,inserted.IsWatchlisted VALUES(@workspace,N'gap-detection',@title,N'Generated from the latest gap scan',N'Missing Coverage',84,N'Validate',N'{"demand":"High","competition":"Low","potential":84,"market":"Global","trend":87,"x":45,"y":35,"reach":16}');UPDATE cacsms.IntelligenceEngineSettings SET LastRunAt=SYSUTCDATETIME(),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=N'gap-detection';`);return mapItem(result.recordset[0]);}
export async function createGapOpportunity(id:string){const {pool,workspace}=await base("gap-detection");const result=await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("id",sql.UniqueIdentifier,id).query<{OpportunityId:string}>(`DECLARE @brand uniqueidentifier=(SELECT TOP(1) BrandId FROM cacsms.Brands WHERE WorkspaceId=@workspace AND IsActive=1);DECLARE @title nvarchar(300),@subtitle nvarchar(400),@category nvarchar(100),@score tinyint;SELECT @title=Title,@subtitle=Subtitle,@category=Category,@score=Score FROM cacsms.IntelligenceItems WHERE WorkspaceId=@workspace AND EngineSlug=N'gap-detection' AND IntelligenceItemId=@id;IF @title IS NULL THROW 50008,'Gap not found.',1;INSERT cacsms.Opportunities(WorkspaceId,BrandId,Title,Subtitle,Category,EstimatedValue,Confidence,Timing,OwnerName,OpportunityScore,Status,MarketDemand,StrategicFit,ExecutionReadiness,CompetitiveWhitespace,IsHighPriority,IsAtRisk) OUTPUT inserted.OpportunityId VALUES(@workspace,@brand,@title,@subtitle,@category,18000000,@score,N'Act now',N'Gap Detection',@score,N'Ready to validate',@score,88,74,92,CASE WHEN @score>=90 THEN 1 ELSE 0 END,0);`);return{opportunityId:String(result.recordset[0].OpportunityId)};}

export async function getScoringData():Promise<ScoringData>{const result=await base("scoring-engine");const weights=await result.pool.request().input("workspace",sql.UniqueIdentifier,result.workspace).query<{FactorKey:string;Label:string;Description:string;Weight:number;Rating:"Low"|"Medium"|"High"}>(`SELECT FactorKey,Label,Description,Weight,Rating FROM cacsms.OpportunityScoringWeights WHERE WorkspaceId=@workspace AND ModelName=N'Opportunity v3.2' ORDER BY CASE FactorKey WHEN N'demand' THEN 1 WHEN N'gap' THEN 2 WHEN N'momentum' THEN 3 WHEN N'resonance' THEN 4 WHEN N'strategicFit' THEN 5 ELSE 6 END;`);const scores=result.items.map(x=>x.score),aggregateAverage=scores.length?Number((scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1)):0,exceptional=scores.filter(x=>x>=85).length;const metrics:EngineMetric[]=[{value:String(scores.length),label:"Opportunities Scored",detail:"Stored scoring records",tone:"purple"},{value:String(exceptional),label:"High-Value Opportunities",detail:"Score 85 or above",tone:"green"},{value:String(aggregateAverage),label:"Average Score",detail:"Calculated live",tone:"orange"},{value:"Opportunity v3.2",label:"Active Scoring Model",detail:"Persisted weight model",tone:"blue"}];return{metrics,items:result.items,lastRunAt:result.lastRunAt,modelName:"Opportunity v3.2",weights:weights.recordset.map(x=>({key:x.FactorKey,label:x.Label,description:x.Description,weight:Number(x.Weight),rating:x.Rating})),averageScore:aggregateAverage,distribution:{exceptional,strong:scores.filter(x=>x>=70&&x<85).length,moderate:scores.filter(x=>x>=50&&x<70).length,low:scores.filter(x=>x<50).length}};}
export async function saveScoringWeights(weights:ScoringWeight[]){if(weights.length!==6||weights.reduce((s,x)=>s+Number(x.weight),0)!==100)throw new Error("Scoring weights must total 100%.");const pool=await getMssqlPool(),workspace=await workspaceId(),transaction=new sql.Transaction(pool);await transaction.begin();try{for(const item of weights){await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).input("key",sql.NVarChar(60),item.key).input("weight",sql.TinyInt,item.weight).query(`UPDATE cacsms.OpportunityScoringWeights SET Weight=@weight,UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND ModelName=N'Opportunity v3.2' AND FactorKey=@key;`);}await transaction.commit();}catch(error){await transaction.rollback();throw error;}}
export async function runScoring(){const data=await getScoringData(),pool=await getMssqlPool(),workspace=await workspaceId(),transaction=new sql.Transaction(pool);await transaction.begin();try{for(const item of data.items){const total=data.weights.reduce((sum,w)=>sum+(Number(item.attributes[w.key]??item.score)*w.weight/100),0),score=Math.round(total);await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).input("id",sql.UniqueIdentifier,item.id).input("score",sql.TinyInt,score).query(`UPDATE cacsms.IntelligenceItems SET Score=@score,UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=N'scoring-engine' AND IntelligenceItemId=@id;`);}await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).query(`UPDATE cacsms.IntelligenceEngineSettings SET LastRunAt=SYSUTCDATETIME(),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=N'scoring-engine';`);await transaction.commit();return getScoringData();}catch(error){await transaction.rollback();throw error;}}
