import sql from "mssql";
import {getMssqlPool,getDatabaseHealth} from "@/lib/database/mssql";
import {homeOperationalPages} from "@/lib/home-operational-pages";
import type {HomeOperationalResponse,OperationalRow,PageStatus} from "@/types/home-remaining-pages";
async function ctx(){const pool=await getMssqlPool(),r=await pool.request().query<{WorkspaceId:string}>(`SELECT TOP(1) WorkspaceId FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;`);if(!r.recordset[0])throw new Error("No active workspace.");return{pool,w:r.recordset[0].WorkspaceId}}
const normalize=(s:string):PageStatus=>({active:"running","in-review":"warning",approved:"completed",draft:"not-started",scheduled:"queued",published:"completed",info:"read",success:"healthy",critical:"failed"} as Record<string,PageStatus>)[s]||s as PageStatus;
export async function getOperationalData(slug:string):Promise<HomeOperationalResponse>{const config=homeOperationalPages[slug];if(!config)throw new Error("Page not found.");if(slug==="system-health"){const db=await getDatabaseHealth(),ok=db.status==="connected";return{generatedAt:db.checkedAt,metrics:config.metricLabels.map((label,i)=>({key:`health-${i}`,label,value:i===0?(ok?"100%":"0%"):i===1?(ok?1:0):i===3?(ok?0:1):i===5?`${db.latencyMs} ms`:0,trend:"flat"})),rows:[{id:"mssql",title:"Microsoft SQL Server",subtitle:db.database,status:ok?"healthy":"offline",values:{category:"Database",latency:`${db.latencyMs} ms`,uptime:ok?"Connected":"Unavailable",lastchecked:new Date(db.checkedAt).toLocaleString(),message:db.message}}],panels:{"Open Incidents":[],"Latest Checks":[{id:"db",title:"MSSQL connection",value:`${db.latencyMs} ms`,status:ok?"healthy":"offline"}]},total:1,page:1,pageSize:20}}
 const{pool,w}=await ctx();let rows:OperationalRow[]=[];
 if(slug==="production-pipeline"){const r=await pool.request().input("w",sql.UniqueIdentifier,w).query<any>(`SELECT TOP(100) p.ProductionId id,p.Title,p.Code,p.Stage,p.Progress,p.Status,p.DueAt,p.UpdatedAt,u.DisplayName owner FROM cacsms.Productions p LEFT JOIN cacsms.Users u ON u.UserId=p.OwnerId WHERE p.WorkspaceId=@w ORDER BY p.UpdatedAt DESC;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.Title,subtitle:x.Code,status:normalize(x.Status),progress:Number(x.Progress),updatedAt:new Date(x.UpdatedAt).toISOString(),values:{stage:x.Stage,progress:x.Progress,owner:x.owner||"Unassigned",due:x.DueAt?new Date(x.DueAt).toLocaleDateString():"—"}}))}
 if(slug==="rendering-monitor"){const r=await pool.request().query<any>(`SELECT TOP(100) j.RenderingJobId id,p.Title,j.AssetName,j.Engine,j.Preset,j.Progress,j.Status,j.EstimatedCompletionAt,j.UpdatedAt FROM cacsms.RenderingJobs j JOIN cacsms.Productions p ON p.ProductionId=j.ProductionId WHERE p.WorkspaceId='${w}' ORDER BY j.UpdatedAt DESC;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.Title,subtitle:x.AssetName,status:normalize(x.Status),progress:Number(x.Progress),updatedAt:new Date(x.UpdatedAt).toISOString(),values:{asset:x.AssetName||"—",engine:x.Engine,preset:x.Preset||"—",progress:x.Progress,eta:x.EstimatedCompletionAt?new Date(x.EstimatedCompletionAt).toLocaleString():"—"}}))}
 if(slug==="agent-activity"){const r=await pool.request().query<any>(`SELECT TOP(100) a.AgentRunId id,a.AgentName,a.AgentRole,a.TaskName,a.Status,a.QueueName,a.SuccessRate,a.CostAmount,a.LastHeartbeatAt,p.Title Production FROM cacsms.AgentRuns a LEFT JOIN cacsms.Productions p ON p.ProductionId=a.ProductionId WHERE p.WorkspaceId='${w}' OR a.ProductionId IS NULL ORDER BY a.UpdatedAt DESC;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.AgentName,subtitle:x.AgentRole,status:normalize(x.Status),values:{role:x.AgentRole,task:x.TaskName||"—",production:x.Production||"—",queue:x.QueueName||"—",success:x.SuccessRate==null?"—":`${x.SuccessRate}%`,costtoday:Number(x.CostAmount).toFixed(2),heartbeat:x.LastHeartbeatAt?new Date(x.LastHeartbeatAt).toLocaleString():"—"}}))}
 if(slug==="publishing-overview"){const r=await pool.request().query<any>(`SELECT TOP(100) j.PublishingJobId id,p.Title,j.Channel,j.AccountName,j.Status,j.ScheduledAt,j.PublishedAt,j.AttemptCount,j.UpdatedAt FROM cacsms.PublishingJobs j JOIN cacsms.Productions p ON p.ProductionId=j.ProductionId WHERE p.WorkspaceId='${w}' ORDER BY j.UpdatedAt DESC;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.Title,subtitle:x.Channel,status:normalize(x.Status),updatedAt:new Date(x.UpdatedAt).toISOString(),values:{channel:x.Channel,account:x.AccountName||"—",scheduled:x.ScheduledAt?new Date(x.ScheduledAt).toLocaleString():"—",published:x.PublishedAt?new Date(x.PublishedAt).toLocaleString():"—",attempts:x.AttemptCount}}))}
 if(slug==="calendar"){const r=await pool.request().input("w",sql.UniqueIdentifier,w).query<any>(`SELECT TOP(100) e.CalendarEventId id,e.Title,e.EventType,e.Status,e.StartsAt,e.EndsAt,e.UpdatedAt,p.Title Production,u.DisplayName Owner FROM cacsms.CalendarEvents e LEFT JOIN cacsms.Productions p ON p.ProductionId=e.ProductionId LEFT JOIN cacsms.Users u ON u.UserId=e.OwnerId WHERE e.WorkspaceId=@w ORDER BY e.StartsAt;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.Title,subtitle:x.EventType,status:normalize(x.Status),updatedAt:new Date(x.UpdatedAt).toISOString(),values:{type:x.EventType,start:new Date(x.StartsAt).toLocaleString(),end:x.EndsAt?new Date(x.EndsAt).toLocaleString():"—",production:x.Production||"—",owner:x.Owner||"Unassigned"}}))}
 if(slug==="notifications"){const r=await pool.request().input("w",sql.UniqueIdentifier,w).query<any>(`SELECT TOP(100) NotificationId id,Title,Body,Category,Severity,EntityType,EntityId,IsRead,CreatedAt FROM cacsms.Notifications WHERE WorkspaceId=@w ORDER BY CreatedAt DESC;`);rows=r.recordset.map((x:any)=>({id:String(x.id),title:x.Title,subtitle:x.Body,status:x.IsRead?"read":"unread",updatedAt:new Date(x.CreatedAt).toISOString(),values:{category:x.Category,severity:x.Severity,status:x.IsRead?"Read":"Unread",created:new Date(x.CreatedAt).toLocaleString(),entity:x.EntityType?`${x.EntityType}: ${x.EntityId||""}`:"—"}}))}
 const metrics=config.metricLabels.map((label,i)=>({key:`${slug}-${i}`,label,value:i===0?rows.length:i===1?rows.filter(x=>["running","unread","queued"].includes(x.status||"")).length:i===2?rows.filter(x=>["failed","warning","offline"].includes(x.status||"")).length:0,trend:"flat" as const}));return{generatedAt:new Date().toISOString(),metrics,rows,panels:Object.fromEntries(config.panelTitles.map(x=>[x,[]])),total:rows.length,page:1,pageSize:20};}
export async function runOperationalAction(slug:string,action:string){const{pool,w}=await ctx();if(slug==="notifications"&&action==="read-all")await pool.request().input("w",sql.UniqueIdentifier,w).query(`UPDATE cacsms.Notifications SET IsRead=1,ReadAt=SYSUTCDATETIME() WHERE WorkspaceId=@w AND IsRead=0;`);else if(slug==="system-health"&&action==="run-checks"){const h=await getDatabaseHealth();await pool.request().input("status",sql.NVarChar(30),h.status==="connected"?"healthy":"offline").input("latency",sql.Int,h.latencyMs).input("message",sql.NVarChar(1000),h.message).query(`INSERT cacsms.ServiceHealthChecks(ServiceName,Category,Status,LatencyMs,Message) VALUES(N'Microsoft SQL Server',N'Database',@status,@latency,@message);`)}else await pool.request().input("w",sql.UniqueIdentifier,w).input("event",sql.NVarChar(150),`home.${slug}.${action}`).query(`INSERT cacsms.AuditEvents(WorkspaceId,EventType,EntityType) VALUES(@w,@event,N'operational-page');`);return{success:true,status:"completed"};}
