import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";
import {engineDefinitions,intelligenceEngineSlugs} from "@/lib/intelligence-engine-definitions";
import type {EngineData,EngineItem,EngineMetric,EngineSettings} from "@/types/intelligence-engine";
type Row={IntelligenceItemId:string;Title:string;Subtitle:string|null;Category:string;Score:number;State:string;AttributesJson:string;IsRisk:boolean;IsWatchlisted:boolean};
function valid(slug:string){if(!intelligenceEngineSlugs.includes(slug))throw new Error("Unknown intelligence engine.");return slug;}
async function workspaceId(){const pool=await getMssqlPool();const result=await pool.request().query<{WorkspaceId:string}>(`SELECT TOP(1) WorkspaceId FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;`);if(!result.recordset[0])throw new Error("No active workspace.");return result.recordset[0].WorkspaceId;}
function mapItem(row:Row):EngineItem{return{id:String(row.IntelligenceItemId),title:row.Title,subtitle:row.Subtitle||"",category:row.Category,score:Number(row.Score),state:row.State,attributes:JSON.parse(row.AttributesJson),risk:Boolean(row.IsRisk),watchlisted:Boolean(row.IsWatchlisted)}}
export async function getEngineData(slug:string):Promise<EngineData>{valid(slug);const pool=await getMssqlPool(),workspace=await workspaceId();const [settingResult,itemResult]=await Promise.all([
 pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).query(`SELECT PrimaryMarket,SignalSensitivity,AutoCreateOpportunities,MetricsJson,LastRunAt FROM cacsms.IntelligenceEngineSettings WHERE WorkspaceId=@workspace AND EngineSlug=@slug;`),
 pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).query<Row>(`SELECT TOP(100) IntelligenceItemId,Title,Subtitle,Category,Score,State,AttributesJson,IsRisk,IsWatchlisted FROM cacsms.IntelligenceItems WHERE WorkspaceId=@workspace AND EngineSlug=@slug ORDER BY Score DESC,CreatedAt DESC;`)
 ]);const row=settingResult.recordset[0];if(!row)throw new Error("Intelligence engine is not configured.");const items=itemResult.recordset.map(mapItem),stored=JSON.parse(row.MetricsJson) as EngineMetric[],average=items.length?Math.round(items.reduce((s,x)=>s+x.score,0)/items.length):0,risks=items.filter(x=>x.risk||x.score<60).length;const metrics=stored.map((m,i)=>({...m,value:i===0?String(items.length):/risk|alert|issue/i.test(m.label)?String(risks):m.value.includes("%")?`${average}%`:String(new Set(items.map(x=>x.category)).size),detail:"Calculated from database records"}));return{metrics,settings:{primaryMarket:row.PrimaryMarket,signalSensitivity:Number(row.SignalSensitivity),autoCreateOpportunities:Boolean(row.AutoCreateOpportunities),lastRunAt:row.LastRunAt?new Date(row.LastRunAt).toISOString():null},items};}
export async function saveEngineSettings(slug:string,settings:EngineSettings){valid(slug);const pool=await getMssqlPool(),workspace=await workspaceId();await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).input("market",sql.NVarChar(150),settings.primaryMarket).input("sensitivity",sql.TinyInt,settings.signalSensitivity).input("auto",sql.Bit,settings.autoCreateOpportunities).query(`UPDATE cacsms.IntelligenceEngineSettings SET PrimaryMarket=@market,SignalSensitivity=@sensitivity,AutoCreateOpportunities=@auto,UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=@slug;`);}
export async function runEngineScan(slug:string){valid(slug);const pool=await getMssqlPool(),workspace=await workspaceId(),definition=engineDefinitions[slug];const title=`New ${definition.title} signal · ${new Date().toLocaleDateString("en-GB")}`;const result=await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).input("title",sql.NVarChar(300),title).query<Row>(`INSERT cacsms.IntelligenceItems(WorkspaceId,EngineSlug,Title,Subtitle,Category,Score,State,AttributesJson) OUTPUT inserted.IntelligenceItemId,inserted.Title,inserted.Subtitle,inserted.Category,inserted.Score,inserted.State,inserted.AttributesJson,inserted.IsRisk,inserted.IsWatchlisted VALUES(@workspace,@slug,@title,N'Generated from live engine scan',N'New intelligence',82,N'New',N'{"a":82,"b":79,"c":85,"confidence":82,"horizon":"Review now","direction":"Positive","impact":"High"}');UPDATE cacsms.IntelligenceEngineSettings SET LastRunAt=SYSUTCDATETIME(),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=@slug;`);return mapItem(result.recordset[0]);}
export async function openEngineItem(slug:string,id:string){valid(slug);const pool=await getMssqlPool(),workspace=await workspaceId();const result=await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).input("id",sql.UniqueIdentifier,id).query<{affected:number}>(`UPDATE cacsms.IntelligenceItems SET LastOpenedAt=SYSUTCDATETIME(),UpdatedAt=SYSUTCDATETIME() WHERE WorkspaceId=@workspace AND EngineSlug=@slug AND IntelligenceItemId=@id;SELECT @@ROWCOUNT affected;`);if(!result.recordset[0]?.affected)throw new Error("Intelligence item not found.");}
export async function createOpportunityFromEngine(slug:string,id:string){valid(slug);const pool=await getMssqlPool(),workspace=await workspaceId();const transaction=new sql.Transaction(pool);await transaction.begin();try{const item=await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).input("slug",sql.NVarChar(80),slug).input("id",sql.UniqueIdentifier,id).query<Row>(`SELECT IntelligenceItemId,Title,Subtitle,Category,Score,State,AttributesJson,IsRisk,IsWatchlisted FROM cacsms.IntelligenceItems WHERE WorkspaceId=@workspace AND EngineSlug=@slug AND IntelligenceItemId=@id;`);if(!item.recordset[0])throw new Error("Intelligence item not found.");const row=item.recordset[0],attributes=JSON.parse(row.AttributesJson) as Record<string,unknown>;const confidence=Math.max(0,Math.min(100,Number(attributes.confidence||attributes.authenticity||attributes.credibility||row.Score)));const result=await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).input("title",sql.NVarChar(300),row.Title).input("subtitle",sql.NVarChar(400),row.Subtitle||`Created from ${engineDefinitions[slug].title}`).input("category",sql.NVarChar(100),row.Category).input("confidence",sql.TinyInt,confidence).input("score",sql.TinyInt,row.Score).query<{OpportunityId:string}>(`DECLARE @brand uniqueidentifier=(SELECT TOP(1) BrandId FROM cacsms.Brands WHERE WorkspaceId=@workspace AND IsActive=1);INSERT cacsms.Opportunities(WorkspaceId,BrandId,Title,Subtitle,Category,EstimatedValue,Confidence,Timing,OwnerName,OpportunityScore,Status,MarketDemand,StrategicFit,ExecutionReadiness,CompetitiveWhitespace,IsHighPriority,IsAtRisk) OUTPUT inserted.OpportunityId VALUES(@workspace,@brand,@title,@subtitle,@category,18000000,@confidence,N'Review now',N'Opportunity Intelligence',@score,N'Ready to validate',@score,86,72,80,CASE WHEN @score>=90 THEN 1 ELSE 0 END,0);`);await new sql.Request(transaction).input("workspace",sql.UniqueIdentifier,workspace).input("entity",sql.NVarChar(100),String(result.recordset[0].OpportunityId)).input("payload",sql.NVarChar(sql.MAX),JSON.stringify({engineSlug:slug,itemId:id})).query(`INSERT cacsms.AuditEvents(WorkspaceId,EventType,EntityType,EntityId,PayloadJson) VALUES(@workspace,N'intelligence.opportunity.created',N'opportunity',@entity,@payload);`);await transaction.commit();return{opportunityId:String(result.recordset[0].OpportunityId)};}catch(error){await transaction.rollback();throw error;}}
