import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";
import {productionPages} from "@/lib/production-studio-pages";
import type {CreateProductionPayload,ProductionPageResponse,ProductionRecord,ProductionStatus} from "@/types/production-studio";

type ProductionRow={ProductionId:string;Code:string;Title:string;ProductionType:string;Stage:string;Status:string;Progress:number;DueAt:Date|null;UpdatedAt:Date;OwnerName:string|null;Priority:string};
async function workspace(){const pool=await getMssqlPool();const result=await pool.request().query<{WorkspaceId:string}>(`SELECT TOP(1) WorkspaceId FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;`);if(!result.recordset[0])throw new Error("No active workspace.");return{pool,id:result.recordset[0].WorkspaceId};}
function status(value:string):ProductionStatus{return({active:"in-progress","in-review":"review",approved:"approved",queued:"queued",draft:"draft",blocked:"blocked",completed:"completed",published:"published",failed:"failed",archived:"archived"} as Record<string,ProductionStatus>)[value]||"draft";}
function typeFilter(slug:string){return ({documentaries:"Documentary",stories:"Story","teaching-content":"Teaching Content",courses:"Course",explainers:"Explainer",tutorials:"Tutorial","corporate-content":"Corporate Content","marketing-content":"Marketing Content",podcasts:"Podcast","social-content":"Social Content","custom-productions":"Custom"} as Record<string,string>)[slug];}
export async function getProductionStudioData(slug:string):Promise<ProductionPageResponse>{const {pool,id}=await workspace(),config=productionPages[slug]||productionPages["all-productions"],filter=typeFilter(slug);const request=pool.request().input("workspace",sql.UniqueIdentifier,id).input("filter",sql.NVarChar(100),filter||null).input("slug",sql.NVarChar(80),slug);const result=await request.query<ProductionRow>(`SELECT TOP(100) p.ProductionId,p.Code,p.Title,p.ProductionType,p.Stage,p.Status,p.Progress,p.DueAt,p.UpdatedAt,u.DisplayName OwnerName,p.Priority FROM cacsms.Productions p LEFT JOIN cacsms.Users u ON u.UserId=p.OwnerId WHERE p.WorkspaceId=@workspace AND (@filter IS NULL OR p.ProductionType=@filter) AND (@slug<>N'drafts' OR p.Status=N'draft') AND (@slug<>N'completed-productions' OR p.Status IN(N'completed',N'published')) AND (@slug<>N'archived-productions' OR p.Status=N'archived') AND (@slug<>N'production-queue' OR p.Status=N'queued') ORDER BY p.UpdatedAt DESC;`);const rows=result.recordset,counts={total:rows.length,progress:rows.filter(x=>["active","queued"].includes(x.Status)).length,review:rows.filter(x=>x.Status==="in-review").length,completed:rows.filter(x=>["completed","published"].includes(x.Status)).length,risk:rows.filter(x=>x.Status==="blocked"||x.Priority==="critical").length};const values=[counts.total,counts.progress,counts.review,counts.completed,counts.risk,rows.length?`${Math.round(rows.reduce((s,x)=>s+x.Progress,0)/rows.length)}%`:"0%"];const metrics=(config?.metricLabels||[]).map((label,index)=>({key:`${slug}-${index}`,label,value:String(values[index]??0),helper:index===5?"Average progress":"Live database count"}));const records:ProductionRecord[]=rows.map(x=>({id:String(x.ProductionId),code:x.Code,title:x.Title,type:x.ProductionType,stage:x.Stage,owner:x.OwnerName||"Unassigned",progress:Number(x.Progress),status:status(x.Status),deadline:x.DueAt?new Date(x.DueAt).toISOString():undefined,updatedAt:new Date(x.UpdatedAt).toISOString(),values:{priority:x.Priority}}));const stageGroups=Object.entries(rows.reduce<Record<string,number>>((a,x)=>(a[x.Stage]=(a[x.Stage]||0)+1,a),{})).map(([label,value],i)=>({id:`stage-${i}`,label,value:String(value),detail:"productions"}));const risks=rows.filter(x=>x.Status==="blocked"||x.Priority==="critical").map(x=>({id:String(x.ProductionId),label:x.Title,value:x.Status,detail:x.Priority,status:status(x.Status)}));return{generatedAt:new Date().toISOString(),slug,metrics,records,panels:{[config?.panelTitles[0]||"Production Mix"]:stageGroups,[config?.panelTitles[1]||"Operational Alerts"]:risks},total:rows.length};}
export async function insertProduction(payload:CreateProductionPayload){const {pool,id}=await workspace(),request=pool.request().input("workspace",sql.UniqueIdentifier,id).input("title",sql.NVarChar(300),payload.title.trim()).input("type",sql.NVarChar(100),payload.contentType.trim()).input("metadata",sql.NVarChar(sql.MAX),JSON.stringify({topic:payload.topic,audience:payload.audience,language:payload.language,goals:payload.goals,references:payload.references,settings:payload.settings,templateId:payload.templateId}));const result=await request.query<{ProductionId:string;CreatedAt:Date}>(`DECLARE @brand uniqueidentifier=(SELECT TOP(1) BrandId FROM cacsms.Brands WHERE WorkspaceId=@workspace AND IsActive=1);DECLARE @owner uniqueidentifier=(SELECT TOP(1) UserId FROM cacsms.Users WHERE WorkspaceId=@workspace AND IsActive=1 ORDER BY CreatedAt);DECLARE @code nvarchar(50)=N'PRD-'+UPPER(LEFT(REPLACE(CONVERT(nvarchar(36),NEWID()),N'-',N''),10));INSERT cacsms.Productions(WorkspaceId,BrandId,OwnerId,Code,Title,ProductionType,Stage,Status,Priority,Progress,MetadataJson) OUTPUT inserted.ProductionId,inserted.CreatedAt VALUES(@workspace,@brand,@owner,@code,@title,@type,N'discover',N'draft',N'medium',0,@metadata);`);return{id:String(result.recordset[0].ProductionId),status:"draft",createdAt:new Date(result.recordset[0].CreatedAt).toISOString()};}
