import sql from "mssql";
import {getMssqlPool} from "@/lib/database/mssql";
import type {RecentProductionsQuery,RecentProductionsResponse,RecentProduction,RecentProductionStatus} from "@/types/recent-productions";
function clamp(v:unknown,f:number,min:number,max:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.trunc(n))):f}
export function parseRecentProductionsQuery(p:URLSearchParams){return{workspaceId:p.get("workspaceId")??undefined,brandId:p.get("brandId")??undefined,from:p.get("from")??undefined,to:p.get("to")??undefined,status:p.get("status")??undefined,type:p.get("type")??undefined,ownerId:p.get("ownerId")??undefined,channel:p.get("channel")??undefined,search:p.get("search")??undefined,sort:p.get("sort")??"completedAt:desc",page:clamp(p.get("page"),1,1,100000),pageSize:clamp(p.get("pageSize"),10,1,100)}}
type Row={ProductionId:string;Code:string;Title:string;ProductionType:string;Status:string;CompletedAt:Date|null;PublishedAt:Date|null;CreatedAt:Date;UpdatedAt:Date;OwnerId:string|null;OwnerName:string|null;OwnerRole:string|null;Channel:string|null};
function type(v:string):RecentProduction["type"]{const x=v.toLowerCase();if(/video|documentary|explainer|tutorial/.test(x))return"video";if(/audio|podcast/.test(x))return"audio";if(/article|corporate|social/.test(x))return"article";if(/script|story/.test(x))return"script";if(/image|visual/.test(x))return"image";return"other"}
export async function getRecentProductionsData(q:RecentProductionsQuery={}):Promise<RecentProductionsResponse>{const page=clamp(q.page,1,1,100000),pageSize=clamp(q.pageSize,10,1,100),pool=await getMssqlPool(),w=await pool.request().query<{WorkspaceId:string}>(`SELECT TOP(1) WorkspaceId FROM cacsms.Workspaces WHERE Status=N'active' ORDER BY CreatedAt;`),workspace=q.workspaceId||w.recordset[0]?.WorkspaceId;if(!workspace)throw new Error("No active workspace.");const result=await pool.request().input("workspace",sql.UniqueIdentifier,workspace).input("search",sql.NVarChar(300),q.search||null).query<Row>(`SELECT p.ProductionId,p.Code,p.Title,p.ProductionType,p.Status,p.CompletedAt,p.PublishedAt,p.CreatedAt,p.UpdatedAt,u.UserId OwnerId,u.DisplayName OwnerName,u.Role OwnerRole,(SELECT TOP(1) Channel FROM cacsms.PublishingJobs j WHERE j.ProductionId=p.ProductionId ORDER BY j.CreatedAt DESC) Channel FROM cacsms.Productions p LEFT JOIN cacsms.Users u ON u.UserId=p.OwnerId WHERE p.WorkspaceId=@workspace AND p.Status IN(N'completed',N'published',N'archived',N'failed') AND (@search IS NULL OR p.Title LIKE N'%'+@search+N'%') ORDER BY COALESCE(p.PublishedAt,p.CompletedAt,p.UpdatedAt) DESC;`);const all=result.recordset,total=all.length,productions=all.slice((page-1)*pageSize,page*pageSize).map(x=>({id:String(x.ProductionId),code:x.Code,title:x.Title,type:type(x.ProductionType),status:x.Status as RecentProductionStatus,owner:{id:x.OwnerId||"unassigned",name:x.OwnerName||"Unassigned",role:x.OwnerRole||undefined},completedAt:x.CompletedAt?new Date(x.CompletedAt).toISOString():null,publishedAt:x.PublishedAt?new Date(x.PublishedAt).toISOString():null,durationDays:x.CompletedAt?Math.max(0,Math.ceil((new Date(x.CompletedAt).getTime()-new Date(x.CreatedAt).getTime())/86400000)):null,channel:x.Channel,qualityScore:null,performanceScore:null,updatedAt:new Date(x.UpdatedAt).toISOString()}));const statuses=(["completed","published","archived","cancelled","failed"] as RecentProductionStatus[]).map(s=>({status:s,count:all.filter(x=>x.Status===s).length,percentage:total?Math.round(all.filter(x=>x.Status===s).length/total*100):0}));const types=Object.entries(all.reduce<Record<string,number>>((a,x)=>(a[x.ProductionType]=(a[x.ProductionType]||0)+1,a),{}));return{generatedAt:new Date().toISOString(),filters:{workspaceId:workspace,brandId:q.brandId||null,from:q.from||null,to:q.to||null},metrics:[{key:"recent",label:"Recent Productions",value:total,trend:"flat"},...statuses.slice(0,4).map(x=>({key:x.status,label:x.status,value:x.count,trend:"flat" as const})),{key:"quality",label:"Avg. Quality Score",value:"—",helper:"No quality records",trend:"flat"}],productions,statusBreakdown:statuses,typeBreakdown:types.map(([t,count])=>({type:t,count,percentage:total?Math.round(count/total*100):0})),performance:[],channelPerformance:[],activity:[],total,page,pageSize};}
export async function exportRecentProductionsCsv(q:RecentProductionsQuery={}){const d=await getRecentProductionsData({...q,pageSize:100});return [["Code","Title","Type","Status","Owner","CompletedAt","PublishedAt","Channel"],...d.productions.map(x=>[x.code,x.title,x.type,x.status,x.owner.name,x.completedAt||"",x.publishedAt||"",x.channel||""])].map(r=>r.map(c=>/[",\n]/.test(c)?`"${c.replace(/"/g,'""')}"`:c).join(",")).join("\n")}
