import type { WorkflowStage } from "./types";

export type LifecyclePhase = "intelligence" | "planning" | "creation" | "release" | "improvement";

export interface LifecyclePageLink {
  label: string;
  module: string;
  href: string;
  purpose: string;
  role: "primary" | "supporting";
}

export interface ProductionLifecycleStage {
  id: WorkflowStage;
  order: number;
  label: string;
  phase: LifecyclePhase;
  description: string;
  outcome: string;
  statusLabel: string;
  pages: LifecyclePageLink[];
}

const page = (label: string, module: string, href: string, purpose: string, role: LifecyclePageLink["role"] = "primary"): LifecyclePageLink => ({ label, module, href, purpose, role });

export const productionLifecycleStages: ProductionLifecycleStage[] = [
  {id:"discover",order:1,label:"Discover",phase:"intelligence",description:"Scan audience, market and knowledge signals for production opportunities.",outcome:"A qualified opportunity with clear audience relevance.",statusLabel:"342 New",pages:[page("Opportunity Dashboard","Opportunity Intelligence","/opportunity-intelligence/opportunity-dashboard","Review opportunity health and discovery performance."),page("Discovery Engine","Opportunity Intelligence","/opportunity-intelligence/discovery-engine","Run autonomous signal discovery."),page("Topic Discovery","Content Intelligence","/content-intelligence/topic-discovery","Identify production-ready topics."),page("Trend Intelligence","Content Intelligence","/content-intelligence/trend-intelligence","Inspect accelerating themes and demand."),page("Gap Detection","Opportunity Intelligence","/opportunity-intelligence/gap-detection","Find underserved knowledge and content gaps."),page("Prediction Engine","Knowledge Universe","/knowledge-universe/prediction-engine","Review forward-looking knowledge signals.","supporting")]},
  {id:"research",order:2,label:"Research",phase:"intelligence",description:"Investigate, corroborate and verify the opportunity and its supporting evidence.",outcome:"A traceable evidence pack ready for evaluation.",statusLabel:"64 In Progress",pages:[page("Research Workspace","Content Intelligence","/content-intelligence/research-workspace","Coordinate the research brief and evidence."),page("Source Analysis","Content Intelligence","/content-intelligence/source-analysis","Assess source authority and relevance."),page("Fact Verification","Content Intelligence","/content-intelligence/fact-verification","Verify material claims before use."),page("Knowledge Extraction","Content Intelligence","/content-intelligence/knowledge-extraction","Convert evidence into structured knowledge."),page("Citation Manager","Content Intelligence","/content-intelligence/citation-manager","Maintain citations and provenance."),page("Knowledge Repository","Knowledge Universe","/knowledge-universe/knowledge-repository","Retrieve reusable verified evidence.","supporting")]},
  {id:"evaluate",order:3,label:"Evaluate",phase:"intelligence",description:"Score, validate and prioritize production opportunities.",outcome:"An approved, rejected or deferred opportunity decision.",statusLabel:"28 High Priority",pages:[page("Scoring Engine","Opportunity Intelligence","/opportunity-intelligence/scoring-engine","Score strategic value, demand and feasibility."),page("Opportunity Portfolio","Opportunity Intelligence","/opportunity-intelligence/opportunity-portfolio","Compare and prioritize opportunities."),page("Editorial Board","Opportunity Intelligence","/opportunity-intelligence/editorial-board","Complete editorial evaluation and approval."),page("Executive Recommendations","Opportunity Intelligence","/opportunity-intelligence/executive-recommendations","Review decision-ready recommendations."),page("Knowledge Quality","Knowledge Universe","/knowledge-universe/knowledge-quality","Assess evidence confidence and completeness.","supporting")]},
  {id:"pre-plan",order:4,label:"Pre-Plan",phase:"planning",description:"Define format, audience, channels, structure and production requirements.",outcome:"An approved production brief and multi-format plan.",statusLabel:"18 Ready",pages:[page("Create Production","Production Studio","/production-studio/create-production","Create the canonical production record."),page("Multi-Format Planner","Opportunity Intelligence","/opportunity-intelligence/multi-format-planner","Define formats and channel derivatives."),page("Campaign Builder","Opportunity Intelligence","/opportunity-intelligence/campaign-builder","Set campaign structure and objectives."),page("Structure Dashboard","Story & Learning Design","/story-learning/structure-dashboard","Plan narrative or learning structure."),page("Template Dashboard","Templates","/templates/template-dashboard","Select reusable production templates."),page("Evergreen Knowledge Bank","Opportunity Intelligence","/opportunity-intelligence/evergreen-knowledge-bank","Attach reusable knowledge assets.","supporting")]},
  {id:"schedule",order:5,label:"Schedule",phase:"planning",description:"Plan timelines, assignments, dependencies and publication dates.",outcome:"A resourced schedule with dependencies and target dates.",statusLabel:"19 Scheduled",pages:[page("Opportunity Scheduler","Opportunity Intelligence","/opportunity-intelligence/opportunity-scheduler","Schedule approved opportunities."),page("Production Calendar","Production Studio","/production-studio/production-calendar","Manage production dates and milestones."),page("Production Queue","Production Studio","/production-studio/production-queue","Prioritize queued work."),page("Assignments","Collaboration","/collaboration/assignments","Assign owners and contributors."),page("Scheduled Productions","Automation Hub","/automation/scheduled-productions","Configure automated start times."),page("Publishing Scheduler","Publishing Center","/publishing/scheduler","Reserve distribution windows.","supporting")]},
  {id:"produce",order:6,label:"Produce",phase:"creation",description:"Create scripts, storyboards, visual, video and audio assets.",outcome:"Complete production assets ready for assembly.",statusLabel:"10 Active",pages:[page("Script Editor","Writing Studio","/writing/script-editor","Write and revise production scripts."),page("Storyboard Editor","Storyboard Studio","/storyboard/storyboard-editor","Create and refine visual sequences."),page("Image Generator","Visual Studio","/visuals/image-generator","Generate approved visual assets."),page("Scene Video Generator","Video Studio","/video/scene-video-generator","Produce scene-level video."),page("Narration Generator","Audio Studio","/audio/narration-generator","Generate narration and voice tracks."),page("Music Generator","Audio Studio","/audio/music-generator","Create music and supporting audio."),page("All Assets","Asset Library","/assets/all-assets","Review generated and licensed assets.","supporting")]},
  {id:"assemble",order:7,label:"Assemble",phase:"creation",description:"Build the master timeline and integrate every production asset.",outcome:"A synchronized master edit ready for quality review.",statusLabel:"6 In Progress",pages:[page("Master Timeline","Timeline Studio","/timeline/master-timeline","Assemble the full production timeline."),page("Auto Assemble","Timeline Studio","/timeline/auto-assemble","Build an initial automated edit."),page("Synchronization","Timeline Studio","/timeline/synchronization","Synchronize picture, voice, music and graphics."),page("Transition Manager","Timeline Studio","/timeline/transition-manager","Manage scene and track transitions."),page("Timeline Preview","Timeline Studio","/timeline/timeline-preview","Review the assembled production."),page("Production Pipeline","Production Studio","/production-pipeline","Track assembly progress and dependencies.","supporting")]},
  {id:"quality",order:8,label:"Quality",phase:"release",description:"Run AI and human quality, compliance, safety and accessibility reviews.",outcome:"A fully approved production with resolved findings.",statusLabel:"4 In Review",pages:[page("Quality Dashboard","Quality & Compliance","/quality/quality-dashboard","Review quality status and open findings."),page("Content QA","Quality & Compliance","/quality/content-qa","Validate content completeness and accuracy."),page("Fact Verification","Quality & Compliance","/quality/fact-verification","Revalidate material claims."),page("Visual QA","Quality & Compliance","/quality/visual-qa","Inspect visual quality and consistency."),page("Audio QA","Quality & Compliance","/quality/audio-qa","Inspect narration, music and loudness."),page("Accessibility Check","Quality & Compliance","/quality/accessibility-check","Validate accessible delivery."),page("Final Approval","Quality & Compliance","/quality/final-approval","Record final human or automated approval.")]},
  {id:"export",order:9,label:"Export",phase:"release",description:"Render and package approved production deliverables.",outcome:"Validated deliverable packages ready for distribution.",statusLabel:"3 Exporting",pages:[page("Export Dashboard","Export Center","/exports/export-dashboard","Monitor render and packaging activity."),page("Final Video Export","Export Center","/exports/final-video-export","Render the approved master video."),page("Editable Scene Package","Export Center","/exports/editable-scene-package","Package editable production sources."),page("Subtitle Package","Export Center","/exports/subtitle-package","Generate subtitle deliverables."),page("Publishing Package","Export Center","/exports/publishing-package","Prepare channel-ready output packages."),page("Export History","Export Center","/exports/export-history","Review completed and failed exports."),page("Download Center","Export Center","/exports/download-center","Access approved deliverables.")]},
  {id:"publish",order:10,label:"Publish",phase:"release",description:"Distribute approved outputs to configured publishing channels.",outcome:"A successfully published and traceable release.",statusLabel:"4 Today",pages:[page("Publishing Dashboard","Publishing Center","/publishing/publishing-dashboard","Monitor channel readiness and releases."),page("Channels","Publishing Center","/publishing/channels","Manage configured destinations."),page("Scheduler","Publishing Center","/publishing/scheduler","Schedule release dates and times."),page("SEO and Metadata","Publishing Center","/publishing/seo-and-metadata","Finalize discoverability metadata."),page("Thumbnail Optimizer","Publishing Center","/publishing/thumbnail-optimizer","Prepare channel thumbnails."),page("Publishing Queue","Publishing Center","/publishing/publishing-queue","Manage pending publications."),page("Publication History","Publishing Center","/publishing/publication-history","Review release records.")]},
  {id:"monitor",order:11,label:"Monitor",phase:"improvement",description:"Track audience, production and publishing performance in real time.",outcome:"Verified performance signals and actionable findings.",statusLabel:"28 Monitoring",pages:[page("Publishing Overview","Home","/home/publishing-overview","Monitor current publishing operations."),page("Audience Analytics","Analytics","/analytics/audience-analytics","Measure audience response and retention."),page("Engagement Analytics","Analytics","/analytics/engagement-analytics","Track comments, shares and interaction."),page("Production Analytics","Analytics","/analytics/production-analytics","Measure production efficiency."),page("Publishing Analytics","Analytics","/analytics/publishing-analytics","Compare channel performance."),page("System Health","Home","/home/system-health","Monitor operational reliability.","supporting")]},
  {id:"learn",order:12,label:"Learn",phase:"improvement",description:"Use verified outcomes to improve the autonomous production system.",outcome:"Approved learnings applied to models, rules and knowledge.",statusLabel:"AI Learning",pages:[page("Learning Engine","Opportunity Intelligence","/opportunity-intelligence/learning-engine","Convert outcomes into system recommendations."),page("Learning Analytics","Analytics","/analytics/learning-analytics","Measure learning and improvement trends."),page("Knowledge Analytics","Knowledge Universe","/knowledge-universe/knowledge-analytics","Evaluate knowledge reuse and gaps."),page("Agent Performance","Analytics","/analytics/agent-performance","Review agent effectiveness."),page("Memory","AI Agents","/agents/memory","Inspect institutional agent memory."),page("Audit History","Collaboration","/collaboration/audit-history","Review the evidence behind changes.","supporting")]},
  {id:"repeat",order:13,label:"Repeat",phase:"improvement",description:"Feed learning back into continuous opportunity discovery.",outcome:"A governed autonomous loop ready for the next opportunity.",statusLabel:"Auto Loop",pages:[page("Autonomy Modes","Opportunity Intelligence","/opportunity-intelligence/autonomy-modes","Control autonomous progression policies."),page("Executive Recommendations","Opportunity Intelligence","/opportunity-intelligence/executive-recommendations","Approve the next recommended actions."),page("Production Workflows","Automation Hub","/automation/production-workflows","Configure reusable lifecycle automation."),page("Event Triggers","Automation Hub","/automation/event-triggers","Start new cycles from verified signals."),page("Retry Manager","Automation Hub","/automation/retry-manager","Recover failed automated work."),page("Discovery Engine","Opportunity Intelligence","/opportunity-intelligence/discovery-engine","Begin the next discovery cycle.")]}
];

export const lifecyclePhases: Array<{id: LifecyclePhase; label: string; description: string}> = [
  {id:"intelligence",label:"Intelligence",description:"Discover, research and evaluate"},
  {id:"planning",label:"Planning",description:"Pre-plan and schedule"},
  {id:"creation",label:"Creation",description:"Produce and assemble"},
  {id:"release",label:"Release",description:"Quality, export and publish"},
  {id:"improvement",label:"Improvement",description:"Monitor, learn and repeat"}
];

export function getProductionLifecycleStage(id: string) {
  return productionLifecycleStages.find((stage) => stage.id === id);
}

/** Canonical pipeline view derived from lifecycle stages (single source of truth). */
export const productionPipeline = productionLifecycleStages.map((stage) => ({
  id: stage.id,
  label: stage.label,
  description: stage.description
}));
