import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { CreateProductionPage } from "@/components/production-studio/CreateProductionPage";
import { ProductionListPage } from "@/components/production-studio/ProductionListPage";
import { ProductionCalendarPage } from "@/components/production-studio/ProductionCalendarPage";
import { AllProductionsPage } from "@/components/production-studio/AllProductionsPage";
import { DocumentariesPage } from "@/components/production-studio/DocumentariesPage";
import { StoriesPage } from "@/components/production-studio/StoriesPage";
import { TeachingContentPage } from "@/components/production-studio/TeachingContentPage";
import { ArchivedProductionsPage, CompletedProductionsPage, CorporateContentPage, CoursesPage, CustomProductionsPage, DraftsPage, ExplainersPage, MarketingContentPage, PodcastsPage, ProductionQueuePage, SocialContentPage, TutorialsPage } from "@/components/production-studio/StructuredPortfolioPage";
import { productionPages, productionSlugs } from "@/lib/production-studio-pages";
export function generateStaticParams() { return productionSlugs.map((slug) => ({ slug })); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params; const config=productionPages[slug]; const title=slug==="create-production"?"Create Production":slug==="production-pipeline"?"Production Pipeline":slug==="production-calendar"?"Production Calendar":config?.title;return title?{title:`${title} | CACSMS`,description:config?.description}:{}}
export default async function ProductionStudioRoute({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==="create-production")return <CreateProductionPage/>;if(slug==="all-productions")return <AllProductionsPage/>;if(slug==="documentaries")return <DocumentariesPage/>;if(slug==="stories")return <StoriesPage/>;if(slug==="teaching-content")return <TeachingContentPage/>;if(slug==="courses")return <CoursesPage/>;if(slug==="explainers")return <ExplainersPage/>;if(slug==="tutorials")return <TutorialsPage/>;if(slug==="corporate-content")return <CorporateContentPage/>;if(slug==="marketing-content")return <MarketingContentPage/>;if(slug==="podcasts")return <PodcastsPage/>;if(slug==="social-content")return <SocialContentPage/>;if(slug==="custom-productions")return <CustomProductionsPage/>;if(slug==="production-queue")return <ProductionQueuePage/>;if(slug==="drafts")return <DraftsPage/>;if(slug==="completed-productions")return <CompletedProductionsPage/>;if(slug==="archived-productions")return <ArchivedProductionsPage/>;if(slug==="production-pipeline")redirect("/production-pipeline/index.html");if(slug==="production-calendar")return <ProductionCalendarPage/>;const config=productionPages[slug];if(!config)notFound();return <ProductionListPage config={config}/>}
