"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,BookOpenCheck,BrainCircuit,CheckCircle2,Clock3,GitBranch,GraduationCap,Network,RefreshCw,ShieldCheck,Sparkles,Target} from "lucide-react";
import type {StoryStructureRecord,StructureDashboardData} from "@/types/story-structure";
import styles from "./StructureDashboard.module.css";

async function load(){const response=await fetch("/api/story-learning/structure-dashboard",{cache:"no-store"});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||"Unable to load structure autonomy.");return body as StructureDashboardData;}
export function StructureDashboard(){const [data,setData]=useState<StructureDashboardData|null>(null);const [error,setError]=useState("");const [selectedId,setSelectedId]=useState("");const refresh=useCallback(async()=>{try{const next=await load();setData(next);setError("");setSelectedId(current=>current||next.structures[0]?.id||"");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load structure autonomy.");}},[]);useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer);},[refresh]);const last=data?.autonomy.lastRun;const selected=useMemo(()=>data?.structures.find(item=>item.id===selectedId)??data?.structures[0],[data,selectedId]);const groups=useMemo(()=>({narrative:data?.structures.filter(x=>x.mode==="narrative").length??0,learning:data?.structures.filter(x=>x.mode==="learning").length??0,hybrid:data?.structures.filter(x=>x.mode==="hybrid").length??0}),[data]);return <main className={styles.page}>
  <header className={styles.header}><div><span>STORY &amp; LEARNING DESIGN</span><h1>Autonomous Structure Dashboard</h1><p>Zero-input narrative architecture, learning design, agent routing, quality governance, and structure approval.</p></div><aside><em><i/>{data?.autonomy.state??"connecting"}</em><span><Clock3/>Every {data?.autonomy.intervalSeconds??30}s</span><span><ShieldCheck/>No human validation</span></aside></header>
  <section className={styles.engine}><BrainCircuit/><div><small>STRUCTURE AUTONOMY ENGINE</small><h2>Dual-path story and learning intelligence is active</h2><p>Productions are classified, structured, scored, agent-routed, risk-gated, and approved automatically.</p></div><aside><span><b>{last?.scanned??0}</b>Scanned</span><span><b>{last?.approved??0}</b>Approved</span><span><b>{last?.refining??0}</b>Refining</span><span><b>{last?.quality??0}%</b>Quality</span><span><b>{last?.confidence??0}%</b>Confidence</span></aside><em>{data?.autonomy.algorithmVersion??"dual-path-structure-intelligence-v6"}</em></section>
  {error?<div className={styles.error}><AlertTriangle/>{error}<button onClick={()=>void refresh()}><RefreshCw/>Reconnect</button></div>:null}
  <section className={styles.metrics}>{[{label:"Active Structures",value:data?.structures.length??0,detail:"Persistent production blueprints",icon:GitBranch},{label:"Auto-approved",value:last?.approved??0,detail:"Quality gates passed",icon:CheckCircle2},{label:"Structure Quality",value:`${last?.quality??0}%`,detail:"Coherence and pedagogy",icon:Target},{label:"Decision Confidence",value:`${last?.confidence??0}%`,detail:"Evidence-weighted confidence",icon:Sparkles}].map(({label,value,detail,icon:Icon})=><article key={label}><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></article>)}</section>
  <div className={styles.layout}><section className={styles.panel}><header><div><h2>Autonomous Structure Portfolio</h2><p>Live production structures governed by machine quality gates</p></div><span>{data?.structures.length??0} structures</span></header><div className={styles.records}>{data?.structures.map(item=><button className={item.id===selected?.id?styles.selected:""} key={item.id} onClick={()=>setSelectedId(item.id)}><i data-mode={item.mode}>{item.mode==="learning"?<GraduationCap/>:item.mode==="hybrid"?<Network/>:<GitBranch/>}</i><span><b>{item.title}</b><small>{item.framework} · {item.productionType}</small><em>{item.status}</em></span><strong>{item.progress}%<u><i style={{width:`${item.progress}%`}}/></u></strong></button>)}</div>{!data?.structures.length?<div className={styles.empty}><BrainCircuit/><b>Awaiting the next autonomous cycle</b><p>Structure records will appear without operator action.</p></div>:null}</section>
  <aside className={styles.side}><section className={styles.panel}><header><div><h2>Structure Composition</h2><p>Automatically classified paths</p></div></header><div className={styles.composition}><div style={{background:`conic-gradient(#5b35e8 0 ${groups.narrative/Math.max(1,data?.structures.length??0)*100}%,#08a6c9 0 ${(groups.narrative+groups.learning)/Math.max(1,data?.structures.length??0)*100}%,#10a461 0 100%)`}}><i><b>{data?.structures.length??0}</b><span>Total</span></i></div><ul><li><i/>Narrative <b>{groups.narrative}</b></li><li><i/>Learning <b>{groups.learning}</b></li><li><i/>Hybrid <b>{groups.hybrid}</b></li></ul></div></section><section className={styles.panel}><header><div><h2>Autonomy Health</h2><p>Live decision quality</p></div></header><Score label="Approved" value={percentage(last?.approved,last?.scanned)}/><Score label="Structure quality" value={last?.quality??0}/><Score label="Confidence" value={last?.confidence??0}/><Score label="Risk clearance" value={100-percentage(last?.held,last?.scanned)}/></section></aside></div>
  {selected?<StructureDetail item={selected}/>:null}
  </main>}

function StructureDetail({item}:{item:StoryStructureRecord}){return <section className={`${styles.panel} ${styles.detail}`}><header><div><small>{item.mode.toUpperCase()} STRUCTURE</small><h2>{item.title}</h2><p>{item.objective}</p></div><span>{item.status}</span></header><div className={styles.detailMeta}><span><small>Audience</small><b>{item.audience}</b></span><span><small>Framework</small><b>{item.framework}</b></span><span><small>Coherence</small><b>{item.coherence}%</b></span><span><small>Pedagogy</small><b>{item.pedagogy}%</b></span><span><small>Engagement</small><b>{item.engagement}%</b></span><span><small>Knowledge alignment</small><b>{item.knowledgeAlignment}%</b></span></div><div className={styles.blueprint}>{item.blueprint.map((stage,index)=><article key={stage.stage}><span>{index+1}</span><div><b>{stage.stage}</b><p>{stage.purpose}</p><small>{stage.agent}</small></div></article>)}</div><footer><BookOpenCheck/><span><b>Autonomous agent team</b><small>{item.agents.join(" · ")}</small></span><em><ShieldCheck/>Human input required: No</em></footer></section>}
function Score({label,value}:{label:string;value:number}){return <div className={styles.score}><span>{label}<b>{Math.round(value*10)/10}%</b></span><i><u style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></i></div>}
function percentage(value=0,total=0){return total?value/total*100:0;}
