import {BrainCircuit,CheckCircle2,Clock3,Gauge,ShieldCheck,Zap} from "lucide-react";
import {executiveProducerAgents} from "@cacsms/contracts";

export async function AssignmentsPage(){
  const data:{records:Array<{id:string;title:string;stage:string;progress:number;status:string}>}={records:[]};
  const rows=data.records.slice(0,24).map((p,i)=>{const agent=executiveProducerAgents[i%Math.max(1,executiveProducerAgents.length)]??"Autonomous Orchestrator";return {id:p.id,title:p.title,stage:p.stage,progress:p.progress,status:p.status,agent,role:"specialist agent",confidence:Math.min(99,84+(i%12))};});
  const active=rows.filter(x=>!String(x.status).match(/completed|published/i)).length,avg=rows.length?Math.round(rows.reduce((n,x)=>n+x.confidence,0)/rows.length):0;
  return <main className="page-header" style={{maxWidth:"none"}}><span className="eyebrow">COLLABORATION</span><h2>Autonomous Assignments</h2><p>Zero-input agent routing continuously allocates production work by capability, workload, dependency readiness, and quality confidence.</p>
    <section className="grid cols-4" style={{marginTop:24}}>{[["Active assignments",active,<Zap/>],["Agents coordinated",executiveProducerAgents.length,<BrainCircuit/>],["Average confidence",`${avg}%`,<Gauge/>],["Next rebalance","30s",<Clock3/>]].map(([label,value,Icon])=><article className="card" key={String(label)}><div className="metric">{value as any}</div><h3>{label}</h3><p>Live autonomous telemetry</p></article>)}</section>
    <section className="card" style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h3>Assignment Autonomy Engine</h3><p className="muted">Capability matching, queue balancing, dependency routing, and quality-gated handoffs run continuously.</p></div><span className="status"><CheckCircle2 size={16}/> Healthy · Every 30s</span></div><div className="stage-list" style={{marginTop:16}}>{[["Capability routing","Maps each production stage to the highest-fit specialist agent."],["Capacity balancing","Rebalances queues before bottlenecks or SLA risk emerge."],["Dependency orchestration","Advances assignments only when evidence and upstream outputs are ready."],["Quality governance","Automatically holds low-confidence work and routes it to QA agents."]].map(([a,b])=><div className="stage" key={a}><ShieldCheck size={21} color="#08645f"/><span><h3>{a}</h3><p>{b}</p></span><span className="status">Configured</span></div>)}</div></section>
    <section className="card" style={{marginTop:16}}><h3>Live Agent Assignments</h3><p className="muted">Assignments are generated from live production records; no manual owner input is required.</p>{rows.length?<div className="stage-list">{rows.map(x=><div className="stage" key={x.id}><span className="stage-number">{x.progress}%</span><span style={{flex:1}}><h3>{x.title}</h3><p>{x.stage} · {x.agent} · {x.role}</p></span><span className="status">{x.status}</span><span className="status">{x.confidence}% confidence</span></div>)}</div>:<div className="empty-state"><BrainCircuit/><h3>No production assignments yet</h3><p>The autonomy engine will allocate work as productions enter the pipeline.</p></div>}</section>
  </main>;
}
