"use client";

import { ArrowUp, Bell, BookOpen, ChevronDown, Download, Eye, FileText, Filter, FlaskConical, Flame, Medal, Plus, Rocket, Search, ShieldCheck, Target, Trophy, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import styles from "./CompetitorIntelligencePage.module.css";

const competitors=[
 {name:"ColdFusion",category:"Tech documentary",views:"8.4M",score:94,status:"Growing",tone:"green"},
 {name:"Business Insider Africa",category:"Business news",views:"1.8M",score:87,status:"Stable",tone:"blue"},
 {name:"African Tech Roundup",category:"Podcast",views:"428K",score:76,status:"Emerging",tone:"amber"},
 {name:"Industry 4.0 TV",category:"Industrial tech",views:"214K",score:68,status:"Declining",tone:"red"}
];
const modules=[["Topic Discovery","24",Search,"blue"],["Research Workspace","18",FlaskConical,"teal"],["Source Analysis","42",FileText,"violet"],["Fact Verification","156",ShieldCheck,"pink"],["Knowledge Extraction","89",Zap,"amber"],["Citation Manager","1.8K",BookOpen,"teal"]] as const;

export function CompetitorIntelligencePage(){const [query,setQuery]=useState("");const [tab,setTab]=useState("Overview");const visible=useMemo(()=>competitors.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())),[query]);return <section className={styles.page}>
 <div className={styles.crumb}>Content Intelligence <span>/</span> Competitor Intelligence</div>
 <header><div><h1>Competitor Intelligence</h1><p>Track competing channels, publishers, formats, topics, and performance patterns.</p><small>Last intelligence update: <b>8 minutes ago</b></small></div><div className={styles.actions}><button><Filter size={15}/>Filters</button><button><Download size={15}/>Export</button><button className={styles.primary}><Plus size={16}/>Add Competitor</button></div></header>
 <section className={styles.metrics}><article data-tone="red"><span>COMPETITORS TRACKED</span><strong>38 <small>↑ 8.4%</small></strong><p>+3 from last quarter</p><Trophy/></article><article data-tone="blue"><span>AVG. COMPETITOR VIEWS</span><strong>2.8M</strong><p>+12% YoY growth</p><Eye/></article><article data-tone="amber"><span>MARKET SHARE</span><strong>23%</strong><p>+3% from last month</p><Medal/></article><article data-tone="green"><span>OPPORTUNITY ALERTS</span><strong>12</strong><p>6 high priority</p><Zap/></article></section>
 <section className={styles.modules}>{modules.map(([label,value,Icon,tone])=><article data-tone={tone} key={label}><Icon size={17}/><strong>{value}</strong><span>{label}</span></article>)}</section>
 <div className={styles.content}><section className={styles.performance}><div className={styles.panelTitle}><h2><Trophy size={16}/>Competitor Performance</h2><button>View all 38 →</button></div><div className={styles.tabs}>{[["Overview","38"],["Content Tracking","156"],["Benchmarks","12"],["Opportunity Alerts","12"]].map(([label,count])=><button className={tab===label?styles.active:""} onClick={()=>setTab(label)} key={label}>{label}<b>{count}</b></button>)}</div><div className={styles.tools}><label><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search competitors..."/></label><button>All Categories <ChevronDown size={14}/></button><button>Sort: Relevance <ChevronDown size={14}/></button></div><div className={styles.list}>{visible.map(item=><article key={item.name}><div><b>{item.name}</b><small>{item.category} · {item.views} avg. views</small></div><strong>{item.views}<small>AVG. VIEWS</small></strong><strong>{item.score}<small>INTELLIGENCE</small></strong><em data-tone={item.tone}>● {item.status}</em></article>)}</div><footer>Showing 1 to {visible.length} of 38 entries</footer></section>
  <aside><section className={styles.panel}><div className={styles.panelTitle}><h2><Medal size={16}/>Benchmarks</h2><button>View details</button></div><div className={styles.benchmarks}><article><span>AVG. ENGAGEMENT RATE</span><b>4.8%</b><small>↑ +0.6%</small></article><article><span>CONTENT VELOCITY</span><b>12.4 / week</b><small>↑ +2.1</small></article><article><span>AVG. VIDEO DURATION</span><b>14:32</b><small>• steady</small></article><article><span>TOPIC DIVERSITY</span><b>87%</b><small>↑ +4%</small></article></div></section><section className={styles.panel}><div className={styles.panelTitle}><h2><Zap size={16}/>Opportunity Alerts</h2><button>View all 12</button></div><div className={styles.alerts}><p><ArrowUp/><span><b>ColdFusion</b> gained 2.4M views on AI content</span><small>2h ago</small></p><p><Flame/><span><b>Industry 4.0 TV</b> has 3 high-growth topics</span><small>5h ago</small></p><p><Target/><span><b>African Tech Roundup</b> low saturation in automation</span><small>1d ago</small></p><p><Rocket/><span><b>Business Insider Africa</b> expanding to video</span><small>2d ago</small></p></div></section></aside>
 </div><div className={styles.bottom}>Updated 13/07/2026, 2:49 PM</div>
 </section>}
