"use client";

import { Bell, BookOpen, BrainCircuit, CheckCheck, ChevronDown, Download, Eye, FileText, Filter, FlaskConical, GraduationCap, LayoutGrid, Palette, Plus, Rocket, Search, Sparkles, Target, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import styles from "./ResearchWorkspacePage.module.css";

const projects=[
 {title:"AI in Nigerian Manufacturing",owner:"Sarah A.",progress:78,status:"In progress",tone:"green"},
 {title:"Digital Twins for Industrial Automation",owner:"James P.",progress:64,status:"Agent working",tone:"blue"},
 {title:"The Future of Remote Work in Africa",owner:"Mia T.",progress:42,status:"Needs sources",tone:"amber"},
 {title:"Sustainable Energy in Sub-Saharan Africa",owner:"David K.",progress:100,status:"Ready",tone:"green"}
];
const modules=[["Opportunity Intelligence","20",Target,"teal"],["Knowledge Intelligence","1.8M",BookOpen,"blue"],["Writing Studio","19",Sparkles,"violet"],["Story & Learning","17",GraduationCap,"pink"],["Storyboard Studio","15",Palette,"amber"],["Visual Studio","20",LayoutGrid,"teal"]] as const;

export function ResearchWorkspacePage(){const [tab,setTab]=useState("All");const [query,setQuery]=useState("");const visible=useMemo(()=>projects.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())&&(tab==="All"||(tab==="Completed"&&item.progress===100)||(tab==="In Review"&&item.status==="Needs sources")||(tab==="Active"&&item.progress<100))),[query,tab]);return <section className={styles.page}>
 <div className={styles.crumb}>Content Intelligence <span>/</span> Research Workspace</div>
 <header><div><h1>Research Workspace</h1><p>Plan, coordinate, and monitor active research assignments from one operational workspace.</p><small>Last intelligence update: <b>8 minutes ago</b></small></div><div className={styles.actions}><button><Filter size={15}/>Filters</button><button><Download size={15}/>Export</button><button className={styles.primary}><Plus size={16}/>New Research</button></div></header>
 <section className={styles.metrics}><article data-tone="teal"><span>ACTIVE PROJECTS</span><strong>24 <small>↑ 12.4%</small></strong><p>+3 from last month</p><Rocket/></article><article data-tone="blue"><span>SOURCES COLLECTED</span><strong>156</strong><p>+12 verified today</p><BookOpen/></article><article data-tone="amber"><span>AWAITING REVIEW</span><strong>18</strong><p>6 urgent priority</p><Eye/></article><article data-tone="green"><span>RESEARCH QUALITY</span><strong>87%</strong><p>+4% improvement</p><CheckCheck/></article></section>
 <section className={styles.modules}>{modules.map(([label,value,Icon,tone])=><article data-tone={tone} key={label}><Icon size={17}/><strong>{value}</strong><span>{label}</span></article>)}</section>
 <div className={styles.grid}><section className={styles.panel}><div className={styles.panelTitle}><h2><FlaskConical size={16}/>Active Research Projects</h2><button>View all →</button></div><div className={styles.tabs}>{[["All","4"],["Active","2"],["Assigned to Me","1"],["In Review","1"],["Completed","1"]].map(([label,count])=><button className={tab===label?styles.active:""} onClick={()=>setTab(label)} key={label}>{label}<b>{count}</b></button>)}</div><label className={styles.search}><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search research workspace..."/></label><div className={styles.projects}>{visible.map(item=><article key={item.title}><div><b>{item.title}</b><small><UsersRound size={11}/>{item.owner} · {item.progress}% complete</small></div><strong data-tone={item.tone}>{item.progress}%<small>{item.status}</small></strong></article>)}</div><footer>Showing 1 to {visible.length} of 4 entries</footer></section>
  <aside><section className={styles.panel}><div className={styles.panelTitle}><h2><BrainCircuit size={16}/>Research Agents</h2><button>View configuration</button></div><div className={styles.agents}><article><i data-tone="blue"><Eye/></i><span><b>Scout Agent</b><small>Collecting 38 sources</small></span><em>● Live</em></article><article><i data-tone="violet"><BrainCircuit/></i><span><b>Analyst Agent</b><small>Synthesizing evidence</small></span><em>● Live</em></article><article><i data-tone="green"><CheckCheck/></i><span><b>Verifier Agent</b><small>Verifying 7 claims</small></span><em>● Live</em></article></div></section><section className={`${styles.panel} ${styles.brief}`}><div className={styles.panelTitle}><h2><Sparkles size={16}/>AI Intelligence Brief</h2><button>Generated from current signals</button></div><article><b>RESEARCH MOMENTUM</b><p>“The Future of AI in Nigerian Industry” has the strongest evidence growth. Source diversity is improving and synthesis is ready to begin.</p><small>Generated 8 minutes ago</small></article><footer><span>Review recommendation <b>Ready</b></span><span>Intelligence Health <b>92%</b></span></footer></section></aside>
 </div><div className={styles.bottom}>Updated 13/07/2026, 3:24 PM</div>
 </section>}
