"use client";

import { AlertTriangle, BookOpen, CheckCircle2, ChevronDown, Download, FileText, Filter, GraduationCap, Layers, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Target, UsersRound, XCircle } from "lucide-react";
import { useMemo, useState, type ComponentType } from "react";
import styles from "./ResearchDedicatedPages.module.css";

const moduleTiles=[["Topic Discovery","24",Target,"blue"],["Research Workspace","18",Search,"teal"],["Source Analysis","42",FileText,"violet"],["Fact Verification","156",ShieldCheck,"pink"],["Knowledge Extraction","89",Layers,"amber"],["Citation Manager","1.8K",BookOpen,"teal"]] as const;
type Metric={label:string;value:string;detail:string;tone:string;icon:ComponentType<{size?:number}>};

function Header({title,subtitle,action,tone,metrics}:{title:string;subtitle:string;action:string;tone:string;metrics:Metric[]}){return <><div className={styles.crumb}>Content Intelligence <span>/</span> {title}</div><header><div><h1 data-tone={tone}>{title}</h1><p>{subtitle}</p><small>Last intelligence update: <b>8 minutes ago</b></small></div><div className={styles.actions}><button><Filter size={15}/>Filters</button><button><Download size={15}/>Export</button><button className={styles.primary} data-tone={tone}><Plus size={16}/>{action}</button></div></header><section className={styles.metrics}>{metrics.map(({label,value,detail,tone:metricTone,icon:Icon})=><article data-tone={metricTone} key={label}><span>{label}</span><strong>{value}{label.includes("CHECKED")||label.includes("RESEARCH")?<small>↑ 12.4%</small>:null}</strong><p>{detail}</p><Icon/></article>)}</section><section className={styles.modules}>{moduleTiles.map(([label,value,Icon,tileTone])=><article data-tone={tileTone} key={label}><Icon size={17}/><strong>{value}</strong><span>{label}</span></article>)}</section></>}

const claims=[
 {text:"AI adoption in Nigerian manufacturing increased 47% in 2025",owner:"Sarah A.",evidence:"5 sources",status:"Verified",tone:"green"},
 {text:"Digital twins reduce industrial downtime by up to 30%",owner:"James P.",evidence:"2 conflicting sources",status:"Disputed",tone:"amber"},
 {text:"Remote work productivity is 22% higher than office-based",owner:"Mia T.",evidence:"Needs verification",status:"Unsupported",tone:"red"},
 {text:"Sustainable energy investments in Africa grew 18% in 2025",owner:"David K.",evidence:"3 pending sources",status:"Queued",tone:"blue"}
];

export function FactVerificationPage(){const [tab,setTab]=useState("Verification Queue");const [query,setQuery]=useState("");const visible=useMemo(()=>claims.filter(item=>item.text.toLowerCase().includes(query.toLowerCase())&&(tab==="Verification Queue"||item.status===tab)),[query,tab]);return <section className={styles.page}><Header title="Fact Verification" subtitle="Validate claims against independent evidence before content enters production or publication." action="New Claim" tone="violet" metrics={[{label:"CLAIMS CHECKED",value:"342",detail:"+38 from last month",tone:"violet",icon:FileText},{label:"VERIFIED",value:"301",detail:"88% verification rate",tone:"green",icon:CheckCircle2},{label:"DISPUTED",value:"27",detail:"Needs resolution",tone:"amber",icon:AlertTriangle},{label:"UNSUPPORTED",value:"14",detail:"Requires evidence",tone:"red",icon:XCircle}]}/><div className={styles.grid}><section className={styles.panel}><PanelTitle icon={ShieldCheck} title="Claims Awaiting Verification" action="View all →"/><Tabs active={tab} setActive={setTab} items={[["Verification Queue","14"],["Verified","301"],["Disputed","27"],["Unsupported","14"]]}/><label className={styles.search}><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search claims..."/></label><div className={styles.claims}>{visible.map(item=><article key={item.text}><div><b>{item.text}</b><small><UsersRound size={11}/>{item.owner} · <FileText size={11}/>{item.evidence}</small></div><span><em data-tone={item.tone}>{item.status}</em><small>{item.evidence}</small></span></article>)}</div><footer>Showing 1 to {visible.length} of 342 entries</footer></section><aside><section className={styles.panel}><PanelTitle icon={SlidersHorizontal} title="Verification Rules" action="View configuration"/><div className={styles.rules}><article><b>2</b><span>MINIMUM SOURCES</span><small>independent ✓</small></article><article><b>75</b><span>AUTHORITY THRESHOLD</span><small>/ 100 ✓</small></article><article><b>●</b><span>CONTRADICTION SCAN</span><small>Enabled ✓</small></article></div></section><Brief text="Industrial AI and agentic automation topics are showing strong demand growth with low content saturation. High opportunity window." footer="Verified"/></aside></div><Bottom time="3:16 PM"/></section>}

const curricula=[
 {name:"AI Automation for Business Leaders",desc:"Executive programme · 12 modules",score:92,modules:"8/12",status:"Active",tone:"green"},
 {name:"Industrial Digital Transformation",desc:"Professional course · 9 modules",score:78,modules:"6/9",status:"In Review",tone:"amber"},
 {name:"Introduction to Digital Twins",desc:"Foundation course · 6 modules",score:65,modules:"3/6",status:"Draft",tone:"blue"},
 {name:"Responsible AI Operations",desc:"Certification pathway · 14 modules",score:88,modules:"12/14",status:"Complete",tone:"violet"}
];
export function CurriculumResearchPage(){const [tab,setTab]=useState("Curricula");const [query,setQuery]=useState("");const visible=curricula.filter(item=>item.name.toLowerCase().includes(query.toLowerCase()));return <section className={styles.page}><Header title="Curriculum Research" subtitle="Develop accurate learning pathways, outcomes, modules, and assessments from trusted knowledge." action="New Curriculum" tone="violet" metrics={[{label:"CURRICULA IN RESEARCH",value:"18",detail:"+3 from last quarter",tone:"violet",icon:BookOpen},{label:"LEARNING OUTCOMES",value:"126",detail:"+18 this month",tone:"green",icon:Target},{label:"MODULES MAPPED",value:"74",detail:"87% complete",tone:"amber",icon:Layers},{label:"EXPERT REVIEWS DUE",value:"21",detail:"9 overdue",tone:"violet",icon:UsersRound}]}/><div className={styles.grid}><section className={styles.panel}><PanelTitle icon={GraduationCap} title="Curriculum Research Projects" action="View all 18 →"/><Tabs active={tab} setActive={setTab} items={[["Curricula","18"],["Learning Outcomes","126"],["Source Mapping","42"],["Expert Review","21"]]}/><label className={styles.search}><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search curriculum research..."/></label><div className={styles.curricula}>{visible.map(item=><article key={item.name}><div><b>{item.name}</b><small>{item.desc}</small></div><strong>{item.score}%<small>INTELLIGENCE</small></strong><strong>{item.modules}<small>MODULES</small></strong><em data-tone={item.tone}>● {item.status}</em></article>)}</div><footer>Showing 1 to {visible.length} of 18 entries</footer></section><aside><section className={styles.panel}><PanelTitle icon={SlidersHorizontal} title="Academic Controls" action="View configuration"/><div className={styles.controls}><article><span>OUTCOME FRAMEWORK</span><b>Bloom's taxonomy</b></article><article><span>SOURCE STANDARD</span><b>Academic + industry</b></article><article><span>REVIEW REQUIREMENT</span><b>Subject expert</b></article></div><div className={styles.controlChips}><span>Sort: Relevance</span><span>Academic + industry</span></div></section><Brief text="Industrial AI and generative AI topics are showing strong demand growth with low content saturation. High opportunity window." footer="Expert review pending"/></aside></div><Bottom time="3:16 PM"/></section>}

function PanelTitle({icon:Icon,title,action}:{icon:ComponentType<{size?:number}>;title:string;action:string}){return <div className={styles.panelTitle}><h2><Icon size={16}/>{title}</h2><button>{action}</button></div>}
function Tabs({active,setActive,items}:{active:string;setActive:(value:string)=>void;items:string[][]}){return <div className={styles.tabs}>{items.map(([label,count])=><button className={active===label?styles.active:""} onClick={()=>setActive(label)} key={label}>{label}<b>{count}</b></button>)}</div>}
function Brief({text,footer}:{text:string;footer:string}){return <section className={`${styles.panel} ${styles.brief}`}><PanelTitle icon={Sparkles} title="AI Intelligence Brief" action="Generated from current signals"/><article><b>OPPORTUNITY DETECTED</b><p>{text}</p><small>Generated 8 minutes ago</small></article><footer>Review recommendation <strong>{footer}</strong></footer></section>}
function Bottom({time}:{time:string}){return <div className={styles.bottom}>Updated 13/07/2026, {time}</div>}
