"use client";

import {
  AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, Building2, CheckCircle2,
  ChevronDown, ChevronLeft, ChevronRight, CircleHelp, CircleX, Database, Download,
  FileCheck2, FileText, Filter, Grid2X2, Info, Link2, List, MoreHorizontal, RefreshCw,
  ScanSearch, Search, ShieldCheck, Sparkles
} from "lucide-react";
import { useMemo, useState, type ComponentType } from "react";
import styles from "./SourceAnalysisPage.module.css";

type Tone="violet"|"green"|"amber"|"red"|"blue";
const metrics:[string,string,string,Tone,ComponentType<{size?:number}>][]=[
 ["486","Sources Analysed","+42 this week","violet",ScanSearch],["91%","Trusted Sources","442 approved","green",ShieldCheck],
 ["28","Bias Warnings","9 need review","amber",AlertTriangle],["14","Rejected","3 this week","red",CircleX],
 ["94%","Provenance Coverage","All critical claims linked","blue",Link2]
];
const sources=[
 {name:"World Economic Forum – Future of Jobs 2025",publisher:"World Economic Forum · Jan 2025",type:"Institutional Report",authority:98,method:"Strong",risk:"Low",corroboration:"12 sources",quality:96,recommendation:"Trusted",tone:"green",icon:Building2},
 {name:"State of AI 2026",publisher:"McKinsey & Company · Mar 2026",type:"Industry Research",authority:96,method:"Strong",risk:"Low–Medium",corroboration:"9 sources",quality:93,recommendation:"Trusted",tone:"green",icon:BarChart3},
 {name:"Nigeria ICT Sector Statistics",publisher:"National Bureau of Statistics · Q2 2026",type:"Government Dataset",authority:94,method:"Strong",risk:"Low",corroboration:"7 sources",quality:92,recommendation:"Primary source",tone:"green",icon:Building2},
 {name:"African AI Startups Report",publisher:"TechCabal · Jun 2026",type:"News Analysis",authority:84,method:"Moderate",risk:"Medium",corroboration:"5 sources",quality:82,recommendation:"Review context",tone:"amber",icon:BookOpen},
 {name:"Smart Manufacturing Survey",publisher:"Industry Association · Apr 2026",type:"Survey Report",authority:78,method:"Moderate",risk:"Medium",corroboration:"3 sources",quality:76,recommendation:"Limited use",tone:"amber",icon:FileText},
 {name:"Automation Will Replace 80% of Jobs",publisher:"Anonymous Automation Blog",type:"Unverified Article",authority:32,method:"Weak",risk:"High",corroboration:"0 sources",quality:41,recommendation:"Reject",tone:"red",icon:CircleHelp}
] as const;

export function SourceAnalysisPage(){const [tab,setTab]=useState("All Sources");const [query,setQuery]=useState("");const [refreshing,setRefreshing]=useState(false);const [view,setView]=useState<"list"|"grid">("list");const visible=useMemo(()=>sources.filter(item=>`${item.name} ${item.publisher} ${item.type}`.toLowerCase().includes(query.toLowerCase())),[query]);function refresh(){setRefreshing(true);window.setTimeout(()=>setRefreshing(false),600)}return <section className={styles.page}>
 <header className={styles.header}><div><div className={styles.crumb}>Content Intelligence <span>/</span> Source Analysis</div><h1>Source Analysis</h1><p>Assess source authority, relevance, freshness, bias, and evidential strength before use.</p></div><div className={styles.selectors}><button>Workspace · CACSMS Studio<ChevronDown size={13}/></button><button>Brand · CACSMS<ChevronDown size={13}/></button><button aria-label="Notifications"><Bell size={15}/></button></div></header>
 <div className={styles.layout}><main><section className={styles.workspaceBar}><i><ScanSearch size={23}/></i><div><b>Source Analysis Workspace</b><small>Last intelligence update: {refreshing?"just now":"4 minutes ago"}</small></div><span><i/>2 analyses running</span><button onClick={refresh}><RefreshCw className={refreshing?styles.spin:""} size={14}/>Refresh</button></section><section className={styles.metrics}>{metrics.map(([value,label,note,tone,Icon])=><article data-tone={tone} key={label}><i><Icon size={25}/></i><div><strong>{value}</strong><span>{label}</span><small>{note}</small></div></article>)}</section>
  <section className={styles.panel}><div className={styles.panelHead}><div><h2>Source Forensics Registry</h2><p>Evaluate authority, methodology, evidence depth, recency, bias, corroboration, and recommended usage.</p></div><button><Download size={14}/>Export</button><button aria-label="More options"><MoreHorizontal size={17}/></button></div><nav className={styles.tabs}>{[["All Sources","486"],["Trusted",""],["Needs Review",""],["Bias Warnings",""],["Rejected",""],["Recently Analysed",""]].map(([name,count])=><button className={tab===name?styles.active:""} onClick={()=>setTab(name)} key={name}>{name}{count?<b>{count}</b>:null}</button>)}</nav><div className={styles.tools}><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sources, domains, authors, or claims..."/></label><button><Filter size={14}/>Filters<b>4</b></button><button>Sort: Quality Score<ChevronDown size={13}/></button><span><button className={view==="list"?styles.selected:""} onClick={()=>setView("list")}><List size={15}/></button><button className={view==="grid"?styles.selected:""} onClick={()=>setView("grid")}><Grid2X2 size={15}/></button></span></div><section className={styles.evidence}><article><ShieldCheck/><span>Independent corroboration<b>88%</b></span></article><article><FileText/><span>Primary-source ratio<b>64%</b></span></article><article><Link2/><span>Broken links<b>12%</b></span></article></section><div className={styles.table}><div className={styles.tableHead}><span/><span>SOURCE / PUBLISHER</span><span>SOURCE TYPE</span><span>AUTHORITY</span><span>METHODOLOGY</span><span>BIAS RISK</span><span>CORROBORATION</span><span>QUALITY SCORE <Info size={9}/></span><span>RECOMMENDATION</span><span/></div>{visible.map((item,index)=>{const Icon=item.icon;return <article className={index===0?styles.highlight:""} key={item.name}><span>{index+1}</span><span><b>{item.name}</b><small>{item.publisher}</small></span><span className={styles.type}><i><Icon size={13}/></i>{item.type}</span><span className={styles.authority}><b>{item.authority}%</b><i><u data-tone={item.tone} style={{width:`${item.authority}%`}}/></i></span><span>{item.method}</span><em data-tone={item.tone}>{item.risk}</em><span>{item.corroboration}</span><span className={styles.score}><b>{item.quality} / 100</b><i><u style={{width:`${item.quality}%`}}/></i></span><em data-tone={item.tone}>{item.recommendation}</em><button><MoreHorizontal size={15}/></button></article>})}</div><footer className={styles.pagination}><span>Showing 1–{visible.length} of 486 sources</span><div><button><ChevronLeft size={13}/><ChevronLeft size={13}/></button><button className={styles.current}>1</button><button>2</button><button>3</button><button>…</button><button>81</button><button><ChevronRight size={13}/><ChevronRight size={13}/></button></div></footer></section>
 </main><aside><SelectedSource/><BiasProfile/><QualityAlerts/><SourceBrief/></aside></div></section>}

function SelectedSource(){return <section className={`${styles.panel} ${styles.selectedSource}`}><h2>Selected Source Analysis</h2><h3>World Economic Forum — Future of Jobs 2025</h3><div><figure><svg viewBox="0 0 120 75"><path d="M15 65 A45 45 0 1 1 105 65"/><path className={styles.gauge} d="M15 65 A45 45 0 1 1 105 65"/></svg><b>96<small>/ 100</small></b><em>Trusted</em></figure><section>{[["Authority",98],["Methodology",94],["Evidence depth",96],["Recency",92],["Transparency",95],["Bias neutrality",91]].map(([name,value])=><article key={name as string}><span>{name}</span><i><u style={{width:`${value}%`}}/></i><b>{value}</b></article>)}</section></div><button>View full methodology<ArrowRight size={13}/></button></section>}
function BiasProfile(){return <section className={`${styles.panel} ${styles.bias}`}><h2>Bias & Evidence Profile</h2>{[["Political bias","Neutral"],["Commercial bias","Low"],["Evidence type","Primary + secondary"],["Citations","184"],["Claims extracted","42"],["Contradictions","1"]].map(([name,value])=><article key={name}><span>{name}</span><b data-alert={name==="Contradictions"}>{value}</b></article>)}<div><span>Left</span><span>Neutral</span><span>Right</span><i><u/></i></div></section>}
function QualityAlerts(){return <section className={`${styles.panel} ${styles.alerts}`}><h2>Source Quality Alerts</h2><article data-tone="red"><AlertTriangle/><span><b>3 unsupported claims</b><small>Anonymous Automation Blog</small></span><ChevronRight/></article><article data-tone="amber"><AlertTriangle/><span><b>9 sources need context review</b></span><ChevronRight/></article><article data-tone="blue"><Info/><span><b>12 links require refresh</b></span><ChevronRight/></article></section>}
function SourceBrief(){return <section className={`${styles.panel} ${styles.brief}`}><div><h2><Sparkles size={17}/>AI Source Brief</h2><b>Evidence recommendation</b></div><p>The WEF report is suitable for strategic workforce claims, but country-level conclusions should be paired with Nigerian labour data.</p><span><b>Trusted</b><b>Use with local data</b><b>42 claims</b></span><footer><button>Open evidence map<ArrowRight size={12}/></button><button>Approve for use</button></footer></section>}
